//! Resource names and the Rust names generated for them.
//!
//! A resource name is what `{Res …}` and the resource editor show: letters, digits, `_`, `.`, `-` and `+`
//! (`welcome_text`, `Logo`, `okButton.Text` — the dotted form is what per-view localised
//! properties and imported `.resw` keys use), starting with a letter or `_`. The accessor generated by
//! `resources!` is its `snake_case` form (`okButton.Text` → `ok_button_text`).

/// Whether `name` is a valid resource name.
/// Whether `name` is a valid name for a `String` entry: any non-empty text. Strings also carry the keys of the
/// web's i18next bundles, which a `.kbres` file must hold losslessly (`header.settings`, `drive-shared`,
/// `2fa_title`, `files_one`, `a key: with spaces`); the `resources!` accessor is still [`rust_name`] (two names
/// that map to the same accessor are a compile error there). Other kinds keep [`is_valid_name`].
pub fn is_valid_string_name(name: &str) -> bool {
    !name.is_empty()
}

pub fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    !name.ends_with('.') && !name.contains("..") && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '-' | '+'))
}

/// The `snake_case` Rust identifier of a resource name (`WelcomeText` → `welcome_text`,
/// `okButton.Text` → `ok_button_text`, `HTTPServer2` → `http_server2`). A result that is a Rust
/// keyword gets a trailing `_` (`type` → `type_`); one starting with a digit a leading `_`.
pub fn rust_name(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut out = String::with_capacity(name.len() + 4);
    for (i, &c) in chars.iter().enumerate() {
        if c == '+' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            out.push_str("plus_");
            continue;
        }
        if c == '.' || c == '-' || c == ' ' || c == '_' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            continue;
        }
        if c.is_ascii_uppercase() {
            let prev = if i > 0 { chars[i - 1] } else { '_' };
            let next = chars.get(i + 1).copied().unwrap_or('_');
            let boundary = prev.is_ascii_lowercase() || prev.is_ascii_digit() || (prev.is_ascii_uppercase() && next.is_ascii_lowercase());
            if boundary && !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.ends_with('_') && !out.is_empty() {
            out.push('_');
        }
    }
    while out.ends_with('_') && out.len() > 1 {
        out.pop();
    }
    if out.is_empty() {
        out.push('_');
    }
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if is_keyword(&out) {
        out.push('_');
    }
    out
}

/// The `PascalCase` type name of a resource file stem (`resources` → `Resources`,
/// `main_view` → `MainView`, `app.icons` → `AppIcons`).
pub fn type_name(stem: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in stem.chars() {
        if c.is_ascii_alphanumeric() {
            if upper {
                out.push(c.to_ascii_uppercase());
                upper = false;
            } else {
                out.push(c);
            }
        } else {
            upper = true;
        }
    }
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, 'R');
    }
    out
}

fn is_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern" | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move" | "mut" | "pub" | "ref"
            | "return" | "self" | "static" | "struct" | "super" | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while" | "async" | "await" | "dyn" | "abstract" | "become" | "box" | "do"
            | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield" | "try" | "gen"
            // Names the generated module itself defines.
            | "culture" | "set_culture" | "register" | "set" | "get" | "names"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_names() {
        for ok in ["logo", "welcome_text", "okButton.Text", "_x", "A1"] {
            assert!(is_valid_name(ok), "{ok}");
        }
        for bad in ["", "1a", "a b", "a.", ".a", "a..b", "é", "a,b", "a}"] {
            assert!(!is_valid_name(bad), "{bad}");
        }
    }

    #[test]
    fn string_names_accept_web_keys() {
        for ok in ["header.settings", "drive-shared", "2fa_title", "files_one", "a key: with spaces", "é", "a..b."] {
            assert!(is_valid_string_name(ok), "{ok}");
        }
        assert!(!is_valid_string_name(""));
        assert_eq!(rust_name("2fa_title"), "_2fa_title");
        assert_eq!(rust_name("drive-shared"), "drive_shared");
        assert_eq!(rust_name("a key: with spaces"), "a_key_with_spaces");
    }

    #[test]
    fn generates_snake_case_names() {
        assert_eq!(rust_name("welcome_text"), "welcome_text");
        assert_eq!(rust_name("WelcomeText"), "welcome_text");
        assert_eq!(rust_name("okButton.Text"), "ok_button_text");
        assert_eq!(rust_name("HTTPServer2"), "http_server2");
        assert_eq!(rust_name("NavigationToolbarVisiblePath.PlaceholderText"), "navigation_toolbar_visible_path_placeholder_text");
        assert_eq!(rust_name("type"), "type_");
        assert_eq!(rust_name("Culture"), "culture_");
        assert_eq!(rust_name("_9"), "_9");
        assert_eq!(rust_name("Medium+"), "medium_plus");
        assert_eq!(rust_name("Medium++"), "medium_plus_plus");
        assert!(is_valid_name("Large+++"));
        assert_eq!(type_name("resources"), "Resources");
        assert_eq!(type_name("main_view"), "MainView");
        assert_eq!(type_name("app.icons"), "AppIcons");
    }
}
