//! Plurals and interpolation of string resources — i18next's semantics, so a `.kbres` string reads the same
//! on the desktop and on the web (where i18next itself resolves `{Res}`; `vskubuno/docs/WEB-VIEWS.md` §2.4,
//! WV-6).
//!
//! - **Plural forms** are ordinary `String` entries named `key_zero`, `key_one`, `key_two`, `key_few`,
//!   `key_many`, `key_other` ([`split_plural`], [`crate::ResourceFile::plural_forms`]).
//! - **Selection** ([`candidates`]): with a count, `key_zero` when the count is 0 (and that entry exists),
//!   else `key_<category>` where the category is the culture's CLDR cardinal category ([`category`]), else
//!   the plain `key`. Each candidate is looked up through the normal culture fallback chain.
//! - **Interpolation** ([`interpolate`]): `{{name}}` (spaces inside the braces tolerated, `{{name, format}}`
//!   gives the value, the format is ignored) is replaced by the argument named `name`, or whose name with
//!   its first letter lower-cased is `name` (`Count` fills `{{count}}`); an unknown placeholder stays as
//!   written.
//!
//! [`category`] is hand-written from the CLDR cardinal rules (the version Node's `Intl.PluralRules` ships)
//! for the product languages — en fr es pt it de el ru ar he hi zh ja — and checked against a table
//! generated by `Intl.PluralRules` (`tests/plural-fixture.json`). Another language gets `one` for 1,
//! else `other`.

/// A CLDR cardinal plural category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum PluralCategory {
    Zero,
    One,
    Two,
    Few,
    Many,
    Other,
}

impl PluralCategory {
    /// Every category, in CLDR order.
    pub const ALL: [PluralCategory; 6] = [PluralCategory::Zero, PluralCategory::One, PluralCategory::Two, PluralCategory::Few, PluralCategory::Many, PluralCategory::Other];

    /// The CLDR name (`one`), also the suffix of a plural form (`key_one`).
    pub fn as_str(self) -> &'static str {
        match self {
            PluralCategory::Zero => "zero",
            PluralCategory::One => "one",
            PluralCategory::Two => "two",
            PluralCategory::Few => "few",
            PluralCategory::Many => "many",
            PluralCategory::Other => "other",
        }
    }

    /// The category named `name` (`one`…).
    pub fn parse(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|c| c.as_str() == name)
    }
}

/// `(base key, category)` of a plural form's name (`items_one` → `("items", One)`); `None` for any other
/// name (the base must not be empty).
pub fn split_plural(name: &str) -> Option<(&str, PluralCategory)> {
    let (base, suffix) = name.rsplit_once('_')?;
    if base.is_empty() {
        return None;
    }
    Some((base, PluralCategory::parse(suffix)?))
}

/// The CLDR operands the product languages need: `n` (absolute value), `i` (integer digits), `v` (number of
/// visible fraction digits). The number is written in its shortest
/// decimal form (what JavaScript's `Intl.PluralRules.select(number)` sees: `1.50` is `1.5`).
struct Operands {
    n: f64,
    i: u64,
    v: usize,
}

impl Operands {
    fn of(value: f64) -> Self {
        let n = value.abs();
        let text = format!("{n}");
        let (int, frac) = match text.split_once('.') {
            Some((a, b)) => (a, b),
            None => (text.as_str(), ""),
        };
        Self { n, i: int.parse().unwrap_or(u64::MAX), v: frac.len() }
    }

    fn is_int(&self) -> bool {
        self.v == 0
    }

    /// `n` is the integer `k` (CLDR `n = k`).
    fn n_is(&self, k: u64) -> bool {
        self.is_int() && self.i == k
    }

    /// `n % m` is an integer within `lo..=hi` (CLDR `n % m = lo..hi`; a fraction never matches).
    fn n_mod_in(&self, m: u64, lo: u64, hi: u64) -> bool {
        self.is_int() && (lo..=hi).contains(&(self.i % m))
    }

    /// The compact-decimal "millions" rule of the Romance languages (`e = 0 and i != 0 and i % 1000000 = 0
    /// and v = 0`; `e` is always 0 for a plain number).
    fn millions(&self) -> bool {
        self.is_int() && self.i != 0 && self.i.is_multiple_of(1_000_000)
    }
}

/// The primary language subtag of a culture name, lower case (`pt-BR` → `pt`, `zh_Hans` → `zh`).
fn language(culture: &str) -> String {
    culture.trim().split(['-', '_']).next().unwrap_or_default().to_ascii_lowercase()
}

/// The CLDR cardinal category of `count` in `culture` (`fr-FR`, `ru`, `ar`…).
pub fn category(culture: &str, count: f64) -> PluralCategory {
    use PluralCategory::*;
    if !count.is_finite() {
        return Other;
    }
    let o = Operands::of(count);
    let canonical = crate::culture::canonical(culture);
    match language(culture).as_str() {
        "en" | "de" => {
            if o.i == 1 && o.v == 0 {
                One
            } else {
                Other
            }
        }
        "el" => {
            if o.n == 1.0 {
                One
            } else {
                Other
            }
        }
        "it" => {
            if o.i == 1 && o.v == 0 {
                One
            } else if o.millions() {
                Many
            } else {
                Other
            }
        }
        // European Portuguese has the Italian rule; `pt` (Brazilian) the French-like one.
        "pt" if canonical == "pt-PT" => {
            if o.i == 1 && o.v == 0 {
                One
            } else if o.millions() {
                Many
            } else {
                Other
            }
        }
        "fr" | "pt" => {
            if o.i <= 1 {
                One
            } else if o.millions() {
                Many
            } else {
                Other
            }
        }
        "es" => {
            if o.n == 1.0 {
                One
            } else if o.millions() {
                Many
            } else {
                Other
            }
        }
        "ru" => {
            if o.v != 0 {
                Other
            } else if o.i % 10 == 1 && o.i % 100 != 11 {
                One
            } else if (2..=4).contains(&(o.i % 10)) && !(12..=14).contains(&(o.i % 100)) {
                Few
            } else {
                Many
            }
        }
        "ar" => {
            if o.n_is(0) {
                Zero
            } else if o.n_is(1) {
                One
            } else if o.n_is(2) {
                Two
            } else if o.n_mod_in(100, 3, 10) {
                Few
            } else if o.n_mod_in(100, 11, 99) {
                Many
            } else {
                Other
            }
        }
        "he" => {
            if (o.i == 1 && o.v == 0) || (o.i == 0 && o.v != 0) {
                One
            } else if o.i == 2 && o.v == 0 {
                Two
            } else {
                Other
            }
        }
        "hi" => {
            if o.i == 0 || o.n == 1.0 {
                One
            } else {
                Other
            }
        }
        "zh" | "ja" => Other,
        _ => {
            if o.n == 1.0 {
                One
            } else {
                Other
            }
        }
    }
}

/// The categories `culture` uses, in CLDR order (`en` → one, other; `ar` → all six).
pub fn categories(culture: &str) -> &'static [PluralCategory] {
    use PluralCategory::*;
    match language(culture).as_str() {
        "en" | "de" | "el" | "hi" => &[One, Other],
        "fr" | "es" | "pt" | "it" => &[One, Many, Other],
        "ru" => &[One, Few, Many, Other],
        "ar" => &[Zero, One, Two, Few, Many, Other],
        "he" => &[One, Two, Other],
        "zh" | "ja" => &[Other],
        _ => &[One, Other],
    }
}

/// The names to try, in order, for `key` with `count` in `culture`: `key_zero` (count 0 only), then
/// `key_<category>`, then `key`. The caller keeps the first that exists (each looked up through the culture
/// fallback chain).
pub fn candidates(key: &str, culture: &str, count: f64) -> Vec<String> {
    let mut out = Vec::with_capacity(3);
    if count == 0.0 {
        out.push(format!("{key}_zero"));
    }
    let suffixed = format!("{key}_{}", category(culture, count).as_str());
    if !out.contains(&suffixed) {
        out.push(suffixed);
    }
    out.push(key.to_string());
    out
}

/// [`candidates`], keeping the first name `exists` accepts.
pub fn select(key: &str, culture: &str, count: f64, exists: impl Fn(&str) -> bool) -> Option<String> {
    candidates(key, culture, count).into_iter().find(|c| exists(c))
}

/// Whether an argument named `name` is the plural count (`Count`, case-insensitive).
pub fn is_count_argument(name: &str) -> bool {
    name.eq_ignore_ascii_case("count")
}

/// The number an argument's text holds, when it is one (`3`, `-1.5`, ` 2 `).
pub fn parse_count(text: &str) -> Option<f64> {
    text.trim().parse::<f64>().ok().filter(|n| n.is_finite())
}

/// Replaces every `{{name}}` of `template` (see the module doc) with `value(name)`; a placeholder `value`
/// does not know stays as written.
pub fn interpolate(template: &str, mut value: impl FnMut(&str) -> Option<String>) -> String {
    let mut out = String::with_capacity(template.len());
    let mut rest = template;
    while let Some(open) = rest.find("{{") {
        out.push_str(&rest[..open]);
        let after = &rest[open + 2..];
        let Some(close) = after.find("}}") else {
            out.push_str(&rest[open..]);
            return out;
        };
        let inside = &after[..close];
        let name = inside.split(',').next().unwrap_or_default().trim();
        match (!name.is_empty()).then(|| value(name)).flatten() {
            Some(v) => out.push_str(&v),
            None => out.push_str(&rest[open..open + 2 + close + 2]),
        }
        rest = &after[close + 2..];
    }
    out.push_str(rest);
    out
}

/// Whether the argument `arg` fills the placeholder `placeholder`: the same name, or the argument's name
/// with its first letter lower-cased (`Count` fills `{{count}}`).
pub fn argument_matches(arg: &str, placeholder: &str) -> bool {
    if arg == placeholder {
        return true;
    }
    let mut c = arg.chars();
    match c.next() {
        Some(first) => {
            let lowered: String = first.to_lowercase().chain(c).collect();
            lowered == placeholder
        }
        None => false,
    }
}

/// [`interpolate`] with named arguments (`(name, text)`), matched by [`argument_matches`] (an exact name
/// first).
pub fn interpolate_args(template: &str, args: &[(String, String)]) -> String {
    interpolate(template, |name| args.iter().find(|(n, _)| n == name).or_else(|| args.iter().find(|(n, _)| argument_matches(n, name))).map(|(_, v)| v.clone()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splits_plural_names() {
        assert_eq!(split_plural("items_one"), Some(("items", PluralCategory::One)));
        assert_eq!(split_plural("drive.files_other"), Some(("drive.files", PluralCategory::Other)));
        assert_eq!(split_plural("a_b_few"), Some(("a_b", PluralCategory::Few)));
        assert_eq!(split_plural("_one"), None);
        assert_eq!(split_plural("items"), None);
        assert_eq!(split_plural("items_ones"), None);
    }

    #[test]
    fn selects_candidates_like_i18next() {
        assert_eq!(candidates("items", "en", 0.0), vec!["items_zero", "items_other", "items"]);
        assert_eq!(candidates("items", "en", 1.0), vec!["items_one", "items"]);
        assert_eq!(candidates("items", "ar", 0.0), vec!["items_zero", "items"]);
        assert_eq!(candidates("items", "ru", 3.0), vec!["items_few", "items"]);
        let have = ["items_one", "items_other"];
        assert_eq!(select("items", "en", 0.0, |k| have.contains(&k)).as_deref(), Some("items_other"));
        assert_eq!(select("items", "fr", 0.0, |k| have.contains(&k)).as_deref(), Some("items_one"));
        assert_eq!(select("items", "ru", 5.0, |k| have.contains(&k)), None);
        assert_eq!(category("xx", 1.0), PluralCategory::One);
        assert_eq!(category("xx", 2.0), PluralCategory::Other);
        assert_eq!(category("pt-PT", 0.0), PluralCategory::Other);
        assert_eq!(category("pt-BR", 0.0), PluralCategory::One);
    }

    #[test]
    fn interpolates_named_arguments() {
        let args = vec![("Count".to_string(), "3".to_string()), ("name".to_string(), "Ana".to_string())];
        assert_eq!(interpolate_args("{{count}} files for {{ name }}", &args), "3 files for Ana");
        assert_eq!(interpolate_args("{{count, number}} / {{missing}} / {{}} / {{x", &args), "3 / {{missing}} / {{}} / {{x");
        assert_eq!(interpolate_args("no placeholder", &args), "no placeholder");
        assert_eq!(interpolate_args("{{Count}}", &args), "3");
        assert!(argument_matches("UserName", "userName") && !argument_matches("userName", "UserName"));
        assert!(is_count_argument("COUNT") && parse_count(" 2.5 ") == Some(2.5) && parse_count("x").is_none());
    }
}
