//! The one error type of the crate. Its messages never contain a connection string, a password or a
//! secret's value: a secret is named by its key, a connection by its component name.

use std::fmt;

/// What went wrong in a data operation.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum DataError {
    /// A component is not configured correctly (a missing `Connection`, an unknown provider…).
    #[error("configuration error: {0}")]
    Config(String),
    /// A secret (a connection string, a password placeholder) could not be resolved, or a connection
    /// string carries a credential in clear. The payload is the key or the reason, never the value.
    #[error("secret error: {0}")]
    Secret(String),
    /// An input was refused before any database call (a malformed identifier, a missing parameter,
    /// a filter that does not parse, a row that does not validate).
    #[error("validation failed: {0}")]
    Validation(String),
    /// The database (or the driver) reported an error.
    #[error("database error: {message}")]
    Database {
        /// The driver's message, without the connection string.
        message: String,
        /// The SQLSTATE / provider code, when there is one.
        code: Option<String>,
    },
    /// An `UPDATE` or `DELETE` generated by an adapter did not affect exactly one row: the row was
    /// changed or deleted by someone else since it was read (ADO.NET `DBConcurrencyException`).
    #[error("concurrency violation: {0}")]
    Concurrency(String),
    /// The operation was cancelled (its task was aborted, or the data runtime is shutting down).
    #[error("the operation was cancelled")]
    Cancelled,
    /// The view that started the operation was closed before it completed.
    #[error("the view was closed")]
    Closed,
}

impl DataError {
    /// A [`DataError::Database`] from a driver error, with its code. Logged by [`log_db`].
    pub(crate) fn from_sqlx(e: &sqlx::Error) -> Self {
        match e {
            sqlx::Error::Database(db) => DataError::Database { message: db.message().to_string(), code: db.code().map(|c| c.to_string()) },
            // Parse errors of a connection URL may quote parts of it: never repeat them.
            sqlx::Error::Configuration(_) => DataError::Config("the connection string is not valid for this provider".to_string()),
            sqlx::Error::PoolTimedOut => DataError::Database { message: "timed out waiting for a connection from the pool".to_string(), code: None },
            sqlx::Error::PoolClosed => DataError::Database { message: "the connection pool is closed".to_string(), code: None },
            sqlx::Error::Io(io) => DataError::Database { message: format!("I/O error: {io}"), code: None },
            sqlx::Error::Tls(tls) => DataError::Database { message: format!("TLS error: {tls}"), code: None },
            sqlx::Error::RowNotFound => DataError::Database { message: "no row returned".to_string(), code: None },
            sqlx::Error::ColumnDecode { index, source } => DataError::Database { message: format!("cannot decode column {index}: {source}"), code: None },
            other => DataError::Database { message: other.to_string(), code: None },
        }
    }

    /// Whether retrying the same operation may succeed (the network, the pool, a server starting or
    /// shedding load). Never true for a constraint violation or a syntax error.
    pub fn is_transient(&self) -> bool {
        match self {
            DataError::Database { code: Some(code), .. } => {
                // PostgreSQL: connection exceptions (08xxx), too many connections (53300),
                // cannot connect now (57P03), serialization failure / deadlock (40001, 40P01).
                code.starts_with("08") || matches!(code.as_str(), "53300" | "57P03" | "40001" | "40P01")
                    // SQLite: SQLITE_BUSY (5), SQLITE_LOCKED (6).
                    || matches!(code.as_str(), "5" | "6")
                    // MySQL: deadlock (1213), server gone / lost (2006, 2013); SQL Server: deadlock
                    // victim (1205), Azure throttling and failover (40501, 40613, 40197, 10928, 10929).
                    || matches!(code.as_str(), "1213" | "2006" | "2013" | "1205" | "40501" | "40613" | "40197" | "10928" | "10929")
            }
            DataError::Database { code: None, message } => message.starts_with("I/O error") || message.starts_with("timed out waiting"),
            _ => false,
        }
    }
}

/// Logs a driver error with its context (Kubuno rule: every DB error is logged before it is
/// returned) and converts it.
pub(crate) fn log_db(context: &str, e: sqlx::Error) -> DataError {
    let err = DataError::from_sqlx(&e);
    tracing::error!(target: "kubuno_desktop_data", context, error = %err, "database operation failed");
    err
}

/// Logs a non-driver error with its context and returns it.
pub(crate) fn logged(context: &str, err: DataError) -> DataError {
    tracing::error!(target: "kubuno_desktop_data", context, error = %err, "data operation failed");
    err
}

/// A short list of messages, for summaries (`"Name: required; Email: not valid"`).
pub(crate) struct Joined<'a>(pub &'a [(String, String)]);

impl fmt::Display for Joined<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for (i, (field, message)) in self.0.iter().enumerate() {
            if i > 0 {
                f.write_str("; ")?;
            }
            if field.is_empty() {
                f.write_str(message)?;
            } else {
                write!(f, "{field}: {message}")?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn transient_errors() {
        assert!(DataError::Database { message: "x".into(), code: Some("08006".into()) }.is_transient());
        assert!(DataError::Database { message: "I/O error: reset".into(), code: None }.is_transient());
        assert!(!DataError::Database { message: "duplicate".into(), code: Some("23505".into()) }.is_transient());
        assert!(!DataError::Validation("x".into()).is_transient());
    }

    #[test]
    fn configuration_errors_do_not_repeat_the_url() {
        let e = sqlx::Error::Configuration("invalid port in postgres://u:secret@h:x/db".into());
        let msg = DataError::from_sqlx(&e).to_string();
        assert!(!msg.contains("secret"), "{msg}");
    }

    #[test]
    fn joined_messages() {
        let v = vec![("Name".to_string(), "required".to_string()), (String::new(), "row".to_string())];
        assert_eq!(Joined(&v).to_string(), "Name: required; row");
    }
}
