//! [`Table`]: rows read from a database with their change tracking (ADO.NET `DataTable`; named
//! `Table` because `DataTable` is the grid control's element name). Each [`DataRow`] keeps its
//! current values, its original values (from the last fill or save), a [`RowState`], and the errors
//! set on it (`SetColumnError`). Deleted rows stay in the table, hidden from binding sources, until
//! the changes are accepted.

use std::collections::BTreeMap;

use crate::value::{DbType, DbValue};

/// A column of a [`Table`].
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DataColumn {
    pub name: String,
    pub ty: DbType,
    pub nullable: bool,
    /// The maximum number of characters, for a text column that declares one.
    pub max_length: Option<usize>,
    /// Computed or joined: never written by an update.
    pub read_only: bool,
    /// Generated by the database (a serial / identity / `INTEGER PRIMARY KEY`).
    pub auto_increment: bool,
    pub primary_key: bool,
}

impl DataColumn {
    pub fn new(name: impl Into<String>, ty: DbType) -> Self {
        Self { name: name.into(), ty, nullable: true, ..Default::default() }
    }
}

/// The state of a row (ADO.NET `DataRowState`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub enum RowState {
    /// Created but not yet in the table's changes (a row being added in a binding source).
    Detached,
    #[default]
    Unchanged,
    Added,
    Modified,
    Deleted,
}

/// One row of a [`Table`].
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DataRow {
    /// Stable within the table (survives sorting, filtering and saving).
    pub id: u64,
    pub values: Vec<DbValue>,
    /// The values as last read or saved (`None` for a row that was never in the database).
    pub original: Option<Vec<DbValue>>,
    pub state: RowState,
    /// Column index → message.
    pub column_errors: BTreeMap<usize, String>,
    /// An error of the whole row.
    pub row_error: Option<String>,
}

impl DataRow {
    pub fn has_errors(&self) -> bool {
        !self.column_errors.is_empty() || self.row_error.is_some()
    }
}

/// A table of rows (see the module doc).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Table {
    pub name: String,
    pub columns: Vec<DataColumn>,
    rows: Vec<DataRow>,
    next_id: u64,
}

impl Table {
    pub fn new(name: impl Into<String>, columns: Vec<DataColumn>) -> Self {
        Self { name: name.into(), columns, rows: Vec::new(), next_id: 1 }
    }

    /// The index of the column named `name` (case-insensitive).
    pub fn column_index(&self, name: &str) -> Option<usize> {
        self.columns.iter().position(|c| c.name == name).or_else(|| self.columns.iter().position(|c| c.name.eq_ignore_ascii_case(name)))
    }

    /// The primary key's column indices.
    pub fn key_columns(&self) -> Vec<usize> {
        self.columns.iter().enumerate().filter(|(_, c)| c.primary_key).map(|(i, _)| i).collect()
    }

    /// Every row, deleted ones included.
    pub fn rows(&self) -> &[DataRow] {
        &self.rows
    }

    pub fn row_by_id(&self, id: u64) -> Option<&DataRow> {
        self.rows.iter().find(|r| r.id == id)
    }

    pub fn row_by_id_mut(&mut self, id: u64) -> Option<&mut DataRow> {
        self.rows.iter_mut().find(|r| r.id == id)
    }

    fn take_id(&mut self) -> u64 {
        let id = self.next_id.max(1);
        self.next_id = id + 1;
        id
    }

    /// Appends a row read from the database (`Unchanged`, its values are its original values).
    pub fn load_row(&mut self, values: Vec<DbValue>) -> u64 {
        let id = self.take_id();
        self.rows.push(DataRow { id, original: Some(values.clone()), values, state: RowState::Unchanged, ..Default::default() });
        id
    }

    /// Appends a new row (`Added`), padded or truncated to the columns.
    pub fn add_row(&mut self, mut values: Vec<DbValue>) -> u64 {
        values.resize(self.columns.len(), DbValue::Null);
        let id = self.take_id();
        self.rows.push(DataRow { id, values, original: None, state: RowState::Added, ..Default::default() });
        id
    }

    /// Appends a detached row (a row being added in a binding source, not yet a change).
    pub(crate) fn add_detached(&mut self) -> u64 {
        let id = self.take_id();
        self.rows.push(DataRow { id, values: vec![DbValue::Null; self.columns.len()], original: None, state: RowState::Detached, ..Default::default() });
        id
    }

    /// Removes a row physically (a detached or added row that is abandoned).
    pub(crate) fn remove_row(&mut self, id: u64) {
        self.rows.retain(|r| r.id != id);
    }

    /// Deletes a row: an added row disappears, any other becomes `Deleted` (kept until accepted).
    pub fn delete_row(&mut self, id: u64) {
        match self.row_by_id(id).map(|r| r.state) {
            Some(RowState::Added | RowState::Detached) => self.remove_row(id),
            Some(_) => {
                if let Some(r) = self.row_by_id_mut(id) {
                    r.state = RowState::Deleted;
                }
            }
            None => {}
        }
    }

    /// Whether any row is added, modified or deleted.
    pub fn has_changes(&self) -> bool {
        self.rows.iter().any(|r| matches!(r.state, RowState::Added | RowState::Modified | RowState::Deleted))
    }

    /// The changed rows, in table order.
    pub fn changes(&self) -> impl Iterator<Item = &DataRow> {
        self.rows.iter().filter(|r| matches!(r.state, RowState::Added | RowState::Modified | RowState::Deleted))
    }

    /// Accepts every change: deleted rows go, the others become `Unchanged` with their current
    /// values as original values.
    pub fn accept_changes(&mut self) {
        self.rows.retain(|r| r.state != RowState::Deleted);
        for r in &mut self.rows {
            if matches!(r.state, RowState::Added | RowState::Modified) {
                r.state = RowState::Unchanged;
                r.original = Some(r.values.clone());
            }
        }
    }

    /// Rejects every change: added rows go, the others get their original values back.
    pub fn reject_changes(&mut self) {
        self.rows.retain(|r| !matches!(r.state, RowState::Added | RowState::Detached));
        for r in &mut self.rows {
            if let Some(o) = &r.original {
                r.values = o.clone();
            }
            r.state = RowState::Unchanged;
            r.column_errors.clear();
            r.row_error = None;
        }
    }

    /// Replaces, in column `c` of every row (current and original values), the temporary keys of
    /// `map` by the keys the database gave (a master saved with its details, DATA-3).
    pub(crate) fn remap_column(&mut self, c: usize, map: &[(DbValue, DbValue)]) {
        for r in &mut self.rows {
            if let Some(v) = r.values.get_mut(c) {
                if let Some((_, real)) = map.iter().find(|(t, _)| t == v) {
                    *v = real.clone();
                }
            }
            if let Some(v) = r.original.as_mut().and_then(|o| o.get_mut(c)) {
                if let Some((_, real)) = map.iter().find(|(t, _)| t == v) {
                    *v = real.clone();
                }
            }
        }
    }

    /// The value of `column` in row `id`.
    pub fn value(&self, id: u64, column: &str) -> Option<&DbValue> {
        let c = self.column_index(column)?;
        self.row_by_id(id).and_then(|r| r.values.get(c))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::DbKind;

    fn table() -> Table {
        let mut id = DataColumn::new("id", DbType::new(DbKind::Int, "INTEGER"));
        id.primary_key = true;
        let mut t = Table::new("t", vec![id, DataColumn::new("name", DbType::new(DbKind::Text, "TEXT"))]);
        t.load_row(vec![DbValue::Int(1), "a".into()]);
        t.load_row(vec![DbValue::Int(2), "b".into()]);
        t
    }

    #[test]
    fn states_accept_and_reject() {
        let mut t = table();
        assert!(!t.has_changes());
        let first = t.rows()[0].id;
        t.row_by_id_mut(first).expect("row").values[1] = "A".into();
        t.row_by_id_mut(first).expect("row").state = RowState::Modified;
        let second = t.rows()[1].id;
        t.delete_row(second);
        let added = t.add_row(vec![DbValue::Null, "c".into()]);
        assert_eq!(t.changes().count(), 3);
        let mut rejected = t.clone();
        rejected.reject_changes();
        assert_eq!(rejected.rows().len(), 2);
        assert_eq!(rejected.value(first, "NAME"), Some(&DbValue::Text("a".into())));
        t.accept_changes();
        assert_eq!(t.rows().len(), 2);
        assert!(t.row_by_id(second).is_none());
        assert_eq!(t.row_by_id(added).map(|r| r.state), Some(RowState::Unchanged));
        assert_eq!(t.row_by_id(first).and_then(|r| r.original.clone()), Some(vec![DbValue::Int(1), "A".into()]));
        assert_eq!(t.key_columns(), vec![0]);
    }

    #[test]
    fn deleting_an_added_row_removes_it() {
        let mut t = table();
        let added = t.add_row(vec![]);
        assert_eq!(t.row_by_id(added).map(|r| r.values.len()), Some(2));
        t.delete_row(added);
        assert!(t.row_by_id(added).is_none());
        assert!(!t.has_changes());
    }
}
