//! The plural categories match a table generated by Node's `Intl.PluralRules` (what i18next uses on the web)
//! for the 13 product languages: `{lang: {categories, samples: {"n": category}}}`, n = 0…200, 1000, 1e6,
//! 2e6, 0.5, 1.5, 2.5.

use kubuno_desktop_resources_model::plural::{categories, category};

#[test]
fn plural_categories_match_intl_plural_rules() {
    let text = include_str!("plural-fixture.json");
    let fixture: serde_json::Value = serde_json::from_str(text).expect("fixture");
    let langs = fixture.as_object().expect("object");
    assert_eq!(langs.len(), 13);
    let mut mismatches = Vec::new();
    let mut checked = 0;
    for (lang, data) in langs {
        let cats: Vec<&str> = data["categories"].as_array().expect("categories").iter().filter_map(|c| c.as_str()).collect();
        let mut ours: Vec<&str> = categories(lang).iter().map(|c| c.as_str()).collect();
        let mut theirs = cats.clone();
        ours.sort_unstable();
        theirs.sort_unstable();
        if ours != theirs {
            mismatches.push(format!("{lang}: categories {ours:?} != {theirs:?}"));
        }
        for (n, expected) in data["samples"].as_object().expect("samples") {
            let value: f64 = n.parse().expect("number");
            let got = category(lang, value).as_str();
            checked += 1;
            if Some(got) != expected.as_str() {
                mismatches.push(format!("{lang} {n}: {got} != {expected}"));
            }
        }
    }
    assert!(checked > 13 * 200, "{checked}");
    assert!(mismatches.is_empty(), "{}", mismatches.join("\n"));
}
