//! Generated by `overrides::tests::write_overrides_rust_fixture`: one class per level overriding
//! every member of the catalogue exactly as `overrides::stub` writes it (compiled by the tests).

#![allow(dead_code)]

use crate::prelude::*;

#[derive(Component, Default)]
#[kubuno(extends = Button, overrides(Component, Control, ButtonBase))]
pub struct AllButton {
    base: Button,
}

impl Component for AllButton {
    fn dispose_core(&mut self, disposing: bool) {
        self.base_mut().dispose_core(disposing);
    }
}

impl Control for AllButton {
    fn on_paint(&mut self, e: &mut PaintEventCx<'_>) {
        self.base_mut().on_paint(e);
    }

    fn on_paint_background(&mut self, e: &mut PaintEventCx<'_>) {
        self.base_mut().on_paint_background(e);
    }

    fn on_print(&mut self, e: &mut PaintEventCx<'_>) {
        self.paint_layers(e);
    }

    fn on_resize(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_resize(e);
    }

    fn on_create_control(&mut self) {
        self.base_mut().on_create_control();
    }

    fn get_preferred_size(&self, canvas: &dyn Canvas, proposed: Size) -> Size {
        self.base().get_preferred_size(canvas, proposed)
    }

    fn set_bounds_core(&mut self, bounds: Rect, specified: BoundsSpecified) {
        self.base_mut().set_bounds_core(bounds, specified);
    }

    fn is_input_key(&self, key: Keys) -> bool {
        self.base().is_input_key(key)
    }

    fn is_input_char(&self, c: char) -> bool {
        self.base().is_input_char(c)
    }

    fn process_cmd_key(&mut self, msg: &mut Message, key: Keys) -> bool {
        self.base_mut().process_cmd_key(msg, key)
    }

    fn process_dialog_key(&mut self, key: Keys) -> bool {
        self.base_mut().process_dialog_key(key)
    }

    fn wnd_proc(&mut self, msg: &mut Message) -> bool {
        self.base_mut().wnd_proc(msg)
    }

    fn create_params(&self) -> CreateParams {
        self.base().create_params()
    }

    fn on_event(&mut self, event: &'static str, e: &mut EventCx<'_, dyn EventArgs>) {
        self.base_mut().on_event(event, e);
    }

    fn on_click(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_click(e);
    }

    fn on_double_click(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_double_click(e);
    }

    fn on_mouse_click(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_click(e);
    }

    fn on_mouse_double_click(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_double_click(e);
    }

    fn on_mouse_down(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_down(e);
    }

    fn on_mouse_up(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_up(e);
    }

    fn on_mouse_move(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_move(e);
    }

    fn on_mouse_enter(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_mouse_enter(e);
    }

    fn on_mouse_leave(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_mouse_leave(e);
    }

    fn on_mouse_hover(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_mouse_hover(e);
    }

    fn on_mouse_wheel(&mut self, e: &mut EventCx<'_, MouseEventArgs>) {
        self.base_mut().on_mouse_wheel(e);
    }

    fn on_key_down(&mut self, e: &mut EventCx<'_, KeyEventArgs>) {
        self.base_mut().on_key_down(e);
    }

    fn on_key_up(&mut self, e: &mut EventCx<'_, KeyEventArgs>) {
        self.base_mut().on_key_up(e);
    }

    fn on_key_press(&mut self, e: &mut EventCx<'_, KeyPressEventArgs>) {
        self.base_mut().on_key_press(e);
    }

    fn on_enter(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_enter(e);
    }

    fn on_leave(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_leave(e);
    }

    fn on_got_focus(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_got_focus(e);
    }

    fn on_lost_focus(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_lost_focus(e);
    }

    fn on_validating(&mut self, e: &mut EventCx<'_, CancelEventArgs>) {
        self.base_mut().on_validating(e);
    }

    fn on_validated(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_validated(e);
    }

    fn on_move(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_move(e);
    }

    fn on_size_changed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_size_changed(e);
    }

    fn on_location_changed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_location_changed(e);
    }

    fn on_layout(&mut self, e: &mut EventCx<'_, LayoutEventArgs>) {
        self.base_mut().on_layout(e);
    }

    fn on_visible_changed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_visible_changed(e);
    }

    fn on_enabled_changed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_enabled_changed(e);
    }

    fn on_text_changed(&mut self, e: &mut EventCx<'_, TextChangedEventArgs>) {
        self.base_mut().on_text_changed(e);
    }

    fn on_handle_created(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_handle_created(e);
    }

    fn on_handle_destroyed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_handle_destroyed(e);
    }

    fn on_drag_enter(&mut self, e: &mut EventCx<'_, DragEventArgs>) {
        self.base_mut().on_drag_enter(e);
    }

    fn on_drag_over(&mut self, e: &mut EventCx<'_, DragEventArgs>) {
        self.base_mut().on_drag_over(e);
    }

    fn on_drag_drop(&mut self, e: &mut EventCx<'_, DragEventArgs>) {
        self.base_mut().on_drag_drop(e);
    }

    fn on_drag_leave(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_drag_leave(e);
    }
}

impl ButtonBase for AllButton {
    fn on_checked_changed(&mut self, e: &mut EventCx<'_, CheckedChangedEventArgs>) {
        self.base_mut().on_checked_changed(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = TextField, overrides(TextBoxBase))]
pub struct AllText {
    base: TextField,
}

impl TextBoxBase for AllText {
    fn on_read_only_changed(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_read_only_changed(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = ListBox, overrides(ListControl))]
pub struct AllList {
    base: ListBox,
}

impl ListControl for AllList {
    fn on_selection_changed(&mut self, e: &mut EventCx<'_, SelectionChangedEventArgs>) {
        self.base_mut().on_selection_changed(e);
    }

    fn on_selected_value_changed(&mut self, e: &mut EventCx<'_, TextChangedEventArgs>) {
        self.base_mut().on_selected_value_changed(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = Slider, overrides(RangeBase))]
pub struct AllRange {
    base: Slider,
}

impl RangeBase for AllRange {
    fn on_value_changed(&mut self, e: &mut EventCx<'_, NumericValueChangedEventArgs>) {
        self.base_mut().on_value_changed(e);
    }

    fn on_scroll(&mut self, e: &mut EventCx<'_, ScrollEventArgs>) {
        self.base_mut().on_scroll(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = ScrollArea, overrides(ScrollableControl))]
pub struct AllScroll {
    base: ScrollArea,
}

impl ScrollableControl for AllScroll {
    fn on_scroll(&mut self, e: &mut EventCx<'_, ScrollEventArgs>) {
        self.base_mut().on_scroll(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = UserControl, overrides(UserControl))]
pub struct AllUser {
    base: UserControlCore,
}

impl UserControl for AllUser {
    fn on_load(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_load(e);
    }
}

#[derive(Component, Default)]
#[kubuno(extends = View, overrides(View))]
pub struct AllView {
    base: ViewCore,
}

impl View for AllView {
    fn on_load(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_load(e);
    }

    fn on_shown(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_shown(e);
    }

    fn on_activated(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_activated(e);
    }

    fn on_deactivate(&mut self, e: &mut EventCx<'_, EmptyEventArgs>) {
        self.base_mut().on_deactivate(e);
    }

    fn on_form_closing(&mut self, e: &mut EventCx<'_, FormClosingEventArgs>) {
        self.base_mut().on_form_closing(e);
    }

    fn on_form_closed(&mut self, e: &mut EventCx<'_, FormClosedEventArgs>) {
        self.base_mut().on_form_closed(e);
    }
}
