//! TypeScript generators: the view's declarations (`X.kbview.d.ts`: `plan`, the abstract `ViewBase` with a
//! typed handle per `x:Name` and an abstract method per handler), its check file (`X.kbview.check.ts`:
//! every binding written as a TS expression against the code-behind type, with a map back to the
//! `.kbview`), and the handle interfaces of the host elements (`@kubuno/views`).
//!
//! The same text is produced by the Vite plugin, `kbview-tsc` (both through WASM) and, later, the language
//! server's web profile (WEB-VIEWS §5: one generator, shared Rust).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use kubuno_desktop_views_model::PropKindEntry;
use serde::Serialize;

use crate::compile::{BindingCheck, CompileOptions, Facts, HandlerUse};

use crate::registry::WebRegistry;

pub const GENERATED_BY: &str = "Generated by @kubuno/views-compiler";

/// One mapped span of the check file: generated `line`, columns `[start, end)` (1-based UTF-16), and the
/// `.kbview` range it stands for. `exact`: the generated text from `start` is the source text from `src`
/// character for character (a binding path), so an error column inside it maps one to one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CheckSpan {
    pub line: u32,
    pub start: u32,
    pub end: u32,
    pub src: [u32; 2],
    pub src_end: [u32; 2],
    pub exact: bool,
    /// What the span checks, for messages (`binding`, `handler`, `props`).
    pub what: &'static str,
}

fn stem(file: &str) -> &str {
    let name = file.rsplit('/').next().unwrap_or(file);
    name.split('.').next().unwrap_or(name)
}

/// The class name the code-behind is expected to export.
pub fn class_name(opts: &CompileOptions) -> String {
    opts.class_name.clone().unwrap_or_else(|| stem(&opts.file).to_string())
}

fn sorted_handlers(handlers: &[HandlerUse]) -> BTreeMap<String, (BTreeSet<String>, BTreeSet<String>)> {
    let mut out: BTreeMap<String, (BTreeSet<String>, BTreeSet<String>)> = BTreeMap::new();
    for h in handlers {
        let e = out.entry(h.name.clone()).or_default();
        e.0.insert(h.sender.clone());
        e.1.insert(h.args.clone());
    }
    out
}

/// `X.kbview.d.ts`.
pub(crate) fn dts(opts: &CompileOptions, facts: &Facts) -> String {
    let mut types: BTreeSet<String> = BTreeSet::new();
    types.insert("View".into());
    types.insert("ViewPlan".into());
    for n in &facts.names {
        types.insert(n.handle.clone());
    }
    let handlers = sorted_handlers(&facts.handlers);
    for (senders, args) in handlers.values() {
        types.extend(senders.iter().cloned());
        types.extend(args.iter().cloned());
    }
    let mut out = String::new();
    let _ = writeln!(out, "// {GENERATED_BY} from {} — do not edit (rebuilt on every change; never committed).", opts.file);
    let imports: Vec<String> = types.iter().map(|t| format!("{t} as __{t}")).collect();
    let _ = writeln!(out, "import type {{ {} }} from '@kubuno/views'", imports.join(", "));
    let props = match (&facts.props_type, &opts.code_behind) {
        (Some((t, _, _)), Some(cb)) => {
            let _ = writeln!(out, "import type {{ {t} as __Props }} from '{cb}'");
            "__Props"
        }
        _ => "{}",
    };
    out.push('\n');
    let _ = writeln!(out, "/** The render plan of `{}`. */", opts.file);
    out.push_str("export declare const plan: __ViewPlan\n\n");
    let _ = writeln!(out, "/** The generated base of the code-behind of `{}`: one handle per `x:Name`, one abstract method per handler. */", opts.file);
    let abstract_kw = if handlers.is_empty() { "" } else { "abstract " };
    let _ = writeln!(out, "export declare {abstract_kw}class ViewBase extends __View<{props}> {{");
    for n in &facts.names {
        let _ = writeln!(out, "  /** `<{} x:Name=\"{}\">` (line {}) */", n.element, n.name, n.at[0]);
        let _ = writeln!(out, "  readonly {}: __{}", n.name, n.handle);
    }
    for (name, (senders, args)) in &handlers {
        let sender = senders.iter().map(|s| format!("__{s}")).collect::<Vec<_>>().join(" | ");
        let args = args.iter().map(|a| format!("__{a}")).collect::<Vec<_>>().join(" | ");
        let uses: Vec<String> = facts.handlers.iter().filter(|h| &h.name == name).map(|h| format!("`{}.{}` (line {})", h.element, h.event, h.at[0])).collect();
        let _ = writeln!(out, "  /** Handles {}. */", uses.join(", "));
        let _ = writeln!(out, "  abstract {name}(sender: {sender}, e: {args}): void | Promise<void>");
    }
    out.push_str("}\n");
    if opts.code_behind.is_none() {
        out.push_str("\n/** The view as a React component (it has no code-behind). */\n");
        out.push_str("declare const component: import('react').ComponentType<{}>\nexport default component\n");
    }
    out
}

/// Writes check lines and records their spans.
struct CheckWriter {
    text: String,
    line: u32,
    spans: Vec<CheckSpan>,
}

impl CheckWriter {
    fn push_line(&mut self, s: &str) {
        self.text.push_str(s);
        self.text.push('\n');
        self.line += 1;
    }

    /// Writes `prefix` + `expr` + `suffix` as one line and maps it. `exact_from` = UTF-16 offset in the
    /// line where the source path text starts.
    fn mapped(&mut self, line: &str, what: &'static str, exact_from: Option<u32>, c: &BindingCheck) {
        let gen_line = self.line + 1;
        let units = line.encode_utf16().count() as u32;
        match (exact_from, c.path_at) {
            (Some(from), Some((s, e))) => {
                // Before the path: the whole attribute.
                self.spans.push(CheckSpan { line: gen_line, start: 1, end: from + 1, src: [c.attr_at.0.line, c.attr_at.0.column], src_end: [c.attr_at.1.line, c.attr_at.1.column], exact: false, what });
                let len = c.path.encode_utf16().count() as u32;
                self.spans.push(CheckSpan { line: gen_line, start: from + 1, end: from + 1 + len, src: [s.line, s.column], src_end: [e.line, e.column], exact: true, what });
                self.spans.push(CheckSpan { line: gen_line, start: from + 1 + len, end: units + 2, src: [c.attr_at.0.line, c.attr_at.0.column], src_end: [c.attr_at.1.line, c.attr_at.1.column], exact: false, what });
            }
            _ => {
                self.spans.push(CheckSpan { line: gen_line, start: 1, end: units + 2, src: [c.attr_at.0.line, c.attr_at.0.column], src_end: [c.attr_at.1.line, c.attr_at.1.column], exact: false, what });
            }
        }
        self.push_line(line);
    }
}

fn scope_expr(rows: &[String]) -> String {
    let mut expr = "vm".to_string();
    for r in rows {
        expr = format!("__r({r}, {expr})");
    }
    expr
}

/// `X.kbview.check.ts` and its span map.
pub(crate) fn check(opts: &CompileOptions, facts: &Facts) -> (String, Vec<CheckSpan>) {
    let mut w = CheckWriter { text: String::new(), line: 0, spans: Vec::new() };
    let file_name = opts.file.rsplit('/').next().unwrap_or(&opts.file).to_string();
    w.push_line(&format!("// {GENERATED_BY} from {} — do not edit. Type-checks the view's bindings against its code-behind;", opts.file));
    w.push_line("// kbview-tsc maps every error back to the .kbview (see the .check.json next to this file).");
    w.push_line("/* eslint-disable */");
    match &opts.code_behind {
        Some(cb) => {
            let class = class_name(opts);
            let line = format!("import type {{ {class} as __V }} from '{cb}'");
            let c = BindingCheck { path: String::new(), path_at: None, attr_at: facts.root_at, check: "any", reads: false, writes: false, rows: Vec::new() };
            w.mapped(&line, "class", None, &c);
        }
        None => w.push_line(&format!("import type {{ ViewBase as __V }} from './{file_name}'")),
    }
    w.push_line("type __IsAny<T> = 0 extends 1 & T ? true : false");
    w.push_line("type __DC<T> = T extends { dataContext: infer D } ? (__IsAny<D> extends true ? any : unknown extends D ? {} : D) : {}");
    w.push_line("declare const vm: __V & __DC<__V>");
    w.push_line("declare const __w: never");
    w.push_line("declare function __bool(v: boolean | null | undefined): void");
    w.push_line("declare function __num(v: number | null | undefined): void");
    w.push_line("declare function __str(v: string | number | bigint | boolean | null | undefined): void");
    w.push_line("declare function __arr(v: readonly unknown[] | null | undefined): void");
    w.push_line("declare function __any(v: unknown): void");
    w.push_line("declare function __fn(v: (...args: never[]) => unknown): void");
    w.push_line("declare function __elem<T>(v: readonly T[] | null | undefined): T");
    w.push_line("declare function __r<R, V>(row: R, outer: V): R & V");
    for row in &facts.rows {
        match &row.items {
            Some(items) => {
                let scope = scope_expr(&items.rows);
                let prefix = format!("const {} = __elem({scope}.", row.var);
                let line = format!("{prefix}{})", items.path);
                let from = prefix.encode_utf16().count() as u32;
                w.mapped(&line, "binding", Some(from), items);
            }
            None => w.push_line(&format!("const {}: any = undefined", row.var)),
        }
    }
    for c in &facts.checks {
        let scope = scope_expr(&c.rows);
        if c.reads {
            let prefix = format!("__{}({scope}.", c.check);
            let line = format!("{prefix}{})", c.path);
            w.mapped(&line, "binding", Some(prefix.encode_utf16().count() as u32), c);
        }
        if c.writes {
            let prefix = format!("{scope}.");
            let line = format!("{prefix}{} = __w", c.path);
            w.mapped(&line, "binding", Some(prefix.encode_utf16().count() as u32), c);
        }
    }
    let rows: Vec<&str> = facts.rows.iter().map(|r| r.var.as_str()).collect();
    let mut used = vec!["vm", "__w", "__bool", "__num", "__str", "__arr", "__any", "__fn", "__elem", "__r"];
    used.extend(rows);
    w.push_line(&format!("void [{}]", used.join(", ")));
    w.push_line("export {}");
    (w.text, w.spans)
}

fn camel(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(f) => f.to_lowercase().chain(c).collect(),
        None => String::new(),
    }
}

fn ts_string(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".into()).replace('\'', "\\'")
}

/// The handle interfaces of every element of `reg` (`@kubuno/views`' `handles.generated.ts`): one
/// `interface <Element> extends ElementHandle` with a camelCase member per property the code may read or
/// set (attached, design-time and root-only properties excluded).
pub fn handle_types(reg: &WebRegistry) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// {GENERATED_BY} (handle_types) from kbview-registry.web.json — do not edit; `npm run build:views-handles`.");
    out.push_str("/* eslint-disable */\nimport type { ElementHandle } from './view'\n\n");
    // Elements rendered by `@kubuno/views` itself (`Repeater`, `Timer`…) declare their handle next to their
    // component (a value and a type of the same name must live in one module).
    let mut elements: Vec<_> = reg.elements().filter(|e| e.web.module.as_deref() != Some("@kubuno/views")).collect();
    elements.sort_by(|a, b| a.entry.name.cmp(&b.entry.name));
    for el in &elements {
        let doc = el.entry.doc.lines().next().unwrap_or_default().replace("*/", "* /");
        let _ = writeln!(out, "/** `<{}>` — {} */", el.entry.name, doc);
        let _ = writeln!(out, "export interface {} extends ElementHandle {{", el.entry.name);
        let mut seen = BTreeSet::new();
        for p in &el.entry.properties {
            if p.name.contains('.') || p.design_time || p.root_only || !el.web.prop_map.contains_key(&p.name) {
                continue;
            }
            let member = camel(&p.name);
            if !seen.insert(member.clone()) || crate::compile::RESERVED_MEMBERS.contains(&member.as_str()) || matches!(member.as_str(), "focus" | "click" | "element" | "id") {
                continue;
            }
            let ty = match &p.kind {
                PropKindEntry::Bool => "boolean".to_string(),
                PropKindEntry::F32 => "number".to_string(),
                PropKindEntry::String => if el.web.prop_map.get(&p.name).and_then(|t| t.convert.as_deref()) == Some("items-source") { "readonly unknown[]".to_string() } else { "string".to_string() },
                PropKindEntry::Enum(values) if !values.is_empty() => values.iter().map(|v| ts_string(v)).collect::<Vec<_>>().join(" | "),
                PropKindEntry::Enum(_) => "string".to_string(),
            };
            let pdoc = p.doc.lines().next().unwrap_or_default().replace("*/", "* /");
            if !pdoc.is_empty() {
                let _ = writeln!(out, "  /** {pdoc} */");
            }
            let _ = writeln!(out, "  {member}: {ty}");
        }
        out.push_str("}\n\n");
    }
    let mut names: Vec<&str> = elements.iter().map(|e| e.entry.name.as_str()).collect();
    names.sort_unstable();
    out.push_str("/** Element name → handle type. */\nexport interface ElementHandles {\n");
    for n in names {
        let _ = writeln!(out, "  {n}: {n}");
    }
    out.push_str("}\n");
    out
}
