//! Typed rows (`vskubuno/docs/DATA.md`, DATA-4): the runtime side of [`crate::data_source!`].
//!
//! - [`TypedRow`]: implemented by the row structs `data_source!` generates, so typed rows and the
//!   dynamic components share one runtime — a [`Table`] (and a [`BindingSource`], its change
//!   tracking and its bindings) can be loaded from typed rows and read back as typed rows
//!   ([`Table::from_typed`], [`Table::to_typed`], [`BindingSource::load_typed`],
//!   [`BindingSource::to_typed`], [`BindingSource::typed_changes`]…).
//! - [`FieldValue`]: the conversion of one field type to and from a [`DbValue`].
//! - The typed pools of a [`ConnectionHandle`] (`sqlite_pool`, `pg_pool`, `mysql_pool`) and the
//!   `run_*` helpers that run typed `sqlx` code on the data runtime and return a [`DataTask`] the UI
//!   awaits without blocking — what the generated `*_task` functions call.

use std::future::Future;

use crate::binding_source::BindingSource;
use crate::connection::ConnectionHandle;
use crate::error::{logged, DataError};
use crate::rt::{self, DataTask};
use crate::table::{DataColumn, RowState, Table};
use crate::value::{DbType, DbValue};

/// A typed row: a struct with one field per column (generated by [`crate::data_source!`]).
pub trait TypedRow: Sized {
    /// The table, view or query the rows come from.
    fn table_name() -> &'static str;
    /// The columns, in field order (name, type, nullability, key, generated…).
    fn columns() -> Vec<DataColumn>;
    /// The field values, in column order.
    fn to_values(&self) -> Vec<DbValue>;
    /// A row from values in column order.
    fn from_values(values: &[DbValue]) -> Result<Self, DataError>;
}

/// A field type of a typed row, converted to and from a [`DbValue`] (dates, times, UUIDs and JSON
/// travel as their canonical text, like everywhere in `kubuno-data`).
pub trait FieldValue: Sized {
    fn to_db(&self) -> DbValue;
    /// `Err(reason)` when `value` cannot be this type (a `NULL` for a non-optional field…).
    fn from_db(value: &DbValue) -> Result<Self, String>;
}

fn null_error() -> String {
    "the value is NULL".to_string()
}

fn int_of(value: &DbValue) -> Result<i128, String> {
    match value {
        DbValue::Int(i) => Ok(i128::from(*i)),
        DbValue::Bool(b) => Ok(i128::from(*b)),
        DbValue::Float(f) if f.fract() == 0.0 && f.is_finite() => Ok(*f as i128),
        DbValue::Text(s) => s.trim().parse::<i128>().map_err(|_| format!("`{s}` is not an integer")),
        DbValue::Null => Err(null_error()),
        other => Err(format!("{} is not an integer", kind_name(other))),
    }
}

fn kind_name(value: &DbValue) -> &'static str {
    match value {
        DbValue::Null => "NULL",
        DbValue::Bool(_) => "a boolean",
        DbValue::Int(_) => "an integer",
        DbValue::Float(_) => "a number",
        DbValue::Text(_) => "a text",
        DbValue::Bytes(_) => "bytes",
    }
}

macro_rules! int_field {
    ($($t:ty),*) => {$(
        impl FieldValue for $t {
            fn to_db(&self) -> DbValue {
                match i64::try_from(*self) {
                    Ok(i) => DbValue::Int(i),
                    // u64 above i64::MAX: exact text.
                    Err(_) => DbValue::Text(self.to_string()),
                }
            }
            fn from_db(value: &DbValue) -> Result<Self, String> {
                let i = int_of(value)?;
                <$t>::try_from(i).map_err(|_| format!("{i} is out of range for {}", stringify!($t)))
            }
        }
    )*};
}

int_field!(i8, i16, i32, i64, u8, u16, u32, u64);

macro_rules! float_field {
    ($($t:ty),*) => {$(
        impl FieldValue for $t {
            fn to_db(&self) -> DbValue {
                DbValue::Float(f64::from(*self))
            }
            fn from_db(value: &DbValue) -> Result<Self, String> {
                match value {
                    DbValue::Null => Err(null_error()),
                    // f64 → f32 narrows like sqlx does when it decodes a REAL into an f32.
                    v => v.as_f64().map(|f| f as $t).ok_or_else(|| format!("{} is not a number", kind_name(v))),
                }
            }
        }
    )*};
}

float_field!(f32, f64);

impl FieldValue for bool {
    fn to_db(&self) -> DbValue {
        DbValue::Bool(*self)
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        match value {
            DbValue::Bool(b) => Ok(*b),
            DbValue::Int(i) => Ok(*i != 0),
            DbValue::Text(s) => match s.trim().to_ascii_lowercase().as_str() {
                "true" | "t" | "1" | "yes" => Ok(true),
                "false" | "f" | "0" | "no" => Ok(false),
                _ => Err(format!("`{s}` is not a boolean")),
            },
            DbValue::Null => Err(null_error()),
            other => Err(format!("{} is not a boolean", kind_name(other))),
        }
    }
}

impl FieldValue for String {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.clone())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        match value {
            DbValue::Null => Err(null_error()),
            DbValue::Bytes(b) => String::from_utf8(b.clone()).map_err(|_| "the bytes are not UTF-8 text".to_string()),
            v => Ok(v.to_display()),
        }
    }
}

impl FieldValue for Vec<u8> {
    fn to_db(&self) -> DbValue {
        DbValue::Bytes(self.clone())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        match value {
            DbValue::Bytes(b) => Ok(b.clone()),
            DbValue::Text(s) => Ok(s.as_bytes().to_vec()),
            DbValue::Null => Err(null_error()),
            other => Err(format!("{} is not bytes", kind_name(other))),
        }
    }
}

impl<T: FieldValue> FieldValue for Option<T> {
    fn to_db(&self) -> DbValue {
        self.as_ref().map_or(DbValue::Null, FieldValue::to_db)
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        match value {
            DbValue::Null => Ok(None),
            v => T::from_db(v).map(Some),
        }
    }
}

fn text_of(value: &DbValue) -> Result<&str, String> {
    match value {
        DbValue::Text(s) => Ok(s.trim()),
        DbValue::Null => Err(null_error()),
        other => Err(format!("{} is not a text", kind_name(other))),
    }
}

impl FieldValue for chrono::NaiveDate {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.format("%Y-%m-%d").to_string())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        let s = text_of(value)?;
        let date = s.get(..10).unwrap_or(s);
        chrono::NaiveDate::parse_from_str(date, "%Y-%m-%d").map_err(|_| format!("`{s}` is not a date (YYYY-MM-DD)"))
    }
}

impl FieldValue for chrono::NaiveTime {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.format("%H:%M:%S%.f").to_string())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        let s = text_of(value)?;
        chrono::NaiveTime::parse_from_str(s, "%H:%M:%S%.f").or_else(|_| chrono::NaiveTime::parse_from_str(s, "%H:%M")).map_err(|_| format!("`{s}` is not a time (HH:MM:SS)"))
    }
}

impl FieldValue for chrono::NaiveDateTime {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.format("%Y-%m-%d %H:%M:%S%.f").to_string())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        let s = text_of(value)?;
        chrono::NaiveDateTime::parse_from_str(s, "%Y-%m-%d %H:%M:%S%.f")
            .or_else(|_| chrono::NaiveDateTime::parse_from_str(s, "%Y-%m-%dT%H:%M:%S%.f"))
            .or_else(|_| chrono::DateTime::parse_from_rfc3339(s).map(|d| d.naive_utc()))
            .map_err(|_| format!("`{s}` is not a date and time (YYYY-MM-DD HH:MM:SS)"))
    }
}

impl FieldValue for chrono::DateTime<chrono::Utc> {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.to_rfc3339())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        let s = text_of(value)?;
        chrono::DateTime::parse_from_rfc3339(s)
            .map(|d| d.with_timezone(&chrono::Utc))
            .or_else(|_| chrono::NaiveDateTime::from_db(value).map(|n| n.and_utc()))
            .map_err(|_| format!("`{s}` is not a timestamp (RFC 3339)"))
    }
}

impl FieldValue for uuid::Uuid {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.hyphenated().to_string())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        match value {
            DbValue::Bytes(b) => uuid::Uuid::from_slice(b).map_err(|_| "the bytes are not a UUID".to_string()),
            v => {
                let s = text_of(v)?;
                uuid::Uuid::parse_str(s).map_err(|_| format!("`{s}` is not a UUID"))
            }
        }
    }
}

impl FieldValue for serde_json::Value {
    fn to_db(&self) -> DbValue {
        DbValue::Text(self.to_string())
    }
    fn from_db(value: &DbValue) -> Result<Self, String> {
        let s = text_of(value)?;
        serde_json::from_str(s).map_err(|e| format!("not valid JSON: {e}"))
    }
}

/// Field `index` (column `column`) of `values` as `T` — what the generated `from_values` calls.
#[doc(hidden)]
pub fn field<T: FieldValue>(values: &[DbValue], index: usize, column: &str) -> Result<T, DataError> {
    let value = values.get(index).unwrap_or(&DbValue::Null);
    T::from_db(value).map_err(|reason| DataError::Validation(format!("column `{column}`: {reason}")))
}

/// A column of a typed row — what the generated `columns` calls. `provider` is the `.kbdata`
/// provider name (`sqlite`, `postgres`, `mysql`, `sqlserver`).
#[doc(hidden)]
#[allow(clippy::too_many_arguments)]
pub fn column(provider: &str, name: &str, db_type: &str, nullable: bool, primary_key: bool, auto_increment: bool, read_only: bool, max_length: u32) -> DataColumn {
    let ty = match provider {
        "sqlite" => DbType::sqlite(db_type),
        "mysql" => DbType::mysql(db_type),
        "sqlserver" => DbType::mssql(db_type),
        _ => DbType::postgres(db_type),
    };
    DataColumn {
        name: name.to_string(),
        ty,
        nullable,
        max_length: (max_length > 0).then_some(max_length as usize),
        read_only,
        auto_increment,
        primary_key,
    }
}

/// Logs a driver error of a generated typed function (Kubuno rule: every DB error is logged before
/// it is returned) and converts it.
#[doc(hidden)]
pub fn db_error(context: &str, e: sqlx::Error) -> DataError {
    crate::error::log_db(context, e)
}

/// The positions, in `table`, of the columns of `T` (by name, case-insensitive).
fn column_map<T: TypedRow>(table: &Table) -> Result<Vec<usize>, DataError> {
    T::columns()
        .iter()
        .map(|c| table.column_index(&c.name).ok_or_else(|| DataError::Validation(format!("the table `{}` has no column `{}` (row type of `{}`)", table.name, c.name, T::table_name()))))
        .collect()
}

fn typed_of<T: TypedRow>(map: &[usize], values: &[DbValue]) -> Result<T, DataError> {
    let ordered: Vec<DbValue> = map.iter().map(|&i| values.get(i).cloned().unwrap_or(DbValue::Null)).collect();
    T::from_values(&ordered)
}

impl Table {
    /// A table of `T`'s columns holding `rows` as unchanged rows (as if they had been filled).
    pub fn from_typed<T: TypedRow>(rows: &[T]) -> Table {
        let mut table = Table::new(T::table_name(), T::columns());
        for r in rows {
            table.load_row(r.to_values());
        }
        table
    }

    /// Appends `row` as a new (`Added`) row; its id.
    pub fn add_typed<T: TypedRow>(&mut self, row: &T) -> Result<u64, DataError> {
        let map = column_map::<T>(self)?;
        let mut values = vec![DbValue::Null; self.columns.len()];
        for (v, &i) in row.to_values().into_iter().zip(&map) {
            values[i] = v;
        }
        Ok(self.add_row(values))
    }

    /// The current values of the rows that are not deleted, as `T` (columns matched by name, so a
    /// table filled by a `TableAdapter` works too).
    pub fn to_typed<T: TypedRow>(&self) -> Result<Vec<T>, DataError> {
        let map = column_map::<T>(self)?;
        self.rows().iter().filter(|r| !matches!(r.state, RowState::Deleted | RowState::Detached)).map(|r| typed_of(&map, &r.values)).collect()
    }

    /// Row `id` as `T`.
    pub fn typed_row<T: TypedRow>(&self, id: u64) -> Result<Option<T>, DataError> {
        let map = column_map::<T>(self)?;
        self.row_by_id(id).map(|r| typed_of(&map, &r.values)).transpose()
    }

    /// The changed rows with their state: added and modified rows with their current values,
    /// deleted rows with their original values (what a save needs: `insert`, `update`, `delete`).
    pub fn typed_changes<T: TypedRow>(&self) -> Result<Vec<(RowState, T)>, DataError> {
        let map = column_map::<T>(self)?;
        self.changes()
            .map(|r| {
                let values = if r.state == RowState::Deleted { r.original.as_ref().unwrap_or(&r.values) } else { &r.values };
                typed_of(&map, values).map(|t| (r.state, t))
            })
            .collect()
    }
}

impl BindingSource {
    /// Loads typed rows (a fill): bindings, grids and the navigator show them, edits are tracked.
    pub fn load_typed<T: TypedRow>(&mut self, rows: &[T]) {
        self.load(Table::from_typed(rows));
    }

    /// The rows that are not deleted, as `T` (the table's order; edits committed by `end_edit`).
    pub fn to_typed<T: TypedRow>(&self) -> Result<Vec<T>, DataError> {
        self.table().to_typed()
    }

    /// The current row as `T` (`None` when there is none).
    pub fn current_typed<T: TypedRow>(&self) -> Result<Option<T>, DataError> {
        let position = self.position();
        match usize::try_from(position).ok().and_then(|p| self.row_id_at(p)) {
            Some(id) => self.table().typed_row(id),
            None => Ok(None),
        }
    }

    /// The pending changes as typed rows with their state (see [`Table::typed_changes`]).
    pub fn typed_changes<T: TypedRow>(&self) -> Result<Vec<(RowState, T)>, DataError> {
        self.table().typed_changes()
    }

    /// Appends `row` as a new row (`Added`) and shows it.
    pub fn add_typed<T: TypedRow>(&mut self, row: &T) -> Result<(), DataError> {
        self.table_mut().add_typed(row)?;
        self.reset_bindings();
        Ok(())
    }
}

// ── Typed pools of a connection ─────────────────────────────────────────────────────────────────

fn wrong_provider(handle: &ConnectionHandle, wanted: &str) -> DataError {
    logged("typed pool", DataError::Config(format!("the connection `{}` is a {} connection, not {wanted}", handle.name(), handle.provider().as_str())))
}

macro_rules! typed_pool {
    ($feature:literal, $pool:ident, $run:ident, $variant:ident, $ty:ty, $wanted:literal) => {
        #[cfg(feature = $feature)]
        impl ConnectionHandle {
            #[doc = concat!("The connection's `", stringify!($ty), "` (opened on first use, with the retry policy), for typed")]
            /// `sqlx` code — the functions `data_source!` generates take it. The task runs on the
            /// data runtime and can be awaited from any executor; the pool itself must be used from
            /// a Tokio context (the data runtime: [`Self::run_sqlite`] and co, or [`crate::block_on`]).
            pub fn $pool(&self) -> DataTask<$ty> {
                let me = self.clone();
                rt::spawn(async move {
                    match me.pool().await? {
                        crate::provider::Pool::$variant(p) => Ok(p),
                        #[allow(unreachable_patterns)]
                        _ => Err(wrong_provider(&me, $wanted)),
                    }
                })
            }

            /// Runs `f` with the connection's pool on the data runtime: the task the UI awaits
            /// (`Customer::fetch_all_task(&conn)` is `conn.run_…(|pool| async move {
            /// Customer::fetch_all(&pool).await })`).
            pub fn $run<T, F, Fut>(&self, f: F) -> DataTask<T>
            where
                T: Send + 'static,
                F: FnOnce($ty) -> Fut + Send + 'static,
                Fut: Future<Output = Result<T, DataError>> + Send + 'static,
            {
                let me = self.clone();
                rt::spawn(async move {
                    let pool = match me.pool().await? {
                        crate::provider::Pool::$variant(p) => p,
                        #[allow(unreachable_patterns)]
                        _ => return Err(wrong_provider(&me, $wanted)),
                    };
                    f(pool).await
                })
            }
        }
    };
}

typed_pool!("sqlite", sqlite_pool, run_sqlite, Sqlite, sqlx::SqlitePool, "a SQLite one");
typed_pool!("postgres", pg_pool, run_pg, Postgres, sqlx::PgPool, "a PostgreSQL one");
typed_pool!("mysql", mysql_pool, run_mysql, MySql, sqlx::MySqlPool, "a MySQL one");

/// Runs `sql` (`@name` parameters) through a [`crate::DbCommand`] and converts its rows to `T`:
/// the run-time checked path (SQL Server, which has no `sqlx` driver).
#[doc(hidden)]
pub fn query_rows<T: TypedRow + Send + 'static>(conn: &ConnectionHandle, sql: &str, params: Vec<(&str, DbValue)>) -> DataTask<Vec<T>> {
    let mut cmd = crate::command::DbCommand::with_text(sql);
    for (name, value) in params {
        cmd.param(name, value);
    }
    let task = cmd.query(conn);
    rt::spawn(async move {
        let table = task.await?;
        table.to_typed::<T>().map_err(|e| logged("typed rows", e))
    })
}

/// Runs `sql` (`@name` parameters) through a [`crate::DbCommand`]; the affected rows.
#[doc(hidden)]
pub fn execute(conn: &ConnectionHandle, sql: &str, params: Vec<(&str, DbValue)>) -> DataTask<u64> {
    let mut cmd = crate::command::DbCommand::with_text(sql);
    for (name, value) in params {
        cmd.param(name, value);
    }
    cmd.execute_non_query(conn)
}

/// The first row of a [`query_rows`] task.
#[doc(hidden)]
pub fn first<T: Send + 'static>(task: DataTask<Vec<T>>) -> DataTask<Option<T>> {
    rt::spawn(async move { Ok(task.await?.into_iter().next()) })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::DbKind;

    #[derive(Debug, Clone, PartialEq)]
    struct Person {
        id: i64,
        name: String,
        born: Option<chrono::NaiveDate>,
    }

    impl TypedRow for Person {
        fn table_name() -> &'static str {
            "people"
        }
        fn columns() -> Vec<DataColumn> {
            vec![column("sqlite", "id", "INTEGER", false, true, true, false, 0), column("sqlite", "name", "TEXT", false, false, false, false, 40), column("sqlite", "born", "DATE", true, false, false, false, 0)]
        }
        fn to_values(&self) -> Vec<DbValue> {
            vec![self.id.to_db(), self.name.to_db(), self.born.to_db()]
        }
        fn from_values(values: &[DbValue]) -> Result<Self, DataError> {
            Ok(Self { id: field(values, 0, "id")?, name: field(values, 1, "name")?, born: field(values, 2, "born")? })
        }
    }

    fn ada() -> Person {
        Person { id: 1, name: "Ada".into(), born: chrono::NaiveDate::from_ymd_opt(1815, 12, 10) }
    }

    #[test]
    fn field_values_round_trip() {
        assert_eq!(i32::from_db(&DbValue::Text(" 42 ".into())), Ok(42));
        assert!(u8::from_db(&DbValue::Int(300)).is_err());
        assert_eq!(u64::MAX.to_db(), DbValue::Text(u64::MAX.to_string()));
        assert_eq!(u64::from_db(&u64::MAX.to_db()), Ok(u64::MAX));
        assert_eq!(bool::from_db(&DbValue::Int(1)), Ok(true));
        assert_eq!(f32::from_db(&DbValue::Int(3)), Ok(3.0));
        assert_eq!(Option::<String>::from_db(&DbValue::Null), Ok(None));
        assert_eq!(String::from_db(&DbValue::Null), Err("the value is NULL".to_string()));
        let d = chrono::NaiveDate::from_ymd_opt(2026, 9, 30).expect("date");
        assert_eq!(chrono::NaiveDate::from_db(&d.to_db()), Ok(d));
        let t = d.and_hms_milli_opt(12, 30, 5, 250).expect("time");
        assert_eq!(chrono::NaiveDateTime::from_db(&t.to_db()), Ok(t));
        assert_eq!(chrono::NaiveDateTime::from_db(&DbValue::Text("2026-09-30T12:30:05.250".into())), Ok(t));
        let utc = t.and_utc();
        assert_eq!(chrono::DateTime::<chrono::Utc>::from_db(&utc.to_db()), Ok(utc));
        let u = uuid::Uuid::from_u128(0x1234);
        assert_eq!(uuid::Uuid::from_db(&u.to_db()), Ok(u));
        let j = serde_json::json!({"a": [1, 2]});
        assert_eq!(serde_json::Value::from_db(&j.to_db()), Ok(j));
        assert_eq!(chrono::NaiveTime::from_db(&DbValue::Text("08:15".into())).map(|t| t.to_string()), Ok("08:15:00".to_string()));
    }

    #[test]
    fn tables_round_trip_typed_rows() {
        let table = Table::from_typed(&[ada()]);
        assert_eq!(table.name, "people");
        assert_eq!(table.columns[0].ty.kind, DbKind::Int);
        assert!(table.columns[0].primary_key && table.columns[0].auto_increment);
        assert_eq!(table.columns[1].max_length, Some(40));
        assert_eq!(table.columns[2].ty.kind, DbKind::Date);
        assert_eq!(table.rows()[0].state, RowState::Unchanged);
        assert_eq!(table.to_typed::<Person>(), Ok(vec![ada()]));
        let e = field::<i64>(&[DbValue::Null], 0, "id").expect_err("null");
        assert_eq!(e, DataError::Validation("column `id`: the value is NULL".into()));

        // Columns matched by name, whatever their order (a table filled by an adapter).
        let mut other = Table::new("people", vec![Person::columns()[2].clone(), Person::columns()[1].clone(), Person::columns()[0].clone()]);
        other.load_row(vec![DbValue::Null, "Linus".into(), DbValue::Int(2)]);
        assert_eq!(other.to_typed::<Person>(), Ok(vec![Person { id: 2, name: "Linus".into(), born: None }]));
        let missing = Table::new("x", vec![DataColumn::new("id", DbType::sqlite("INTEGER"))]);
        assert!(missing.to_typed::<Person>().is_err());
    }

    #[test]
    fn binding_source_edits_are_read_back_typed() {
        let mut bs = BindingSource::new();
        bs.load_typed(&[ada(), Person { id: 2, name: "Linus".into(), born: None }]);
        assert_eq!(bs.count(), 2);
        assert_eq!(bs.current_typed::<Person>().ok().flatten(), Some(ada()));
        bs.set_field("name", &kubuno_views::binding::Value::Str("Ada Lovelace".into())).expect("edit");
        bs.end_edit().expect("end edit");
        bs.move_last().expect("move");
        bs.remove_current().expect("delete");
        bs.add_typed(&Person { id: 0, name: "Grace".into(), born: None }).expect("add");
        let changes = bs.typed_changes::<Person>().expect("changes");
        let states: Vec<RowState> = changes.iter().map(|(s, _)| *s).collect();
        assert_eq!(states, [RowState::Modified, RowState::Deleted, RowState::Added]);
        assert_eq!(changes[0].1.name, "Ada Lovelace");
        assert_eq!(changes[1].1.name, "Linus");
        assert_eq!(bs.to_typed::<Person>().map(|v| v.len()), Ok(2));
        bs.table_mut().accept_changes();
        assert!(!bs.has_changes());
    }
}
