//! The `lsp-server` `Connection` main loop: initialize handshake, then
//! dispatch `textDocument/{completion,hover,documentSymbol,definition}`
//! requests and `textDocument/{didOpen,didChange,didClose}` notifications
//! (full text sync — see [`crate::documents`]'s doc comment) until
//! `shutdown`/`exit`.
//!
//! Takes `&Connection` rather than owning it so the same loop drives both a
//! real stdio server ([`Connection::stdio`], from `main.rs`) and the
//! in-memory harness the round-trip tests in `tests/` use
//! ([`Connection::memory`]) — the whole point of choosing `lsp-server` per
//! this crate's `Cargo.toml` doc comment.

use lsp_server::{Connection, ErrorCode, Message, Notification, Request, RequestId, Response};
use std::collections::HashMap;
use std::time::{Duration, Instant, SystemTime};

use lsp_types::{
    CodeActionOrCommand, CodeActionParams, CodeActionProviderCapability, CompletionOptions, CompletionParams,
    CompletionResponse, DidChangeTextDocumentParams,
    DidCloseTextDocumentParams, DidOpenTextDocumentParams, DocumentSymbolParams, DocumentSymbolResponse,
    GotoDefinitionParams, GotoDefinitionResponse, HoverParams, HoverProviderCapability, OneOf,
    PublishDiagnosticsParams, RenameOptions, RenameParams, ServerCapabilities, TextDocumentPositionParams,
    TextDocumentSyncCapability, TextDocumentSyncKind, TextDocumentSyncOptions, Uri,
};

use crate::documents::DocumentStore;
use crate::edit_bridge::{self, ApplyEditParams, ElementAtOffsetParams, RangeOfElementParams};
use crate::convert_handlers::{self, ConvertHandlersParams};
use crate::handler_insert::{self, CreateHandlerParams};
use crate::handlers::{self, CompatibleHandlersParams, RemoveHandlerParams, RenameHandlerParams};
use crate::sources;
use crate::{completion, definition, diagnostics, hover, symbols};

/// A boxed error covering both `lsp-server`'s protocol errors and
/// `serde_json`'s — the one error type this whole module's `Result`s use, so
/// `?` works across both sources without a hand-written `From` impl per call
/// site.
type DynError = Box<dyn std::error::Error + Send + Sync>;

/// Runs the server: the `initialize`/`initialized` handshake, then the main
/// dispatch loop, returning once the client sends `exit` (or the connection
/// closes). The caller (`main.rs`, or a test) owns joining any I/O threads.
pub fn run(connection: &Connection) -> Result<(), DynError> {
    let capabilities = serde_json::to_value(server_capabilities())?;
    // The raw `InitializeParams` (workspace root, client capabilities…) are
    // received but not currently read: nothing in this phase's feature set
    // (diagnostics/completion/hover/symbols/definition, all per-document)
    // depends on workspace configuration or client capability negotiation.
    let _initialize_params = connection.initialize(capabilities)?;
    main_loop(connection)
}

/// How often the code-behind files of the open views are checked for changes (EVT-5): the
/// handler warnings of a view depend on its `.rs` files, which this server is not told about.
const CODE_BEHIND_POLL: Duration = Duration::from_millis(1500);

/// How long after the last edit of a web view its generated `.d.ts` is written (WEB-VIEWS.md §5: "regenerated by
/// the language server on change (debounced)").
const GENERATE_DEBOUNCE: Duration = Duration::from_millis(400);

/// Writes the generated declarations of the web views whose debounce elapsed (`crate::web::language::write_generated`).
fn flush_generated(documents: &DocumentStore, pending: &mut HashMap<String, (Uri, Instant)>) {
    let now = Instant::now();
    let due: Vec<String> = pending.iter().filter(|(_, (_, at))| *at <= now).map(|(k, _)| k.clone()).collect();
    for key in due {
        let Some((uri, _)) = pending.remove(&key) else { continue };
        if let (Some(doc), Some(view)) = (documents.get(&uri), crate::web::web_view(&uri)) {
            let written = crate::web::language::write_generated(doc, &view);
            if written > 0 {
                tracing::info!("{}: {written} generated file(s) written", view.path.display());
            }
        }
    }
}

/// Per open view: its folder's `.rs` files (key, modified, length) at the last check.
type Stamps = HashMap<String, Vec<(String, Option<SystemTime>, u64)>>;

fn main_loop(connection: &Connection) -> Result<(), DynError> {
    let mut documents = DocumentStore::new();
    let mut stamps: Stamps = HashMap::new();
    let mut scanner = crate::project::ProjectScanner::new();
    let mut last_poll = Instant::now();
    let mut pending_generated: HashMap<String, (Uri, Instant)> = HashMap::new();
    loop {
        let msg = match connection.receiver.recv_timeout(CODE_BEHIND_POLL) {
            Ok(msg) => Some(msg),
            Err(crossbeam_channel::RecvTimeoutError::Timeout) => None,
            Err(crossbeam_channel::RecvTimeoutError::Disconnected) => {
                tracing::info!("the client closed the connection");
                return Ok(());
            }
        };
        match msg {
            Some(Message::Request(req)) => {
                if connection.handle_shutdown(&req)? {
                    tracing::info!("shutdown requested by the client");
                    return Ok(());
                }
                let response = handle_request(&documents, req);
                connection.sender.send(Message::Response(response))?;
            }
            Some(Message::Notification(not)) => {
                let opened = not.method == "textDocument/didOpen";
                // A web view opened or edited: its `.d.ts` is regenerated shortly (debounced while typing).
                if opened || not.method == "textDocument/didChange" {
                    if let Some(uri) = not.params.pointer("/textDocument/uri").and_then(|v| v.as_str()).and_then(|s| s.parse::<Uri>().ok()) {
                        if crate::web::is_web(&uri) {
                            let due = if opened { Instant::now() } else { Instant::now() + GENERATE_DEBOUNCE };
                            pending_generated.insert(uri.as_str().to_string(), (uri, due));
                        }
                    }
                }
                // A notification the server cannot read is logged, never fatal: exiting would drop every
                // open view's IntelliSense and the designer's connection.
                if let Err(error) = handle_notification(connection, &mut documents, not) {
                    tracing::warn!("a notification could not be handled: {error}");
                }
                if opened {
                    rescan_project(connection, &documents, &mut scanner)?;
                }
            }
            // This server never issues requests of its own, so it never
            // expects a response back from the client.
            Some(Message::Response(_)) => {}
            None => {}
        }
        flush_generated(&documents, &mut pending_generated);
        if last_poll.elapsed() >= CODE_BEHIND_POLL {
            last_poll = Instant::now();
            republish_on_code_behind_change(connection, &documents, &mut stamps)?;
            rescan_project(connection, &documents, &mut scanner)?;
            // A web registry changed (an element added to `@kubuno/ui`, a project control declared): every web view
            // is validated again.
            if crate::web::project::refresh_all(false) {
                let uris: Vec<Uri> = documents.iter().map(|(uri, _)| uri.clone()).filter(crate::web::is_web).collect();
                for uri in uris {
                    publish_diagnostics(connection, &documents, &uri)?;
                }
            }
        }
    }
}

/// Rescans the project's own controls (EVT-7b, [`crate::project`]) for the open views; when they
/// changed, registers them with the view registry and republishes every open view's diagnostics
/// (a control declared or renamed in Rust and saved clears or raises "unknown element").
fn rescan_project(connection: &Connection, documents: &DocumentStore, scanner: &mut crate::project::ProjectScanner) -> Result<(), DynError> {
    // The desktop views only: a web project's controls come from its JSON registries (`crate::web::project`).
    let views: Vec<std::path::PathBuf> = documents.iter().filter(|(uri, _)| !crate::web::is_web(uri)).filter_map(|(uri, _)| crate::fs_uri::to_path(uri)).collect();
    if let Some(declared) = scanner.refresh(&views) {
        kubuno_desktop_views::registry::set_declared(declared);
        let uris: Vec<Uri> = documents.iter().map(|(uri, _)| uri.clone()).collect();
        for uri in uris {
            publish_diagnostics(connection, documents, &uri)?;
        }
    }
    Ok(())
}

/// Republishes the diagnostics of every open view whose folder's `.rs` files changed on disk
/// since the last check (a handler added, renamed or removed in Rust and saved).
fn republish_on_code_behind_change(
    connection: &Connection,
    documents: &DocumentStore,
    stamps: &mut Stamps,
) -> Result<(), DynError> {
    let uris: Vec<Uri> = documents.iter().map(|(uri, _)| uri.clone()).collect();
    stamps.retain(|key, _| uris.iter().any(|u| u.as_str() == key));
    for uri in uris {
        let Some(path) = crate::fs_uri::to_path(&uri) else { continue };
        let Some(dir) = path.parent().map(std::path::Path::to_path_buf) else { continue };
        // A web view's code-behind is its same-stem `.ts` / `.tsx`; a desktop view's, its folder's `.rs` files.
        let files = if crate::web::is_web(&uri) { crate::web::project::code_behind_of(&path).into_iter().collect() } else { crate::definition::sibling_rs_files(&dir) };
        let mut current: Vec<(String, Option<SystemTime>, u64)> = files
            .into_iter()
            .map(|p| {
                let meta = std::fs::metadata(&p).ok();
                (sources::key(&p), meta.as_ref().and_then(|m| m.modified().ok()), meta.map_or(0, |m| m.len()))
            })
            .collect();
        current.sort();
        let previous = stamps.insert(uri.as_str().to_string(), current.clone());
        if previous.is_some_and(|p| p != current) {
            publish_diagnostics(connection, documents, &uri)?;
        }
    }
    Ok(())
}

/// `kubuno/crateComponents { manifestPath }` (EVT-7b).
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct CrateComponentsParams {
    manifest_path: String,
}

fn server_capabilities() -> ServerCapabilities {
    ServerCapabilities {
        // The options form, not the bare `Kind(FULL)` shorthand: the spec says the
        // shorthand implies open/close notifications, but Visual Studio's LSP
        // client reads it as `openClose: false` and then never sends
        // `didOpen`/`didChange` (seen live: no diagnostics, `documentSymbol`
        // answered `null` for a document this server was never told about).
        text_document_sync: Some(TextDocumentSyncCapability::Options(TextDocumentSyncOptions {
            open_close: Some(true),
            change: Some(TextDocumentSyncKind::FULL),
            ..Default::default()
        })),
        completion_provider: Some(CompletionOptions {
            // '<' (a new element or a closing tag's `</`), ' ' (the gap
            // before the next attribute), '"' (just opened a value, ready
            // for an enum's completion list), '=' (about to type a value).
            trigger_characters: Some(vec!["<".into(), " ".into(), "\"".into(), "=".into()]),
            ..Default::default()
        }),
        hover_provider: Some(HoverProviderCapability::Simple(true)),
        document_symbol_provider: Some(OneOf::Left(true)),
        definition_provider: Some(OneOf::Left(true)),
        // One `refactor.rewrite` action (EVT-4): convert the view's legacy `handlers!` table
        // to typed handlers (`convert_handlers`).
        code_action_provider: Some(CodeActionProviderCapability::Simple(true)),
        // F2 on a handler name in the XML renames the handler (EVT-5, `handlers::rename`).
        rename_provider: Some(OneOf::Right(RenameOptions { prepare_provider: Some(true), work_done_progress_options: Default::default() })),
        // No `document_formatting_provider`: see `lib.rs`'s module doc,
        // "Formatting — deliberately not implemented".
        ..Default::default()
    }
}

/// The document a request is about: `textDocument.uri`, else `uri` (the custom methods).
fn request_uri(req: &Request) -> Option<Uri> {
    let p = &req.params;
    p.pointer("/textDocument/uri").or_else(|| p.get("uri")).and_then(|v| v.as_str()).and_then(|s| s.parse().ok())
}

/// A request about a view of a web project (`crate::web`): answered by the web profile, with the same methods and
/// payloads as the desktop. `None` for the methods both profiles share (`documentSymbol`, the designer's edit and
/// selection methods, the icons), which the desktop dispatch then answers.
fn handle_web_request(documents: &DocumentStore, req: &Request, view: &crate::web::WebView) -> Option<Response> {
    use crate::web::{handlers as web_handlers, language};
    let req = req.clone();
    let response = match req.method.as_str() {
        "textDocument/completion" => respond(req, |p: CompletionParams| {
            let uri = p.text_document_position.text_document.uri;
            CompletionResponse::Array(documents.get(&uri).map(|d| language::completion(d, view, p.text_document_position.position)).unwrap_or_default())
        }),
        "textDocument/hover" => respond(req, |p: HoverParams| {
            let uri = p.text_document_position_params.text_document.uri;
            documents.get(&uri).and_then(|d| language::hover(d, view, p.text_document_position_params.position))
        }),
        "textDocument/definition" => respond(req, |p: GotoDefinitionParams| {
            let uri = p.text_document_position_params.text_document.uri;
            documents.get(&uri).and_then(|d| language::definition(d, view, p.text_document_position_params.position)).map(|l| GotoDefinitionResponse::Array(vec![l]))
        }),
        "textDocument/codeAction" => respond(req, |p: CodeActionParams| {
            let uri = &p.text_document.uri;
            let actions: Vec<CodeActionOrCommand> =
                documents.get(uri).map(|d| language::code_actions(d, uri, view, &p.range)).unwrap_or_default().into_iter().map(CodeActionOrCommand::CodeAction).collect();
            if actions.is_empty() { None } else { Some(actions) }
        }),
        "textDocument/prepareRename" => respond(req, |p: TextDocumentPositionParams| documents.get(&p.text_document.uri).and_then(|d| web_handlers::prepare_rename(d, view, p.position))),
        "textDocument/rename" => {
            let id = req.id.clone();
            match serde_json::from_value::<RenameParams>(req.params) {
                Ok(p) => {
                    let pos = p.text_document_position;
                    match web_handlers::rename(documents, &pos.text_document.uri, view, pos.position, &p.new_name) {
                        Ok(edit) => Response::new_ok(id, edit),
                        Err(reason) => Response::new_err(id, ErrorCode::RequestFailed as i32, reason),
                    }
                }
                Err(err) => Response::new_err(id, ErrorCode::InvalidParams as i32, err.to_string()),
            }
        }
        "kubuno/registry" => Response::new_ok(req.id, language::registry_json(view)),
        "kubuno/registryVersion" => Response::new_ok(req.id, serde_json::json!({ "version": language::registry_json(view)["version"] })),
        "kubuno/createHandler" => respond(req, |p: CreateHandlerParams| {
            sources::with_overlays(&p.open_files, || web_handlers::create_handler(documents.get(&p.uri), &p.uri, view, &p))
        }),
        "kubuno/compatibleHandlers" => respond(req, |p: CompatibleHandlersParams| {
            sources::with_overlays(&p.open_files, || web_handlers::compatible_handlers(documents.get(&p.uri), view, &p))
        }),
        "kubuno/renameHandler" => respond(req, |p: RenameHandlerParams| sources::with_overlays(&p.open_files, || web_handlers::rename_handler(documents, view, &p))),
        "kubuno/removeHandler" => respond(req, |p: RemoveHandlerParams| sources::with_overlays(&p.open_files, || web_handlers::remove_handler(documents, view, &p))),
        "kubuno/bindingPaths" => respond(req, |p: crate::bindings::BindingPathsParams| {
            sources::with_overlays(&p.open_files, || crate::bindings::BindingPathsResult { paths: language::binding_paths(view) })
        }),
        "kubuno/bindingDefinition" => respond(req, |p: crate::binding_lsp::BindingDefinitionParams| {
            sources::with_overlays(&p.open_files, || documents.get(&p.uri).and_then(|d| language::binding_definition(d, view, &p.element_id, &p.attribute)))
        }),
        // Desktop-only methods (Rust code-behind, data sources): nothing for a web view.
        "kubuno/bindingSources" | "kubuno/convertHandlers" => Response::new_ok(req.id, serde_json::Value::Null),
        _ => return None,
    };
    Some(response)
}

fn handle_request(documents: &DocumentStore, req: Request) -> Response {
    if let Some(view) = request_uri(&req).and_then(|uri| crate::web::web_view(&uri)) {
        if let Some(response) = handle_web_request(documents, &req, &view) {
            return response;
        }
    }
    match req.method.as_str() {
        "textDocument/completion" => respond(req, |p: CompletionParams| {
            let uri = p.text_document_position.text_document.uri;
            let pos = p.text_document_position.position;
            // `{Binding …}` parts, then `{Res …}` keys (vskubuno docs/RESOURCES.md), else the ordinary completion.
            let items = documents
                .get(&uri)
                .map(|d| crate::binding_lsp::completion(d, &uri, pos).or_else(|| crate::resources::completion(d, &uri, pos)).unwrap_or_else(|| completion::completion(d, pos)))
                .unwrap_or_default();
            CompletionResponse::Array(items)
        }),
        "textDocument/hover" => respond(req, |p: HoverParams| {
            let uri = p.text_document_position_params.text_document.uri;
            let pos = p.text_document_position_params.position;
            documents.get(&uri).and_then(|d| crate::resources::hover(d, &uri, pos).or_else(|| crate::binding_lsp::hover(d, &uri, pos)).or_else(|| hover::hover(d, pos)))
        }),
        "textDocument/documentSymbol" => respond(req, |p: DocumentSymbolParams| {
            let uri = p.text_document.uri;
            let syms = documents.get(&uri).map(symbols::document_symbols).unwrap_or_default();
            if syms.is_empty() { None } else { Some(DocumentSymbolResponse::Nested(syms)) }
        }),
        "textDocument/definition" => respond(req, |p: GotoDefinitionParams| {
            let uri = p.text_document_position_params.text_document.uri;
            let pos = p.text_document_position_params.position;
            let locations =
                documents.get(&uri).map(|d| crate::resources::definition(d, &uri, pos).or_else(|| crate::binding_lsp::definition(d, &uri, pos)).map(|l| vec![l]).unwrap_or_else(|| definition::goto_definition(d, &uri, pos))).unwrap_or_default();
            if locations.is_empty() { None } else { Some(GotoDefinitionResponse::Array(locations)) }
        }),
        // Custom methods for the visual designer (`vskubuno/docs/DESIGNER.md`,
        // work package DSG-2 — see its "DSG-2 protocol" section for the wire
        // shapes). All three degrade to an empty/`None` result for a `uri`
        // this server has no open document for, rather than an error: a
        // designer gesture racing the document's own open/close is not
        // exceptional.
        // `kubuno/registry` (work package DSG-1, `vskubuno/docs/DESIGNER.md`
        // §5/§8): the whole component registry, JSON-exported by
        // `kubuno_desktop_views::registry::export` — see that module's own doc for
        // the wire shape. Takes no params (unlike the DSG-2 methods below),
        // so it bypasses `respond`'s params-deserialization step entirely.
        "kubuno/registry" => match serde_json::to_value(kubuno_desktop_views::registry::export::export()) {
            Ok(value) => Response::new_ok(req.id, value),
            Err(err) => Response::new_err(req.id, ErrorCode::InternalError as i32, err.to_string()),
        },
        // The Kubuno icon set, with the paths of every glyph: the Visual Studio icon picker draws its
        // gallery from it (`kubuno_desktop_views::icon::catalog_json`).
        "kubuno/icons" => Response::new_ok(req.id, kubuno_desktop_views::icon::catalog_json()),
        // One icon value rendered exactly as the application will draw it (an image file of any
        // format, a glyph, their options), for the picker's previews.
        "kubuno/renderIcon" => respond(req, |p: RenderIconParams| {
            let base_dir = p.uri.as_ref().and_then(crate::fs_uri::to_path).and_then(|f| f.parent().map(std::path::Path::to_path_buf));
            kubuno_desktop_views::icon::render_json(&p.value, base_dir.as_deref(), p.size.unwrap_or(32), p.color.as_deref().unwrap_or("#202124"))
        }),
        // EVT-7b: the controls another crate declares (Visual Studio's "Choisir des éléments…").
        "kubuno/crateComponents" => respond(req, |p: CrateComponentsParams| {
            let (crate_name, components) = crate::project::crate_components(std::path::Path::new(&p.manifest_path));
            serde_json::json!({ "crateName": crate_name, "components": components })
        }),
        // EVT-7b: the registry's version only (it changes when the project's controls do): what the designer polls
        // before fetching the whole `kubuno/registry` again.
        "kubuno/registryVersion" => Response::new_ok(req.id, serde_json::json!({ "version": kubuno_desktop_views::registry::export::export().version })),
        "kubuno/applyEdit" => respond(req, |p: ApplyEditParams| edit_bridge::apply_edit(documents.get(&p.uri), &p.op)),
        "kubuno/elementAtOffset" => respond(req, |p: ElementAtOffsetParams| {
            documents.get(&p.uri).and_then(|d| edit_bridge::element_at_offset(d, p.position))
        }),
        "kubuno/rangeOfElement" => respond(req, |p: RangeOfElementParams| {
            documents.get(&p.uri).and_then(|d| edit_bridge::range_of_element(d, &p.element_id))
        }),
        // `kubuno/createHandler` (work package DSG-10, `vskubuno/docs/
        // DESIGNER.md`): double-click on a control/event on the design
        // surface -> create the Rust handler. See `handler_insert`'s own doc
        // for the two-part edit (`.kbview` attribute + code-behind `.rs`
        // stub) and the "already exists -> just a location" short circuit.
        "kubuno/createHandler" => respond(req, |p: CreateHandlerParams| {
            sources::with_overlays(&p.open_files, || handler_insert::create_handler(documents.get(&p.uri), &p.uri, &p))
        }),
        "textDocument/codeAction" => respond(req, |p: CodeActionParams| {
            let uri = &p.text_document.uri;
            // Quick fixes first (a missing handler, an older event name), then the conversion.
            let mut quick = documents.get(uri).map(|d| handlers::quick_fixes(d, uri, &p.range)).unwrap_or_default();
            // « Mettre à jour les liaisons » after a member was renamed.
            quick.extend(documents.get(uri).map(|d| crate::binding_lsp::code_actions(d, uri, &p.context.diagnostics)).unwrap_or_default());
            // « Renommer en .kbcontrol / .kbview » when the extension disagrees with the view's kind.
            quick.extend(documents.get(uri).map(|d| crate::view_kind::quick_fixes(d, uri, &p.range)).unwrap_or_default());
            // « Did you mean »: a misspelt element or attribute, `Binding="…"` (vskubuno docs/DESIGNER.md §17).
            quick.extend(documents.get(uri).map(|d| diagnostics::suggestion_fixes(d, uri, &p.range)).unwrap_or_default());
            // « Ajouter les déclarations d'espaces de noms manquantes »: an undeclared `x:` / `d:` prefix.
            quick.extend(documents.get(uri).map(|d| crate::namespaces::quick_fixes(d, uri, &p.range)).unwrap_or_default());
            let actions: Vec<CodeActionOrCommand> =
                quick.into_iter().chain(convert_handlers::code_actions(uri)).map(CodeActionOrCommand::CodeAction).collect();
            if actions.is_empty() { None } else { Some(actions) }
        }),
        // EVT-5 (`handlers`): the ⚡ row's dropdown, rename and clear.
        "kubuno/compatibleHandlers" => respond(req, |p: CompatibleHandlersParams| {
            sources::with_overlays(&p.open_files, || handlers::compatible_handlers(documents.get(&p.uri), &p))
        }),
        "kubuno/renameHandler" => respond(req, |p: RenameHandlerParams| sources::with_overlays(&p.open_files, || handlers::rename_handler(documents, &p))),
        "kubuno/removeHandler" => respond(req, |p: RemoveHandlerParams| sources::with_overlays(&p.open_files, || handlers::remove_handler(documents, &p))),
        "textDocument/prepareRename" => respond(req, |p: TextDocumentPositionParams| {
            documents.get(&p.text_document.uri).and_then(|d| handlers::prepare_rename(d, p.position))
        }),
        "textDocument/rename" => {
            let id = req.id.clone();
            match serde_json::from_value::<RenameParams>(req.params) {
                Ok(p) => {
                    let pos = p.text_document_position;
                    match handlers::rename(documents, &pos.text_document.uri, pos.position, &p.new_name) {
                        Ok(edit) => Response::new_ok(id, edit),
                        Err(reason) => Response::new_err(id, ErrorCode::RequestFailed as i32, reason),
                    }
                }
                Err(err) => Response::new_err(id, ErrorCode::InvalidParams as i32, err.to_string()),
            }
        }
        // `kubuno/convertHandlers { uri }` (EVT-4): the same conversion as the code action, for
        // the designer's command; the result says why when there is nothing to convert.
        // The binding paths of the view's code-behind (the Properties window's binding picker).
        "kubuno/bindingPaths" => respond(req, |p: crate::bindings::BindingPathsParams| {
            sources::with_overlays(&p.open_files, || crate::bindings::binding_paths(&p.uri))
        }),
        // The source schema of an element's bindings and their problems (the binding picker, the
        // « Liaison de données » dialog, the Properties window's markers).
        "kubuno/bindingSources" => respond(req, |p: crate::binding_sources::BindingSourcesParams| {
            sources::with_overlays(&p.open_files, || crate::binding_sources::binding_sources(documents.get(&p.uri), &p))
        }),
        // A sample value through a binding's converter and format, as the runtime shows it.
        "kubuno/bindingPreview" => respond(req, |p: crate::binding_lsp::BindingPreviewParams| crate::binding_lsp::binding_preview(&p)),
        "kubuno/bindingDefinition" => respond(req, |p: crate::binding_lsp::BindingDefinitionParams| {
            sources::with_overlays(&p.open_files, || crate::binding_lsp::binding_definition(documents.get(&p.uri), &p))
        }),
        "kubuno/convertHandlers" => respond(req, |p: ConvertHandlersParams| {
            sources::with_overlays(&p.open_files, || convert_handlers::convert_handlers(&p.uri))
        }),
        other => {
            Response::new_err(req.id, ErrorCode::MethodNotFound as i32, format!("unhandled method: {other}"))
        }
    }
}

/// Deserializes `req`'s params as `P`, calls `f`, and serializes the result
/// back into a [`Response`] — the one place every request handler above
/// converts a typed `(params) -> result` function into the untyped
/// `Request -> Response` shape `lsp-server` moves over the wire, so a
/// malformed params payload from the client becomes a proper JSON-RPC
/// "invalid params" error response instead of a panic.
fn respond<P, R, F>(req: Request, f: F) -> Response
where
    P: serde::de::DeserializeOwned,
    R: serde::Serialize,
    F: FnOnce(P) -> R,
{
    let id: RequestId = req.id;
    match serde_json::from_value::<P>(req.params) {
        Ok(params) => Response::new_ok(id, f(params)),
        Err(err) => Response::new_err(id, ErrorCode::InvalidParams as i32, err.to_string()),
    }
}

fn handle_notification(
    connection: &Connection,
    documents: &mut DocumentStore,
    not: Notification,
) -> Result<(), DynError> {
    match not.method.as_str() {
        "textDocument/didOpen" => {
            let p: DidOpenTextDocumentParams = serde_json::from_value(not.params)?;
            let uri = p.text_document.uri;
            documents.open(uri.clone(), p.text_document.text, p.text_document.version);
            publish_diagnostics(connection, documents, &uri)?;
        }
        "textDocument/didChange" => {
            let p: DidChangeTextDocumentParams = serde_json::from_value(not.params)?;
            let uri = p.text_document.uri;
            // Full sync (`TextDocumentSyncKind::FULL`, advertised above): the
            // client sends exactly one change event carrying the whole new
            // text, so only the last (and only) entry matters.
            if let Some(change) = p.content_changes.into_iter().next_back() {
                documents.update(uri.clone(), change.text, p.text_document.version);
                publish_diagnostics(connection, documents, &uri)?;
            }
        }
        "textDocument/didClose" => {
            let p: DidCloseTextDocumentParams = serde_json::from_value(not.params)?;
            documents.close(&p.text_document.uri);
            // A view renamed or deleted (the « Renommer en .kbcontrol » quick fix closes the old name): its warnings
            // would otherwise stay in the Error List under a file that no longer exists.
            if crate::fs_uri::to_path(&p.text_document.uri).is_some_and(|path| !path.exists()) {
                let params = PublishDiagnosticsParams { uri: p.text_document.uri, diagnostics: Vec::new(), version: None };
                connection.sender.send(Message::Notification(Notification::new("textDocument/publishDiagnostics".to_string(), params)))?;
            }
        }
        // `initialized`, `$/cancelRequest`, etc. — nothing this phase needs
        // to react to.
        _ => {}
    }
    Ok(())
}

fn publish_diagnostics(connection: &Connection, documents: &DocumentStore, uri: &Uri) -> Result<(), DynError> {
    let Some(doc) = documents.get(uri) else { return Ok(()) };
    if let Some(view) = crate::web::web_view(uri) {
        let diagnostics = crate::web::language::diagnostics(doc, &view)
            .into_iter()
            .map(|mut d| {
                d.message = kubuno_desktop_views::messages::localize(&d.message);
                d
            })
            .collect();
        let params = PublishDiagnosticsParams { uri: uri.clone(), diagnostics, version: Some(doc.version) };
        connection.sender.send(Message::Notification(Notification::new("textDocument/publishDiagnostics".to_string(), params)))?;
        return Ok(());
    }
    let params = PublishDiagnosticsParams {
        uri: uri.clone(),
        diagnostics: diagnostics::document_diagnostics(doc)
            .into_iter()
            .chain(handlers::handler_diagnostics(doc, uri))
            .chain(diagnostics::icon_file_diagnostics(doc, uri))
            .chain(crate::resources::diagnostics(doc, uri))
            .chain(crate::binding_lsp::diagnostics(doc, uri))
            .chain(crate::view_kind::diagnostics(doc, uri))
            .chain(crate::storage::diagnostics(doc, uri))
            .chain(crate::namespaces::diagnostics(doc))
            // In Visual Studio's UI language (`KUBUNO_UI_LANG`, vskubuno docs/DESIGNER.md §17).
            .map(|mut d| {
                d.message = kubuno_desktop_views::messages::localize(&d.message);
                d
            })
            .collect(),
        version: Some(doc.version),
    };
    let note = Notification::new("textDocument/publishDiagnostics".to_string(), params);
    connection.sender.send(Message::Notification(note))?;
    Ok(())
}

/// `kubuno/renderIcon`'s parameters: the icon value as written, the `.kbview` it belongs to (its
/// folder resolves a relative file), the size in pixels (32 by default) and the colour of a glyph
/// and an SVG's `currentColor` (`#rrggbb`).
#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct RenderIconParams {
    value: String,
    #[serde(default)]
    uri: Option<lsp_types::Uri>,
    #[serde(default)]
    size: Option<u32>,
    #[serde(default)]
    color: Option<String>,
}
