//! The levels between `Control` and the concrete classes: `ScrollableControl` →
//! `ContainerControl` → `UserControl` / `View`, and the family bases `ButtonBase`, `TextBoxBase`,
//! `ListControl`, `LabelBase`, `ContainerBase`, `RangeBase` (the design note's `ScrollBarBase`:
//! every value-in-a-range control). Each is a trait with default methods plus a core struct the
//! classes of that family embed (`ButtonBaseCore` derefs to [`ControlCore`], which derefs to the
//! WinForms property replica).

use std::ops::{Deref, DerefMut};

use kubuno_controls::host::vk;
use kubuno_controls::ContentAlignment;
use kubuno_ui::Size;

use super::control::{Control, ControlCore, ControlLink, ControlStyles, HasControlCore, Keys};
use super::cx::EventCx;
use super::{ComponentCore, HasComponentCore, Lineage};
use crate::events::{
    ChangeSource, CheckedChangedEventArgs, EmptyEventArgs, Event, FormClosedEventArgs, FormClosingEventArgs, MouseEventArgs, NumericValueChangedEventArgs, ScrollEventArgs,
    SelectionChangedEventArgs, TextChangedEventArgs,
};
use crate::registry::LayoutKind;

/// Declares a level's hidden plumbing: `Has<Level>Core` (the core accessor) and `<Level>Link`
/// (the base object a class delegates to), both generated by `#[derive(Component)]`.
macro_rules! plumbing {
    ($has:ident, $core:ident, $get:ident, $get_mut:ident, $link:ident, $level:ident, $base:ident, $base_mut:ident) => {
        #[doc = concat!("Reaches the [`", stringify!($core), "`] (generated by `#[derive(Component)]`; the cores implement it).")]
        #[doc(hidden)]
        pub trait $has {
            fn $get(&self) -> &$core;
            fn $get_mut(&mut self) -> &mut $core;
        }

        impl $has for $core {
            fn $get(&self) -> &$core {
                self
            }
            fn $get_mut(&mut self) -> &mut $core {
                self
            }
        }

        #[doc = concat!("The base object a `", stringify!($level), "` class delegates to (generated by `#[derive(Component)]`).")]
        #[doc(hidden)]
        pub trait $link: $has {
            fn $base(&self) -> Option<&dyn $level>;
            fn $base_mut(&mut self) -> Option<&mut dyn $level>;
        }
    };
}

/// Implements a lower level's accessor for a core, through the embedded field path.
macro_rules! lower {
    ($core:ident: $($has:ident :: $get:ident / $get_mut:ident -> $target:ty = $($field:ident).+;)*) => {$(
        impl $has for $core {
            fn $get(&self) -> &$target {
                &self.$($field).+
            }
            fn $get_mut(&mut self) -> &mut $target {
                &mut self.$($field).+
            }
        }
    )*};
}

/// Deref from a core to the core it embeds.
macro_rules! deref_to {
    ($core:ident => $field:ident: $target:ty) => {
        impl Deref for $core {
            type Target = $target;
            fn deref(&self) -> &$target {
                &self.$field
            }
        }
        impl DerefMut for $core {
            fn deref_mut(&mut self) -> &mut $target {
                &mut self.$field
            }
        }
    };
}

/// Overridable level methods: delegate to the base object, else raise.
macro_rules! level_overridable {
    ($base_mut:ident; $($(#[$doc:meta])* fn $method:ident($args:ty) => $event:literal;)*) => {$(
        $(#[$doc])*
        fn $method(&mut self, e: &mut EventCx<'_, $args>) {
            if let Some(base) = self.$base_mut() {
                return base.$method(e);
            }
            e.raise(&*self, $event);
        }
    )*};
}

/// Event accessors of a level.
macro_rules! level_accessors {
    ($($(#[$doc:meta])* fn $name:ident($args:ty) => $event:literal;)*) => {$(
        $(#[$doc])*
        fn $name(&self) -> Event<$args> {
            self.component_core().events.event($event)
        }
    )*};
}

fn styles_without(mut s: ControlStyles, off: ControlStyles) -> ControlStyles {
    s.set(off, false);
    s
}

// ── ScrollableControl ───────────────────────────────────────────────────────────────────

/// The state of `ScrollableControl` (WinForms: the base of every control that scrolls its
/// content — `Panel`, `ContainerControl`).
pub struct ScrollableControlCore {
    pub control: ControlCore,
    /// `AutoScroll`: scroll bars appear when the content outgrows the control.
    pub auto_scroll: bool,
    /// `AutoScrollPosition`, the scroll offset (x, y), in DIP.
    pub auto_scroll_position: (f32, f32),
    /// `AutoScrollMinSize`.
    pub auto_scroll_min_size: Size,
}

impl Default for ScrollableControlCore {
    fn default() -> Self {
        let mut control = ControlCore::default();
        control.styles = control.styles | ControlStyles::CONTAINER_CONTROL;
        Self { control, auto_scroll: false, auto_scroll_position: (0.0, 0.0), auto_scroll_min_size: Size::EMPTY }
    }
}

deref_to!(ScrollableControlCore => control: ControlCore);
plumbing!(HasScrollableControlCore, ScrollableControlCore, scrollable_control_core, scrollable_control_core_mut, ScrollableControlLink, ScrollableControl, base_scrollable_control, base_scrollable_control_mut);
lower!(ScrollableControlCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for ScrollableControlCore {
    const CHAIN: &'static [&'static str] = &["ScrollableControl", "Control", "Component"];
}

/// A control that scrolls its content (WinForms `ScrollableControl`).
pub trait ScrollableControl: Control + ScrollableControlLink {
    /// `AutoScroll`.
    fn auto_scroll(&self) -> bool {
        self.scrollable_control_core().auto_scroll
    }

    /// `AutoScrollPosition`.
    fn auto_scroll_position(&self) -> (f32, f32) {
        self.scrollable_control_core().auto_scroll_position
    }

    /// Scrolls to `(x, y)`, raising `Scroll` when it moved (source: code).
    fn set_auto_scroll_position(&mut self, x: f32, y: f32) {
        let old = std::mem::replace(&mut self.scrollable_control_core_mut().auto_scroll_position, (x, y));
        if old != (x, y) {
            let mut args = ScrollEventArgs { old: old.1, new: y, ..Default::default() };
            self.on_scroll(&mut EventCx::new(&mut args).from_class(self.class_name()));
        }
    }

    level_overridable! { base_scrollable_control_mut;
        /// Raises `Scroll` (WinForms `ScrollableControl.OnScroll`).
        fn on_scroll(ScrollEventArgs) => "OnScroll";
    }

    level_accessors! {
        /// `Scroll`.
        fn scroll(ScrollEventArgs) => "OnScroll";
    }
}

// ── ContainerControl ────────────────────────────────────────────────────────────────────

/// The state of `ContainerControl` (WinForms: a control that manages the focus of the controls
/// inside it — `Form`, `UserControl`).
#[derive(Default)]
pub struct ContainerControlCore {
    pub scrollable: ScrollableControlCore,
    /// `ActiveControl`: the `x:Name` of the control inside that has (or last had) the focus.
    pub active_control: Option<String>,
    /// A control to give the focus to at the next frame (`set_active_control`).
    pub(crate) focus_request: Option<String>,
}

deref_to!(ContainerControlCore => scrollable: ScrollableControlCore);
plumbing!(HasContainerControlCore, ContainerControlCore, container_control_core, container_control_core_mut, ContainerControlLink, ContainerControl, base_container_control, base_container_control_mut);
lower!(ContainerControlCore:
    HasScrollableControlCore::scrollable_control_core / scrollable_control_core_mut -> ScrollableControlCore = scrollable;
    HasControlCore::control_core / control_core_mut -> ControlCore = scrollable.control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = scrollable.control.component;
);
impl Lineage for ContainerControlCore {
    const CHAIN: &'static [&'static str] = &["ContainerControl", "ScrollableControl", "Control", "Component"];
}

/// A control that manages the focus of the controls inside it (WinForms `ContainerControl`).
pub trait ContainerControl: ScrollableControl + ContainerControlLink {
    /// `ActiveControl`.
    fn active_control(&self) -> Option<&str> {
        self.container_control_core().active_control.as_deref()
    }

    /// Sets `ActiveControl` (by `x:Name`): the control inside of that name takes the keyboard focus at
    /// the next frame (WinForms `ActiveControl = textBox1`).
    fn set_active_control(&mut self, name: Option<&str>) {
        let core = self.container_control_core_mut();
        core.active_control = name.map(str::to_string);
        core.focus_request = name.map(str::to_string);
    }
}

// ── UserControl ─────────────────────────────────────────────────────────────────────────

/// The state of `UserControl`.
#[derive(Default)]
pub struct UserControlCore {
    pub container: ContainerControlCore,
}

deref_to!(UserControlCore => container: ContainerControlCore);
plumbing!(HasUserControlCore, UserControlCore, user_control_core, user_control_core_mut, UserControlLink, UserControl, base_user_control, base_user_control_mut);
lower!(UserControlCore:
    HasContainerControlCore::container_control_core / container_control_core_mut -> ContainerControlCore = container;
    HasScrollableControlCore::scrollable_control_core / scrollable_control_core_mut -> ScrollableControlCore = container.scrollable;
    HasControlCore::control_core / control_core_mut -> ControlCore = container.scrollable.control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = container.scrollable.control.component;
);
impl Lineage for UserControlCore {
    const CHAIN: &'static [&'static str] = &["UserControl", "ContainerControl", "ScrollableControl", "Control", "Component"];
}

/// A composite control designed as a `.kbview` of its own (WinForms `UserControl`; the XML side
/// is EVT-7b).
pub trait UserControl: ContainerControl + UserControlLink {
    level_overridable! { base_user_control_mut;
        /// Raises `Load`, before the user control is first shown.
        fn on_load(EmptyEventArgs) => "OnLoad";
    }

    level_accessors! {
        /// `Load`.
        fn load(EmptyEventArgs) => "OnLoad";
    }
}

// ── View (the Form) ─────────────────────────────────────────────────────────────────────

/// The state of `View`, the Kubuno `Form`: a view shown in its own window.
#[derive(Default)]
pub struct ViewCore {
    pub container: ContainerControlCore,
    /// `KeyPreview`: the view sees the keys before the focused control.
    pub key_preview: bool,
}

deref_to!(ViewCore => container: ContainerControlCore);
plumbing!(HasViewCore, ViewCore, view_core, view_core_mut, ViewLink, View, base_view, base_view_mut);
lower!(ViewCore:
    HasContainerControlCore::container_control_core / container_control_core_mut -> ContainerControlCore = container;
    HasScrollableControlCore::scrollable_control_core / scrollable_control_core_mut -> ScrollableControlCore = container.scrollable;
    HasControlCore::control_core / control_core_mut -> ControlCore = container.scrollable.control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = container.scrollable.control.component;
);
impl Lineage for ViewCore {
    const CHAIN: &'static [&'static str] = &["View", "ContainerControl", "ScrollableControl", "Control", "Component"];
}

/// A view in its own window (WinForms `Form`): the lifecycle Load → Activated → Shown, and
/// FormClosing (cancelable) → FormClosed.
pub trait View: ContainerControl + ViewLink {
    /// `KeyPreview`.
    fn key_preview(&self) -> bool {
        self.view_core().key_preview
    }

    level_overridable! { base_view_mut;
        /// Raises `Load`, before the view is shown for the first time.
        fn on_load(EmptyEventArgs) => "OnLoad";
        /// Raises `Shown`, after the first frame.
        fn on_shown(EmptyEventArgs) => "OnShown";
        /// Raises `Activated`.
        fn on_activated(EmptyEventArgs) => "OnActivated";
        /// Raises `Deactivate`.
        fn on_deactivate(EmptyEventArgs) => "OnDeactivate";
        /// Raises `FormClosing`; setting `e.cancel` keeps the window open.
        fn on_form_closing(FormClosingEventArgs) => "OnFormClosing";
        /// Raises `FormClosed`.
        fn on_form_closed(FormClosedEventArgs) => "OnFormClosed";
    }

    level_accessors! {
        /// `Load`.
        fn load(EmptyEventArgs) => "OnLoad";
        /// `Shown`.
        fn shown(EmptyEventArgs) => "OnShown";
        /// `Activated`.
        fn activated(EmptyEventArgs) => "OnActivated";
        /// `Deactivate`.
        fn deactivate(EmptyEventArgs) => "OnDeactivate";
        /// `FormClosing`.
        fn form_closing(FormClosingEventArgs) => "OnFormClosing";
        /// `FormClosed`.
        fn form_closed(FormClosedEventArgs) => "OnFormClosed";
    }
}

// ── ButtonBase ──────────────────────────────────────────────────────────────────────────

/// The state of `ButtonBase` (WinForms: `Button`, `CheckBox`, `RadioButton`; here also
/// `IconButton` and `Switch`).
pub struct ButtonBaseCore {
    pub control: ControlCore,
    /// `IsDefault`: the view's accept button (Enter), painted with a distinct border.
    pub is_default: bool,
    /// `AutoEllipsis`.
    pub auto_ellipsis: bool,
    /// `TextAlign`.
    pub text_align: ContentAlignment,
    /// `Image`: the path of an image file shown on the button.
    pub image: Option<String>,
    /// `ImageAlign`.
    pub image_align: ContentAlignment,
    /// `TextImageRelation`.
    pub text_image_relation: kubuno_controls::buttons::TextImageRelation,
    /// `UseMnemonic`: an `&` in the text marks its keyboard shortcut.
    pub use_mnemonic: bool,
    /// The shown text's character underlined this frame (the mnemonic, while Alt is held).
    pub mnemonic: Option<usize>,
}

impl Default for ButtonBaseCore {
    /// WinForms' `ButtonBase` styles: resize-redraw, transparent back colour, cached text; no
    /// standard double-click (a second quick click is a second Click).
    fn default() -> Self {
        let mut control = ControlCore::default();
        control.styles = styles_without(control.styles, ControlStyles::STANDARD_DOUBLE_CLICK)
            | ControlStyles::RESIZE_REDRAW
            | ControlStyles::SUPPORTS_TRANSPARENT_BACK_COLOR
            | ControlStyles::CACHE_TEXT;
        Self {
            control,
            is_default: false,
            auto_ellipsis: false,
            text_align: ContentAlignment::MiddleCenter,
            image: None,
            image_align: ContentAlignment::MiddleCenter,
            text_image_relation: kubuno_controls::buttons::TextImageRelation::Overlay,
            use_mnemonic: true,
            mnemonic: None,
        }
    }
}

impl ButtonBaseCore {
    /// A core labelled `text`.
    pub fn with_text(text: &str) -> Self {
        let mut core = Self::default();
        core.control.text = text.to_string();
        core
    }
}

deref_to!(ButtonBaseCore => control: ControlCore);
plumbing!(HasButtonBaseCore, ButtonBaseCore, button_base_core, button_base_core_mut, ButtonBaseLink, ButtonBase, base_button_base, base_button_base_mut);
lower!(ButtonBaseCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for ButtonBaseCore {
    const CHAIN: &'static [&'static str] = &["ButtonBase", "Control", "Component"];
}

/// The buttons (WinForms `ButtonBase`).
pub trait ButtonBase: Control + ButtonBaseLink {
    /// `IsDefault`.
    fn is_default(&self) -> bool {
        self.button_base_core().is_default
    }

    /// WinForms `PerformClick()`: raises Click as a keyboard activation would (no button, no
    /// click count), through the outermost `on_click` override. Nothing when the button cannot
    /// be selected (hidden, disabled).
    fn perform_click(&mut self) {
        if !self.can_select() {
            return;
        }
        let mut args = MouseEventArgs::default();
        self.on_click(&mut EventCx::new(&mut args).from_class(self.class_name()));
    }

    level_overridable! { base_button_base_mut;
        /// Raises `CheckedChanged` (the checkable buttons: `CheckBox`, `RadioButton`, `Switch`).
        fn on_checked_changed(CheckedChangedEventArgs) => "OnCheckedChanged";
    }

    level_accessors! {
        /// `CheckedChanged`.
        fn checked_changed(CheckedChangedEventArgs) => "OnCheckedChanged";
    }
}

// ── TextBoxBase ─────────────────────────────────────────────────────────────────────────

/// The state of `TextBoxBase` (WinForms: `TextBox`, `MaskedTextBox`, `RichTextBox`; here
/// `TextField`, `TextArea`, `MaskedField`, `SearchField`).
pub struct TextBoxBaseCore {
    pub control: ControlCore,
    /// `ReadOnly`.
    pub read_only: bool,
    /// `MaxLength` (WinForms' default, 32767).
    pub max_length: usize,
    /// `Multiline`: Enter and the vertical arrows are input keys.
    pub multiline: bool,
    /// `AcceptsTab`: Tab is an input key (it does not move the focus).
    pub accepts_tab: bool,
    /// `PlaceholderText`.
    pub placeholder: String,
    /// `Modified`: the user edited the text since it was last set.
    pub modified: bool,
}

impl Default for TextBoxBaseCore {
    fn default() -> Self {
        Self { control: ControlCore::default(), read_only: false, max_length: 32767, multiline: false, accepts_tab: false, placeholder: String::new(), modified: false }
    }
}

deref_to!(TextBoxBaseCore => control: ControlCore);
plumbing!(HasTextBoxBaseCore, TextBoxBaseCore, text_box_base_core, text_box_base_core_mut, TextBoxBaseLink, TextBoxBase, base_text_box_base, base_text_box_base_mut);
lower!(TextBoxBaseCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for TextBoxBaseCore {
    const CHAIN: &'static [&'static str] = &["TextBoxBase", "Control", "Component"];
}

impl TextBoxBaseCore {
    /// WinForms `TextBoxBase.IsInputKey`: the horizontal arrows, Home/End; Enter and the vertical
    /// arrows when multiline; Tab when `accepts_tab`. What the text classes' `is_input_key`
    /// answers.
    pub fn is_input_key(&self, key: Keys) -> bool {
        if key.mods.alt {
            return false;
        }
        match key.key.0 {
            vk::LEFT | vk::RIGHT | vk::HOME | vk::END => true,
            vk::UP | vk::DOWN | vk::ENTER => self.multiline,
            vk::TAB => self.accepts_tab && !key.mods.ctrl,
            _ => false,
        }
    }
}

/// The text fields (WinForms `TextBoxBase`).
pub trait TextBoxBase: Control + TextBoxBaseLink {
    /// `ReadOnly`.
    fn read_only(&self) -> bool {
        self.text_box_base_core().read_only
    }

    /// Sets `ReadOnly`, raising `ReadOnlyChanged` when it changes.
    fn set_read_only(&mut self, read_only: bool) {
        if self.text_box_base_core().read_only != read_only {
            self.text_box_base_core_mut().read_only = read_only;
            self.on_read_only_changed(&mut EventCx::new(&mut EmptyEventArgs).from_class(self.class_name()));
        }
    }

    /// `Modified`.
    fn modified(&self) -> bool {
        self.text_box_base_core().modified
    }

    level_overridable! { base_text_box_base_mut;
        /// Raises `ReadOnlyChanged`.
        fn on_read_only_changed(EmptyEventArgs) => "OnReadOnlyChanged";
    }

    level_accessors! {
        /// `ReadOnlyChanged`.
        fn read_only_changed(EmptyEventArgs) => "OnReadOnlyChanged";
    }
}

// ── ListControl ─────────────────────────────────────────────────────────────────────────

/// The state of `ListControl` (WinForms: `ListBox`, `ComboBox`; here also `CheckedListBox`,
/// `Dropdown`).
#[derive(Default)]
pub struct ListControlCore {
    pub control: ControlCore,
    /// `SelectedIndex` (`None` = WinForms' `-1`).
    pub selected_index: Option<usize>,
    /// The items' display texts.
    pub items: Vec<String>,
    /// `DisplayMember` / `ValueMember` (bound lists).
    pub display_member: String,
    pub value_member: String,
}

deref_to!(ListControlCore => control: ControlCore);
plumbing!(HasListControlCore, ListControlCore, list_control_core, list_control_core_mut, ListControlLink, ListControl, base_list_control, base_list_control_mut);
lower!(ListControlCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for ListControlCore {
    const CHAIN: &'static [&'static str] = &["ListControl", "Control", "Component"];
}

/// The lists (WinForms `ListControl`).
pub trait ListControl: Control + ListControlLink {
    /// `SelectedIndex`.
    fn selected_index(&self) -> Option<usize> {
        self.list_control_core().selected_index
    }

    /// Sets `SelectedIndex`, raising `SelectionChanged` when it changes (source: code).
    fn set_selected_index(&mut self, index: Option<usize>) {
        let old = self.list_control_core().selected_index;
        if old != index {
            self.list_control_core_mut().selected_index = index;
            let mut args = SelectionChangedEventArgs::new(old, index, ChangeSource::Code);
            self.on_selection_changed(&mut EventCx::new(&mut args).from_class(self.class_name()));
        }
    }

    /// The items' display texts.
    fn items(&self) -> &[String] {
        &self.list_control_core().items
    }

    level_overridable! { base_list_control_mut;
        /// Raises `SelectionChanged` (WinForms `OnSelectedIndexChanged`).
        fn on_selection_changed(SelectionChangedEventArgs) => "OnSelectionChanged";
        /// Raises `SelectedValueChanged`.
        fn on_selected_value_changed(TextChangedEventArgs) => "OnSelectedValueChanged";
    }

    level_accessors! {
        /// `SelectionChanged`.
        fn selection_changed(SelectionChangedEventArgs) => "OnSelectionChanged";
        /// `SelectedValueChanged`.
        fn selected_value_changed(TextChangedEventArgs) => "OnSelectedValueChanged";
    }
}

// ── LabelBase ───────────────────────────────────────────────────────────────────────────

/// The state of `LabelBase` (WinForms `Label` and `LinkLabel`; here also `Badge`).
pub struct LabelBaseCore {
    pub control: ControlCore,
    /// `AutoEllipsis`.
    pub auto_ellipsis: bool,
    /// `TextAlign`.
    pub text_align: ContentAlignment,
}

impl Default for LabelBaseCore {
    /// WinForms' `Label`: not selectable, no tab stop.
    fn default() -> Self {
        let mut control = ControlCore::default();
        control.styles = styles_without(control.styles, ControlStyles::SELECTABLE);
        control.tab_stop = false;
        Self { control, auto_ellipsis: false, text_align: ContentAlignment::TopLeft }
    }
}

impl LabelBaseCore {
    /// A core showing `text`.
    pub fn with_text(text: &str) -> Self {
        let mut core = Self::default();
        core.control.text = text.to_string();
        core
    }
}

deref_to!(LabelBaseCore => control: ControlCore);
plumbing!(HasLabelBaseCore, LabelBaseCore, label_base_core, label_base_core_mut, LabelBaseLink, LabelBase, base_label_base, base_label_base_mut);
lower!(LabelBaseCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for LabelBaseCore {
    const CHAIN: &'static [&'static str] = &["LabelBase", "Control", "Component"];
}

/// The text displays (WinForms `Label`).
pub trait LabelBase: Control + LabelBaseLink {
    /// `AutoEllipsis`.
    fn auto_ellipsis(&self) -> bool {
        self.label_base_core().auto_ellipsis
    }
}

// ── ContainerBase ───────────────────────────────────────────────────────────────────────

/// The state of `ContainerBase` (WinForms `Panel`, `GroupBox`; here also `Card`, `Stack`, `Tabs`,
/// `Splitter`, `Accordion`).
pub struct ContainerBaseCore {
    pub scrollable: ScrollableControlCore,
    /// Which layout engine places the children.
    pub layout: LayoutKind,
}

impl Default for ContainerBaseCore {
    /// WinForms' `Panel`: not selectable, no tab stop, transparent back colour supported.
    fn default() -> Self {
        let mut scrollable = ScrollableControlCore::default();
        scrollable.control.styles = styles_without(scrollable.control.styles, ControlStyles::SELECTABLE) | ControlStyles::SUPPORTS_TRANSPARENT_BACK_COLOR;
        scrollable.control.tab_stop = false;
        Self { scrollable, layout: LayoutKind::None }
    }
}

deref_to!(ContainerBaseCore => scrollable: ScrollableControlCore);
plumbing!(HasContainerBaseCore, ContainerBaseCore, container_base_core, container_base_core_mut, ContainerBaseLink, ContainerBase, base_container_base, base_container_base_mut);
lower!(ContainerBaseCore:
    HasScrollableControlCore::scrollable_control_core / scrollable_control_core_mut -> ScrollableControlCore = scrollable;
    HasControlCore::control_core / control_core_mut -> ControlCore = scrollable.control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = scrollable.control.component;
);
impl Lineage for ContainerBaseCore {
    const CHAIN: &'static [&'static str] = &["ContainerBase", "ScrollableControl", "Control", "Component"];
}

/// The layout containers (WinForms `Panel`).
pub trait ContainerBase: ScrollableControl + ContainerBaseLink {
    /// The layout engine that places the children.
    fn layout_kind(&self) -> LayoutKind {
        self.container_base_core().layout
    }
}

// ── RangeBase ───────────────────────────────────────────────────────────────────────────

/// The state of `RangeBase` (a value in `minimum..=maximum`: `Slider`, `ProgressBar`,
/// `NumericField`; the design note's `ScrollBarBase`).
pub struct RangeBaseCore {
    pub control: ControlCore,
    pub minimum: f32,
    pub maximum: f32,
    pub value: f32,
    /// `SmallChange` (an arrow key) and `LargeChange` (Page Up/Down).
    pub small_change: f32,
    pub large_change: f32,
}

impl Default for RangeBaseCore {
    fn default() -> Self {
        Self { control: ControlCore::default(), minimum: 0.0, maximum: 100.0, value: 0.0, small_change: 1.0, large_change: 10.0 }
    }
}

deref_to!(RangeBaseCore => control: ControlCore);
plumbing!(HasRangeBaseCore, RangeBaseCore, range_base_core, range_base_core_mut, RangeBaseLink, RangeBase, base_range_base, base_range_base_mut);
lower!(RangeBaseCore:
    HasControlCore::control_core / control_core_mut -> ControlCore = control;
    HasComponentCore::component_core / component_core_mut -> ComponentCore = control.component;
);
impl Lineage for RangeBaseCore {
    const CHAIN: &'static [&'static str] = &["RangeBase", "Control", "Component"];
}

/// The value-in-a-range controls.
pub trait RangeBase: Control + RangeBaseLink {
    /// `Value`.
    fn value(&self) -> f32 {
        self.range_base_core().value
    }

    /// Sets `Value` (clamped to the range), raising `ValueChanged` when it changes (source: code).
    fn set_value(&mut self, value: f32) {
        let core = self.range_base_core();
        let value = value.clamp(core.minimum.min(core.maximum), core.maximum.max(core.minimum));
        let old = core.value;
        if old != value {
            self.range_base_core_mut().value = value;
            let mut args = NumericValueChangedEventArgs::new(old, value, ChangeSource::Code);
            self.on_value_changed(&mut EventCx::new(&mut args).from_class(self.class_name()));
        }
    }

    /// `Minimum`.
    fn minimum(&self) -> f32 {
        self.range_base_core().minimum
    }

    /// `Maximum`.
    fn maximum(&self) -> f32 {
        self.range_base_core().maximum
    }

    level_overridable! { base_range_base_mut;
        /// Raises `ValueChanged`.
        fn on_value_changed(NumericValueChangedEventArgs) => "OnValueChanged";
        /// Raises `Scroll`.
        fn on_scroll(ScrollEventArgs) => "OnScroll";
    }

    level_accessors! {
        /// `ValueChanged`.
        fn value_changed(NumericValueChangedEventArgs) => "OnValueChanged";
        /// `Scroll`.
        fn scroll(ScrollEventArgs) => "OnScroll";
    }
}

/// `ComponentCore` as the base of a non-visual component (`#[kubuno(extends = Component)]`).
impl Lineage for ComponentCore {
    const CHAIN: &'static [&'static str] = &["Component"];
}

/// Makes a level's core an object of its level: the abstract base a class extending the level
/// delegates to (`self.base_mut().on_click(e)` reaches the level's root behaviour, WinForms'
/// `base.OnClick(e)` in a class derived from `Control`). A core raises its events itself, with
/// the level's name as its class.
macro_rules! core_object {
    ($core:ty, $name:literal, [$($level:ident / $as_ref:ident / $as_mut:ident / $link:ident / $base:ident / $base_mut:ident),*]) => {
        impl super::ComponentLink for $core {
            fn as_any(&self) -> &dyn std::any::Any {
                self
            }
            fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
                self
            }
            fn as_component(&self) -> &dyn super::Component {
                self
            }
            fn as_component_mut(&mut self) -> &mut dyn super::Component {
                self
            }
            fn class_name(&self) -> &'static str {
                $name
            }
            fn class_chain(&self) -> &'static [&'static str] {
                <$core as Lineage>::CHAIN
            }
            fn base_component(&self) -> Option<&dyn super::Component> {
                None
            }
            fn base_component_mut(&mut self) -> Option<&mut dyn super::Component> {
                None
            }
            $(
                fn $as_ref(&self) -> Option<&dyn $level> {
                    Some(self)
                }
                fn $as_mut(&mut self) -> Option<&mut dyn $level> {
                    Some(self)
                }
            )*
        }
        impl super::Component for $core {}
        $(
            impl $link for $core {
                fn $base(&self) -> Option<&dyn $level> {
                    None
                }
                fn $base_mut(&mut self) -> Option<&mut dyn $level> {
                    None
                }
            }
            impl $level for $core {}
        )*
    };
}


core_object!(ComponentCore, "Component", []);
core_object!(ControlCore, "Control", [Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut]);
core_object!(ScrollableControlCore, "ScrollableControl", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ScrollableControl / as_scrollable_control / as_scrollable_control_mut / ScrollableControlLink / base_scrollable_control / base_scrollable_control_mut
]);
core_object!(ContainerControlCore, "ContainerControl", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ScrollableControl / as_scrollable_control / as_scrollable_control_mut / ScrollableControlLink / base_scrollable_control / base_scrollable_control_mut,
    ContainerControl / as_container_control / as_container_control_mut / ContainerControlLink / base_container_control / base_container_control_mut
]);
core_object!(UserControlCore, "UserControl", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ScrollableControl / as_scrollable_control / as_scrollable_control_mut / ScrollableControlLink / base_scrollable_control / base_scrollable_control_mut,
    ContainerControl / as_container_control / as_container_control_mut / ContainerControlLink / base_container_control / base_container_control_mut,
    UserControl / as_user_control / as_user_control_mut / UserControlLink / base_user_control / base_user_control_mut
]);
core_object!(ViewCore, "View", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ScrollableControl / as_scrollable_control / as_scrollable_control_mut / ScrollableControlLink / base_scrollable_control / base_scrollable_control_mut,
    ContainerControl / as_container_control / as_container_control_mut / ContainerControlLink / base_container_control / base_container_control_mut,
    View / as_view / as_view_mut / ViewLink / base_view / base_view_mut
]);
core_object!(ButtonBaseCore, "ButtonBase", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ButtonBase / as_button_base / as_button_base_mut / ButtonBaseLink / base_button_base / base_button_base_mut
]);
core_object!(TextBoxBaseCore, "TextBoxBase", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    TextBoxBase / as_text_box_base / as_text_box_base_mut / TextBoxBaseLink / base_text_box_base / base_text_box_base_mut
]);
core_object!(ListControlCore, "ListControl", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ListControl / as_list_control / as_list_control_mut / ListControlLink / base_list_control / base_list_control_mut
]);
core_object!(LabelBaseCore, "LabelBase", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    LabelBase / as_label_base / as_label_base_mut / LabelBaseLink / base_label_base / base_label_base_mut
]);
core_object!(ContainerBaseCore, "ContainerBase", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    ScrollableControl / as_scrollable_control / as_scrollable_control_mut / ScrollableControlLink / base_scrollable_control / base_scrollable_control_mut,
    ContainerBase / as_container_base / as_container_base_mut / ContainerBaseLink / base_container_base / base_container_base_mut
]);
core_object!(RangeBaseCore, "RangeBase", [
    Control / as_control / as_control_mut / ControlLink / base_control / base_control_mut,
    RangeBase / as_range_base / as_range_base_mut / RangeBaseLink / base_range_base / base_range_base_mut
]);
