//! The two levels of the ribbon family (`vskubuno/docs/RIBBON.md` §3): `RibbonControl`
//! (every element of a ribbon: tabs, groups, controls, Backstage entries) and `RibbonItem` (what
//! can stand in a group, a quick access toolbar or a menu). Both derive `Control`: every element
//! of a ribbon is a real control, selectable on the design surface and raising its own events,
//! though the ribbon lays it out (its `X`, `Y`, `Dock`, `Anchor`… are hidden).

use std::ops::{Deref, DerefMut};

use super::control::{Control, ControlCore, ControlLink, HasControlCore};
use super::{ComponentCore, HasComponentCore, Lineage};

// ── RibbonControl ───────────────────────────────────────────────────────────────────────

/// The state of `RibbonControl`: the ribbon properties every element shares.
#[derive(Default)]
pub struct RibbonControlCore {
    pub control: ControlCore,
    /// `Label` (a tab's or a group's `Header`).
    pub label: String,
    /// `SmallIcon`, `LargeIcon`.
    pub small_icon: String,
    pub large_icon: String,
    /// `KeyTip`.
    pub key_tip: String,
    /// `Command`: the `x:Name` of the `<Command>` it runs.
    pub command: String,
}

impl Deref for RibbonControlCore {
    type Target = ControlCore;
    fn deref(&self) -> &ControlCore {
        &self.control
    }
}

impl DerefMut for RibbonControlCore {
    fn deref_mut(&mut self) -> &mut ControlCore {
        &mut self.control
    }
}

/// Reaches the [`RibbonControlCore`] (generated by `#[derive(Component)]`; the cores implement it).
#[doc(hidden)]
pub trait HasRibbonControlCore {
    fn ribbon_control_core(&self) -> &RibbonControlCore;
    fn ribbon_control_core_mut(&mut self) -> &mut RibbonControlCore;
}

impl HasRibbonControlCore for RibbonControlCore {
    fn ribbon_control_core(&self) -> &RibbonControlCore {
        self
    }
    fn ribbon_control_core_mut(&mut self) -> &mut RibbonControlCore {
        self
    }
}

/// The base object a `RibbonControl` class delegates to (generated by `#[derive(Component)]`).
#[doc(hidden)]
pub trait RibbonControlLink: HasRibbonControlCore {
    fn base_ribbon_control(&self) -> Option<&dyn RibbonControl>;
    fn base_ribbon_control_mut(&mut self) -> Option<&mut dyn RibbonControl>;
}

impl HasControlCore for RibbonControlCore {
    fn control_core(&self) -> &ControlCore {
        &self.control
    }
    fn control_core_mut(&mut self) -> &mut ControlCore {
        &mut self.control
    }
}

impl HasComponentCore for RibbonControlCore {
    fn component_core(&self) -> &ComponentCore {
        &self.control.component
    }
    fn component_core_mut(&mut self) -> &mut ComponentCore {
        &mut self.control.component
    }
}

impl Lineage for RibbonControlCore {
    const CHAIN: &'static [&'static str] = &["RibbonControl", "Control", "Component"];
}

/// Every element of a ribbon.
pub trait RibbonControl: Control + RibbonControlLink {
    /// `Label` (a tab's or a group's header).
    fn label(&self) -> &str {
        &self.ribbon_control_core().label
    }

    fn set_label(&mut self, label: &str) {
        self.ribbon_control_core_mut().label = label.to_string();
    }

    /// `Command`: the `x:Name` of the `<Command>` it runs (empty for none).
    fn command(&self) -> &str {
        &self.ribbon_control_core().command
    }
}

// ── RibbonItem ──────────────────────────────────────────────────────────────────────────

/// The state of `RibbonItem`: what stands in a group, a quick access toolbar or a menu.
#[derive(Default)]
pub struct RibbonItemCore {
    pub ribbon: RibbonControlCore,
    /// `Checked` (a toggle, a check box, a menu item).
    pub checked: bool,
}

impl Deref for RibbonItemCore {
    type Target = RibbonControlCore;
    fn deref(&self) -> &RibbonControlCore {
        &self.ribbon
    }
}

impl DerefMut for RibbonItemCore {
    fn deref_mut(&mut self) -> &mut RibbonControlCore {
        &mut self.ribbon
    }
}

/// Reaches the [`RibbonItemCore`].
#[doc(hidden)]
pub trait HasRibbonItemCore {
    fn ribbon_item_core(&self) -> &RibbonItemCore;
    fn ribbon_item_core_mut(&mut self) -> &mut RibbonItemCore;
}

impl HasRibbonItemCore for RibbonItemCore {
    fn ribbon_item_core(&self) -> &RibbonItemCore {
        self
    }
    fn ribbon_item_core_mut(&mut self) -> &mut RibbonItemCore {
        self
    }
}

/// The base object a `RibbonItem` class delegates to.
#[doc(hidden)]
pub trait RibbonItemLink: HasRibbonItemCore {
    fn base_ribbon_item(&self) -> Option<&dyn RibbonItem>;
    fn base_ribbon_item_mut(&mut self) -> Option<&mut dyn RibbonItem>;
}

impl HasRibbonControlCore for RibbonItemCore {
    fn ribbon_control_core(&self) -> &RibbonControlCore {
        &self.ribbon
    }
    fn ribbon_control_core_mut(&mut self) -> &mut RibbonControlCore {
        &mut self.ribbon
    }
}

impl HasControlCore for RibbonItemCore {
    fn control_core(&self) -> &ControlCore {
        &self.ribbon.control
    }
    fn control_core_mut(&mut self) -> &mut ControlCore {
        &mut self.ribbon.control
    }
}

impl HasComponentCore for RibbonItemCore {
    fn component_core(&self) -> &ComponentCore {
        &self.ribbon.control.component
    }
    fn component_core_mut(&mut self) -> &mut ComponentCore {
        &mut self.ribbon.control.component
    }
}

impl Lineage for RibbonItemCore {
    const CHAIN: &'static [&'static str] = &["RibbonItem", "RibbonControl", "Control", "Component"];
}

/// What can stand in a group, a quick access toolbar or a menu.
pub trait RibbonItem: RibbonControl + RibbonItemLink {
    /// `Checked`.
    fn is_checked(&self) -> bool {
        self.ribbon_item_core().checked
    }

    fn set_checked(&mut self, on: bool) {
        self.ribbon_item_core_mut().checked = on;
    }
}

// ── The cores as objects of their levels (the abstract bases) ─────────────────────────

macro_rules! ribbon_core_object {
    ($core:ty, $name:literal, item: $item:tt) => {
        impl super::ComponentLink for $core {
            fn as_any(&self) -> &dyn std::any::Any {
                self
            }
            fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
                self
            }
            fn as_component(&self) -> &dyn super::Component {
                self
            }
            fn as_component_mut(&mut self) -> &mut dyn super::Component {
                self
            }
            fn class_name(&self) -> &'static str {
                $name
            }
            fn class_chain(&self) -> &'static [&'static str] {
                <$core as Lineage>::CHAIN
            }
            fn base_component(&self) -> Option<&dyn super::Component> {
                None
            }
            fn base_component_mut(&mut self) -> Option<&mut dyn super::Component> {
                None
            }
            fn as_control(&self) -> Option<&dyn Control> {
                Some(self)
            }
            fn as_control_mut(&mut self) -> Option<&mut dyn Control> {
                Some(self)
            }
            fn as_ribbon_control(&self) -> Option<&dyn RibbonControl> {
                Some(self)
            }
            fn as_ribbon_control_mut(&mut self) -> Option<&mut dyn RibbonControl> {
                Some(self)
            }
            ribbon_core_object!(@item $item);
        }
        impl super::Component for $core {}
        impl ControlLink for $core {
            fn base_control(&self) -> Option<&dyn Control> {
                None
            }
            fn base_control_mut(&mut self) -> Option<&mut dyn Control> {
                None
            }
        }
        impl Control for $core {}
        impl RibbonControlLink for $core {
            fn base_ribbon_control(&self) -> Option<&dyn RibbonControl> {
                None
            }
            fn base_ribbon_control_mut(&mut self) -> Option<&mut dyn RibbonControl> {
                None
            }
        }
        impl RibbonControl for $core {}
    };
    (@item true) => {
        fn as_ribbon_item(&self) -> Option<&dyn RibbonItem> {
            Some(self)
        }
        fn as_ribbon_item_mut(&mut self) -> Option<&mut dyn RibbonItem> {
            Some(self)
        }
    };
    (@item false) => {};
}

ribbon_core_object!(RibbonControlCore, "RibbonControl", item: false);
ribbon_core_object!(RibbonItemCore, "RibbonItem", item: true);

impl RibbonItemLink for RibbonItemCore {
    fn base_ribbon_item(&self) -> Option<&dyn RibbonItem> {
        None
    }
    fn base_ribbon_item_mut(&mut self) -> Option<&mut dyn RibbonItem> {
        None
    }
}

impl RibbonItem for RibbonItemCore {}
