//! Continuous daemon mode: keep the folder in sync automatically.
//!
//! Two triggers feed a single sync runner:
//!   - a filesystem watcher (notify: inotify / FSEvents / ReadDirectoryChangesW)
//!     fires on local changes — debounced so an editor's burst of writes maps to
//!     one sync;
//!   - a periodic timer polls the server for remote changes (the daemon is the
//!     client; it pulls rather than being pushed to).
//!
//! After each sync we drain the event channel to swallow the events generated by
//! our own downloads, so a pull doesn't trigger an endless re-sync loop.

use std::sync::mpsc::{channel, RecvTimeoutError};
use std::time::Duration;

use anyhow::Result;
use notify::{RecursiveMode, Watcher};

use crate::{
    api::Api,
    config::{db_path, Config, Creds},
    engine, push,
    store::Store,
};

pub fn watch(interval_secs: u64) -> Result<()> {
    let cfg = Config::load()?;
    let mut api = Api::new(cfg.server_url.clone(), Creds::load()?);
    let store = Store::open(&db_path()?)?;
    std::fs::create_dir_all(&cfg.sync_root)?;

    // Catch up once before watching.
    run_once(&mut api, &store, &cfg);

    let (tx, rx) = channel();

    // Local filesystem changes.
    let tx_fs = tx.clone();
    let mut watcher = notify::recommended_watcher(move |res: notify::Result<notify::Event>| {
        if res.is_ok() {
            let _ = tx_fs.send(());
        }
    })?;
    watcher.watch(&cfg.sync_root, RecursiveMode::Recursive)?;

    // Real-time remote changes via the core WebSocket (poll below is the fallback).
    crate::ws::spawn_listener(cfg.server_url.clone(), tx.clone());

    println!(
        "Surveillance de {} — temps réel (WebSocket) + poll serveur toutes les {interval_secs}s. Ctrl-C pour arrêter.",
        cfg.sync_root.display()
    );

    let debounce = Duration::from_millis(1500);
    let poll = Duration::from_secs(interval_secs.max(1));
    loop {
        match rx.recv_timeout(poll) {
            // Local change(s): wait for the write burst to settle, then sync.
            Ok(()) => {
                while rx.recv_timeout(debounce).is_ok() {}
                run_once(&mut api, &store, &cfg);
            }
            // Periodic remote poll.
            Err(RecvTimeoutError::Timeout) => run_once(&mut api, &store, &cfg),
            Err(RecvTimeoutError::Disconnected) => break,
        }
        // Discard events caused by our own writes during the sync above.
        while rx.try_recv().is_ok() {}
    }
    Ok(())
}

/// One push+pull cycle. Errors (e.g. offline) are logged, never fatal — the
/// daemon keeps running and retries on the next trigger.
fn run_once(api: &mut Api, store: &Store, cfg: &Config) {
    match push::push(api, store, cfg) {
        Ok(p) if p.uploaded + p.modified + p.deleted + p.conflicts > 0 => println!(
            "  ↑ {} créé(s), {} modifié(s), {} supprimé(s), {} conflit(s)",
            p.uploaded, p.modified, p.deleted, p.conflicts
        ),
        Ok(_) => {}
        Err(e) => eprintln!("  push : {e}"),
    }
    match engine::sync(api, store, cfg) {
        Ok(s) if s.downloaded + s.folders + s.deleted > 0 => println!(
            "  ↓ {} téléchargé(s), {} dossier(s), {} supprimé(s)",
            s.downloaded, s.folders, s.deleted
        ),
        Ok(_) => {}
        Err(e) => eprintln!("  pull : {e}"),
    }
}
