//! Embeds the module brand logos THE WEB serves (moved from the shell's `build.rs`, see `src/logos.rs`).

use std::path::{Path, PathBuf};

/// Where the web host keeps the module brand logos it serves (`/<id>-logo.png`): `core/frontend/public`.
const WEB_LOGOS_ENV: &str = "KUBUNO_WEB_LOGOS_DIR";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    web_logos();
}

/// Embeds the very files of `core/frontend/public` the core answers `/api/v1/modules`' `logo_url` with, as the
/// launcher's fallback before its first download. Generated at every build from those files, never copied by
/// hand, so the desktop cannot drift from the web.
///
/// The folder is `KUBUNO_WEB_LOGOS_DIR` when set, else the `core/frontend/public` of the polyrepo workspace
/// this checkout sits in. A checkout without the core next to it still builds: the table is empty and the
/// launcher falls back to the server's logos, then to the modules' glyphs.
fn web_logos() {
    println!("cargo:rerun-if-env-changed={WEB_LOGOS_ENV}");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo")).join("web_logos.rs");
    let dir = std::env::var_os(WEB_LOGOS_ENV).map(PathBuf::from).or_else(|| {
        let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR")?);
        manifest.ancestors().map(|a| a.join("core").join("frontend").join("public")).find(|p| p.is_dir())
    });
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    match &dir {
        Some(dir) => {
            println!("cargo:rerun-if-changed={}", dir.display());
            if let Ok(entries) = std::fs::read_dir(dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    let Some(name) = path.file_name().and_then(|n| n.to_str()).map(str::to_string) else { continue };
                    if is_module_logo(&name) && path.is_file() {
                        println!("cargo:rerun-if-changed={}", path.display());
                        files.push((name, path));
                    }
                }
            }
            if files.is_empty() {
                println!("cargo:warning=no module logo found in {}: the launcher has no built-in fallback", dir.display());
            }
        }
        None => println!("cargo:warning=core/frontend/public not found (set {WEB_LOGOS_ENV}): the launcher has no built-in logo fallback"),
    }
    files.sort();
    let mut code = String::from(
        "// Generated by build.rs from the web host's module logos: do not edit.\n\
         /// `(file name as the web serves it, bytes)`, sorted by name.\n\
         pub static WEB_LOGOS: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &files {
        code.push_str(&format!("    ({name:?}, include_bytes!({:?})),\n", absolute(path)));
    }
    code.push_str("];\n");
    std::fs::write(&out, code).expect("unable to write web_logos.rs");
}

/// A module or sub-app brand logo of the web host: `<id>-logo.png` / `<id>-logo.svg`. The product's own marks
/// (`kubuno-logo.png`, `kubuno-logo-white.svg`) are not modules.
fn is_module_logo(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    let stem = lower.strip_suffix("-logo.png").or_else(|| lower.strip_suffix("-logo.svg"));
    matches!(stem, Some(s) if !s.is_empty() && s != "kubuno" && s.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_'))
}

fn absolute(path: &Path) -> String {
    // Not `canonicalize`: on Windows it yields a `\\?\` path, which is needless here.
    std::path::absolute(path).unwrap_or_else(|_| path.to_path_buf()).to_string_lossy().into_owned()
}
