//! French user documentation of the registry (`vskubuno/docs/DESIGNER.md` section 11): the same
//! short, user-facing sentences as each component's, property's and event's English `doc`, shown
//! by Visual Studio's Properties window and Toolbox when Visual Studio runs in French. Keyed like
//! [`key`]: `"Button"` for a component, `"Button.Text"` for a property or an event. Keep in step
//! with the English `doc` strings (a test checks every registry member has an entry).

/// The key of a component (`member` = `None`) or of one of its properties/events.
pub fn key(component: &str, member: Option<&str>) -> String {
    match member {
        Some(m) => format!("{component}.{m}"),
        None => component.to_string(),
    }
}

/// The French documentation of `component`'s property `property`: the component's own entry, else
/// the entry of the level it inherits it from (`Control.BackColor`, `View.Title`…).
pub fn property_french(component: &str, property: &str, level: Option<&str>) -> Option<&'static str> {
    french(&key(component, Some(property)))
        .or_else(|| french(&key(level?, Some(property))))
        // The icon options every element with an icon takes (`common::ICON_OPTION_PROPERTIES`).
        .or_else(|| super::common::ICON_OPTION_PROPERTIES.iter().any(|p| p.name == property).then(|| french(&key("Icon", Some(property)))).flatten())
}

/// The French documentation of the properties the levels of the control hierarchy declare
/// (`registry::common`), keyed `Level.Property`.
fn level_french(key: &str) -> Option<&'static str> {
    Some(match key {
        "Control.AccessibleName" => "Nom annoncé par les lecteurs d'écran pour le contrôle. Laisser vide pour utiliser son texte.",
        "Control.AccessibleDescription" => "Description annoncée par les lecteurs d'écran pour le contrôle.",
        "Control.AccessibleRole" => "Type d'élément annoncé par les lecteurs d'écran. Default utilise le type du contrôle lui-même.",
        "Control.BackColor" => "Couleur de fond : une couleur du thème (elle suit les thèmes clair et sombre) ou une couleur de votre choix. Laisser vide pour prendre celle du parent.",
        "Control.ForeColor" => "Couleur du texte : une couleur du thème (elle suit les thèmes clair et sombre) ou une couleur de votre choix. Laisser vide pour prendre celle du parent.",
        "Control.Font" => "Police du texte : famille, taille et style. Laisser vide pour prendre celle du parent.",
        "Control.Cursor" => "Pointeur de la souris affiché au-dessus du contrôle.",
        "Control.RightToLeft" => "Affiche le texte de droite à gauche, pour des langues comme l'arabe ou l'hébreu. Inherit reprend le réglage du parent.",
        "Control.BackgroundImage" => "Image peinte derrière le contenu du contrôle : le chemin d'un fichier image, relatif à la vue.",
        "Control.BackgroundImageLayout" => "Façon dont l'image de fond remplit le contrôle.",
        "Control.Enabled" => "Indique si le contrôle réagit à la souris et au clavier. Un contrôle désactivé est grisé, avec tout ce qu'il contient.",
        "Control.Visible" => "Indique si le contrôle est affiché quand l'application s'exécute. Le concepteur l'affiche toujours.",
        "Control.TabIndex" => "Position du contrôle dans l'ordre suivi par la touche Tab, parmi les contrôles du même conteneur.",
        "Control.TabStop" => "Indique si la touche Tab s'arrête sur le contrôle.",
        "Control.ContextMenu" => "Menu affiché quand on clique sur le contrôle avec le bouton droit : le nom d'un ContextMenu de la vue.",
        "Control.AllowDrop" => "Indique si des données (fichiers, texte…) peuvent être glissées sur le contrôle : il déclenche alors DragEnter, DragOver, DragLeave et DragDrop.",
        "Control.UseWaitCursor" => "Affiche le pointeur d'attente au-dessus du contrôle et de tout ce qu'il contient.",
        "Control.ToolTip" => "Texte de l'info-bulle affichée quand la souris s'arrête sur le contrôle.",
        "Control.Tag" => "Texte libre conservé avec le contrôle, pour votre propre code.",
        "Control.Locked" => "Empêche de déplacer ou de redimensionner le contrôle dans le concepteur.",
        "Control.GenerateMember" => "Indique si votre code peut retrouver le contrôle par son nom.",
        "Control.Modifiers" => "Qui peut utiliser le contrôle depuis du code extérieur à la vue ; Protected ou Public permet aussi aux vues qui héritent de celle-ci de le modifier.",
        "Control.CausesValidation" => "Indique si donner le focus à ce contrôle valide d'abord le contrôle qui l'avait.",
        "Control.X" => "Distance depuis le bord gauche du panneau parent, en pixels.",
        "Control.Y" => "Distance depuis le bord supérieur du panneau parent, en pixels.",
        "Control.Width" => "Largeur de l'élément, en pixels.",
        "Control.Height" => "Hauteur de l'élément, en pixels.",
        "Control.Dock" => "Bord du panneau parent auquel l'élément est ancré, ou Fill pour occuper l'espace restant.",
        "Control.Anchor" => "Bords du panneau parent auxquels l'élément reste attaché quand il est redimensionné, par exemple Top, Left.",
        "Control.Margin" => "Espace laissé autour du contrôle par le conteneur qui l'aligne avec d'autres : gauche, haut, droite, bas, en pixels.",
        "Control.Padding" => "Espace à l'intérieur du contrôle, autour de son contenu : gauche, haut, droite, bas, en pixels.",
        "Control.MinimumSize" => "Plus petite taille du contrôle : largeur, hauteur en pixels (0 signifie aucune limite).",
        "Control.MaximumSize" => "Plus grande taille du contrôle : largeur, hauteur en pixels (0 signifie aucune limite).",
        "Control.AutoSize" => "Dimensionne le contrôle selon son contenu au lieu de sa largeur et de sa hauteur.",
        "Control.AutoSizeMode" => "Avec AutoSize, indique si le contrôle peut aussi devenir plus petit que sa largeur et sa hauteur.",
        "Control.TitleBar.Region" => "Sur un contrôle du premier niveau de la vue : le place dans la barre de titre de la fenêtre, à gauche, au centre ou à droite (onglets, champ de recherche, avatar, bouton de menu).",
        "Control.TitleBar.Drag" => "Fait du contrôle une zone qui déplace la fenêtre quand on la fait glisser : dans la barre de titre, ou n'importe où dans une fenêtre sans bordure.",
        "Control.ActionBar.Region" => "Sur un contrôle du premier niveau de la vue : le place dans la barre d'actions de la fenêtre, le pied d'un dialogue (boutons à droite, case à cocher ou lien à gauche).",
        "Control.Stack.Fill" => "Sur un enfant d'une Stack : il prend la place que les autres enfants laissent le long du flux.",
        "Control.TableLayoutPanel.Row" => "Sur un enfant d'un TableLayoutPanel : sa ligne (0 est la première) ; vide pour la prochaine cellule libre.",
        "Control.TableLayoutPanel.Column" => "Sur un enfant d'un TableLayoutPanel : sa colonne (0 est la première) ; vide pour la prochaine cellule libre.",
        "Control.TableLayoutPanel.RowSpan" => "Sur un enfant d'un TableLayoutPanel : le nombre de lignes qu'il occupe.",
        "Control.TableLayoutPanel.ColumnSpan" => "Sur un enfant d'un TableLayoutPanel : le nombre de colonnes qu'il occupe.",
        "ButtonBase.TextAlign" => "Position du texte dans le contrôle.",
        "ButtonBase.Image" => "Image affichée sur le contrôle : le chemin d'un fichier image, relatif à la vue.",
        "ButtonBase.ImageAlign" => "Position de l'image ou de l'icône dans le contrôle (avec TextImageRelation Overlay ; sinon TextAlign place l'icône et le texte ensemble).",
        "ButtonBase.TextImageRelation" => "Place de l'image ou de l'icône par rapport au texte. Une icône se place avant le texte quand ce réglage n'est pas défini.",
        "ButtonBase.IconSpacing" => "Espace entre l'icône (ou l'image) et le texte, en pixels. Laisser vide pour l'espacement propre au bouton.",
        "Icon.IconSize" => "Taille de l'icône : Small (16), Medium (20), Large (24), XLarge (32), un nombre de pixels, ou largeur, hauteur. Laisser vide pour la taille propre au contrôle.",
        "Icon.IconScaling" => "Façon dont une image non carrée remplit la place de l'icône : Fit la montre entière, Fill couvre la place, Stretch l'ajuste exactement, None garde sa propre taille.",
        "Icon.IconColor" => "Couleur de l'icône, chaque pixel recoloré (pour une icône d'une seule couleur). Laisser vide pour la couleur du contrôle : un glyphe et un SVG dessiné en currentColor la suivent, ainsi que le thème ; une autre image garde ses couleurs.",
        "ButtonBase.UseMnemonic" => "Fait d'une lettre précédée d'une esperluette (&Enregistrer) le raccourci clavier du contrôle : Alt et cette lettre l'activent, et la lettre est soulignée tant qu'Alt est enfoncée.",
        "ButtonBase.UseVisualStyleBackColor" => "Peint le bouton aux couleurs du thème, sans tenir compte de BackColor. Mettre à false pour utiliser BackColor.",
        "LabelBase.TextAlign" => "Position du texte dans le contrôle.",
        "LabelBase.UseMnemonic" => "Fait d'une lettre précédée d'une esperluette (&Nom) un raccourci clavier : Alt et cette lettre passent au contrôle suivant dans l'ordre de tabulation.",
        "LabelBase.BorderStyle" => "Bordure dessinée autour du contrôle.",
        "LabelBase.Image" => "Image affichée dans le contrôle : le chemin d'un fichier image, relatif à la vue.",
        "LabelBase.ImageAlign" => "Position de l'image dans le contrôle.",
        "TextBoxBase.ReadOnly" => "Permet de sélectionner et de copier le texte, mais pas de le modifier.",
        "TextBoxBase.MaxLength" => "Nombre maximal de caractères pouvant être saisis.",
        "TextBoxBase.AcceptsTab" => "Insère une tabulation quand on appuie sur Tab, au lieu de passer au contrôle suivant.",
        "TextBoxBase.PasswordChar" => "Caractère affiché à la place de chaque caractère saisi, pour un mot de passe. Laisser vide pour afficher le texte.",
        "TextBoxBase.CharacterCasing" => "Met les lettres saisies en majuscules ou en minuscules.",
        "TextBoxBase.HideSelection" => "Masque le texte sélectionné tant que le champ n'a pas le focus.",
        "TextBoxBase.TextAlign" => "Alignement du texte dans le champ.",
        "ListControl.Sorted" => "Affiche les éléments dans l'ordre alphabétique.",
        "ScrollableControl.AutoScroll" => "Affiche des barres de défilement quand le contenu est plus grand que le contrôle.",
        "ContainerBase.BorderStyle" => "Bordure dessinée autour du conteneur.",
        "View.Title" => "Texte de la barre de titre de la fenêtre, aussi affiché dans la barre des tâches.",
        "View.Icon" => "Icône de la fenêtre, dans sa barre de titre, la barre des tâches et Alt+Tab : un nom du jeu d'icônes Kubuno, ou un fichier image (.ico, .svg, .png…) relatif à la vue.",
        "View.StartPosition" => "Emplacement d'ouverture de la fenêtre. Manual utilise les X et Y de la vue.",
        "View.FormBorderStyle" => "Bordure et barre de titre de la fenêtre, et possibilité de la redimensionner.",
        "View.ControlBox" => "Affiche les boutons de la barre de titre (réduire, agrandir, fermer) et le menu de la fenêtre.",
        "View.MinimizeBox" => "Affiche le bouton Réduire de la barre de titre.",
        "View.MaximizeBox" => "Affiche le bouton Agrandir de la barre de titre.",
        "View.ShowInTaskbar" => "Affiche la fenêtre dans la barre des tâches de Windows.",
        "View.TopMost" => "Garde la fenêtre au-dessus des autres fenêtres.",
        "View.Opacity" => "Opacité de la fenêtre, en pourcentage : 100 est opaque, une valeur plus faible laisse voir ce qui est derrière.",
        "View.WindowState" => "Indique si la fenêtre s'ouvre normale, réduite ou agrandie.",
        "View.AcceptButton" => "Bouton cliqué quand on appuie sur Entrée dans la fenêtre : le nom d'un bouton de la vue.",
        "View.CancelButton" => "Bouton cliqué quand on appuie sur Échap dans la fenêtre : le nom d'un bouton de la vue.",
        "View.KeyPreview" => "Permet à la vue de recevoir les événements clavier avant le contrôle qui a le focus.",
        "View.AutoScroll" => "Affiche des barres de défilement quand la vue est plus grande que la fenêtre.",
        "View.WindowKind" => "Type de fenêtre : fenêtre principale, dialogue modal, fenêtre d'outils, écran de démarrage, menu volant ou document MDI. Il prérègle la bordure, les boutons de la barre de titre et l'emplacement d'ouverture ; une propriété réglée sur la vue l'emporte.",
        "View.ShowIcon" => "Affiche l'icône de la fenêtre dans sa barre de titre.",
        "View.HelpButton" => "Affiche un bouton d'aide dans la barre de titre ; un clic déclenche HelpButtonClicked.",
        "View.SizeGripStyle" => "Poignée de redimensionnement dans le coin inférieur droit de la fenêtre. Auto l'affiche quand la fenêtre peut être redimensionnée.",
        "View.TransparencyKey" => "Couleur transparente dans la fenêtre : ce qui est derrière apparaît et reçoit les clics.",
        "View.ResizeBorder" => "Permet de redimensionner par ses bords une fenêtre sans bordure (FormBorderStyle None).",
        "View.RightToLeftLayout" => "Met la fenêtre en miroir pour les langues écrites de droite à gauche : les boutons de la barre de titre passent à gauche.",
        "View.IsMdiContainer" => "Fait de la fenêtre le parent de documents MDI : les fenêtres enfants s'ouvrent dans sa zone cliente.",
        "View.SplashDuration" => "Pour un écran de démarrage : durée d'affichage, en millisecondes, avant qu'il ne se ferme (0 le garde ouvert).",
        "View.Chrome" => "Qui dessine la barre de titre : celle de Kubuno, celle de Windows, ou personne (la vue dessine la sienne). Default reprend le réglage de l'application.",
        "View.Backdrop" => "Matière de Windows 11 derrière la fenêtre : Mica, Mica Alt ou Acrylique. Elle apparaît là où la vue laisse la fenêtre transparente.",
        "View.CornerPreference" => "Coins de la fenêtre, prédéfinis : Round (8 pixels, ceux de Windows 11), RoundSmall (4) ou DoNotRound (coins droits). Default arrondit à 8 une fenêtre qui a une barre de titre et laisse droits ceux d'une fenêtre sans bordure (un écran de démarrage est arrondi). CornerRadius, s'il est défini, l'emporte.",
        "View.CornerRadius" => "Rayon des coins de la fenêtre, en pixels (8 par défaut, comme Windows 11 ; 0 pour des coins droits). Une fenêtre agrandie, ancrée ou en plein écran a toujours des coins droits. Sans lui, CornerPreference décide (une fenêtre sans bordure a des coins droits). Sur un flyout, un rayon supérieur à 0 l'affiche comme un panneau flottant sur un flou de ce qui est derrière lui, avec une ombre portée (le lanceur d'applications du web), teinté par la BackColor translucide de la vue.",
        "View.BorderColor" => "Couleur de la fine bordure de la fenêtre. Laisser vide pour prendre celle de la barre de titre.",
        "View.AccentColor" => "Couleur d'accent de cette fenêtre : sa barre de titre et ses contrôles à la couleur d'accent. Laisser vide pour prendre celle du thème.",
        "View.TitleBarHeight" => "Hauteur de la barre de titre, en pixels (50 par défaut, 32 pour une fenêtre d'outils).",
        "View.TitleBarPadding" => "Espace entre les bords gauche et droit de la fenêtre et ce que la barre de titre porte à ses extrémités (son icône ou ses contrôles de gauche, ses propres boutons), en pixels (16 par défaut, 8 pour une fenêtre d'outils).",
        "View.TitleBarBackground" => "Couleur de la barre de titre. Laisser vide pour prendre la couleur d'accent.",
        "View.TitleBarForeground" => "Couleur du titre, de l'icône et des boutons de la barre de titre. Laisser vide pour du blanc sur l'accent.",
        "View.Subtitle" => "Second texte, plus petit, affiché après le titre dans la barre de titre.",
        "View.TitleAlignment" => "Position du titre dans la barre de titre.",
        "View.ShowTitle" => "Affiche le titre dans la barre de titre (à masquer quand elle contient des onglets ou un champ de recherche).",
        "View.CaptionButtonStyle" => "Aspect des boutons de la barre de titre : les boutons arrondis de Kubuno, ou les boutons larges de Windows avec un bouton Fermer rouge.",
        "View.CaptionButtons" => "Vos propres boutons dans la barre de titre, à côté de Réduire : id:Icône:Info-bulle, séparés par des points-virgules (pin:Pin:Garder au premier plan; settings:Settings2:Paramètres). Un clic déclenche CaptionButtonClick.",
        "View.ExtendContentIntoTitleBar" => "Laisse la vue dessiner sous la barre de titre : le titre et les boutons sont dessinés par-dessus.",
        "View.ShowSearch" => "Affiche le bouton de recherche (une loupe) avant les autres boutons de l'en-tête dans la barre de titre ; un clic déclenche SearchClicked.",
        "View.ShowNotifications" => "Affiche la cloche des notifications dans la barre de titre, avec le compteur UnreadCount ; un clic déclenche NotificationsClicked.",
        "View.ShowSettings" => "Affiche le bouton des paramètres dans la barre de titre ; un clic déclenche SettingsClicked.",
        "View.ShowHelp" => "Affiche le bouton d'aide de l'en-tête dans la barre de titre ; un clic déclenche HelpClicked.",
        "View.ShowWaffle" => "Affiche le lanceur d'applications (le gaufrier) dans la barre de titre ; il ouvre le lanceur d'applications.",
        "View.ShowAccount" => "Affiche l'avatar du compte dans la barre de titre ; il ouvre le panneau du compte.",
        "View.UnreadCount" => "Nombre de notifications non lues affiché sur la cloche (0 n'affiche aucun compteur).",
        _ => return None,
    })
}

/// The French documentation for [`key`], if any.
pub fn french(key: &str) -> Option<&'static str> {
    if let Some(level) = level_french(key) {
        return Some(level);
    }
    // The ribbon family keeps its French documentation beside its declarations.
    if let Some(ribbon) = super::families::ribbon::french(key) {
        return Some(ribbon);
    }
    // So does the menu family (and the menu components).
    if let Some(menus) = super::families::menus::french(key) {
        return Some(menus);
    }
    Some(match key {
        "Accordion" => "Liste de sections qui peuvent être développées ou réduites. Ajoutez les sections comme éléments AccordionSection enfants.",
        "Accordion.Size" => "Espacement des en-têtes et du contenu des sections.",
        "AccordionSection" => "Section d'un accordéon, qui peut être développée ou réduite.",
        "AccordionSection.Disabled" => "Affiche la section grisée et la garde réduite.",
        "AccordionSection.Header" => "Titre de la section.",
        "AccordionSection.OnToggled" => "Se produit quand la section est développée ou réduite.",
        "AccordionSection.Open" => "Indique si la section est développée.",
        "Badge" => "Petite pastille affichant un nombre ou un état.",
        "Badge.Dot" => "Affiche une pastille d'état colorée avant le texte.",
        "Badge.MaxWidth" => "Largeur maximale en pixels avant que le texte soit raccourci. 0 signifie aucune limite.",
        "Badge.Size" => "Taille de la pastille.",
        "Badge.Solid" => "Remplit la pastille avec la couleur saturée de sa variante, son texte en blanc : un compteur posé sur un bouton (notifications non lues).",
        "Badge.Text" => "Texte de la pastille.",
        "Badge.Variant" => "Couleur de la pastille.",
        "Breadcrumb" => "Fil d'Ariane de navigation. Ajoutez les segments comme éléments BreadcrumbItem enfants.",
        "Breadcrumb.RootChevron" => "Réserve la place d'une icône d'accueil avant le premier segment.",
        "BreadcrumbItem" => "Segment d'un fil d'Ariane.",
        "BreadcrumbItem.OnClick" => "Se produit quand le segment est cliqué.",
        "BreadcrumbItem.Text" => "Texte du segment.",
        "Button" => "Bouton poussoir.",
        "Button.Icon" => "Icône affichée avant le texte : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "Button.Loading" => "Affiche un indicateur de chargement à la place du contenu et désactive le bouton.",
        "Button.OnClick" => "Se produit quand le bouton est cliqué ou activé avec Espace ou Entrée.",
        "Button.Size" => "Hauteur et marges horizontales du bouton.",
        "Button.Text" => "Texte affiché sur le bouton.",
        "Button.Variant" => "Style visuel : plein, contour, fantôme, texte seul ou danger.",
        "Callout" => "Bandeau de message : information, succès, avertissement ou erreur.",
        "Callout.ActionLabel" => "Texte d'un bouton d'action dans le bandeau. Laisser vide pour aucun bouton.",
        "Callout.Body" => "Texte du message.",
        "Callout.Dismissible" => "Affiche un bouton pour fermer le bandeau.",
        "Callout.OnAction" => "Se produit quand le bouton d'action est cliqué.",
        "Callout.OnDismiss" => "Se produit quand le bandeau est fermé.",
        "Callout.ShowIcon" => "Affiche l'icône du type de message.",
        "Callout.Title" => "Titre en gras affiché au-dessus du message. Laisser vide pour aucun titre.",
        "Callout.Variant" => "Type de message, qui détermine la couleur et l'icône.",
        "Card" => "Carte avec un titre facultatif, qui contient un élément enfant.",
        "Card.Dense" => "Utilise des espacements réduits et un titre plus petit.",
        "Card.Flush" => "Supprime les marges intérieures, pour qu'un tableau ou une liste touche les bords de la carte.",
        "Card.Subtitle" => "Texte secondaire affiché sous le titre.",
        "Card.Surface" => "Fond de la carte : standard, calque, ou surélevé avec une ombre.",
        "Card.Title" => "Titre affiché dans l'en-tête de la carte. Laisser vide pour masquer l'en-tête.",
        "CheckBox" => "Case à cocher.",
        "CheckBox.AutoCheck" => "Coche ou décoche la case quand on clique dessus.",
        "CheckBox.CheckState" => "État de la case, y compris l'état indéterminé d'une case à trois états.",
        "CheckBox.ThreeState" => "Permet aussi d'obtenir l'état indéterminé en cliquant.",
        "CheckBox.Checked" => "Indique si la case est cochée.",
        "CheckBox.Description" => "Texte secondaire affiché sous le libellé.",
        "CheckBox.OnCheckedChanged" => "Se produit quand la case est cochée ou décochée.",
        "CheckBox.Text" => "Texte affiché à côté de la case.",
        "CheckedListBox" => "Liste d'éléments, chacun avec une case à cocher.",
        "CheckedListBox.CheckOnClick" => "Coche ou décoche un élément d'un simple clic n'importe où dessus.",
        "CheckedListBox.ItemsSource" => "Liaison vers la liste des éléments à afficher, à la place des éléments Item.",
        "CheckedListBox.OnCheckedChanged" => "Se produit quand un élément est coché ou décoché.",
        "CheckedListBox.OnSelectionChanged" => "Se produit quand l'élément sélectionné change.",
        "CheckedListBox.SelectedIndex" => "Index de l'élément sélectionné, à partir de 0. -1 signifie aucun.",
        "ColorField" => "Pastille de couleur qui ouvre un sélecteur de couleur.",
        "ColorField.Color" => "Couleur affichée, au format #rrggbb.",
        "ColorField.OnClick" => "Se produit quand la pastille est cliquée, ce qui ouvre ou ferme son sélecteur de couleur.",
        "ColorField.OnValueChanged" => "Se produit quand la couleur est modifiée dans le sélecteur.",
        "GradientField" => "Pastille de dégradé qui ouvre un sélecteur de dégradé.",
        "GradientField.Value" => "Dégradé affiché, au format CSS linear-gradient(...) ou radial-gradient(circle, ...).",
        "GradientField.OnValueChanged" => "Se produit quand le dégradé est modifié dans le sélecteur.",
        "Column" => "Colonne d'une ListView ou d'une DataTable.",
        "Column.Binding" => "Champ de chaque ligne affiché dans cette colonne, par exemple {Binding Name}.",
        "Column.Header" => "Texte de l'en-tête de colonne.",
        "Column.Width" => "Largeur de la colonne, en pixels.",
        "Column.FormatString" => "Format des valeurs affichées dans cette colonne, par exemple N2 pour un nombre à deux décimales ou d pour une date courte. Vide affiche les valeurs telles quelles.",
        "Column.Culture" => "Culture utilisée pour mettre en forme et relire les valeurs de cette colonne, par exemple fr-FR. Vide utilise la culture du tableau.",
        "Column.NullValue" => "Texte affiché pour une valeur vide. Le saisir réécrit une valeur vide.",
        "Column.Alignment" => "Alignement horizontal des valeurs de cette colonne.",
        "Column.ReadOnly" => "Empêche la modification des cellules de cette colonne.",
        "Column.AutoSizeMode" => "Fill donne à la colonne la largeur que les autres laissent, au moins sa Width.",
        "ComboBox" => "Liste déroulante pour choisir une option. Ajoutez les options comme éléments Option enfants.",
        "ComboBox.DisplayMember" => "Champ de chaque élément lié affiché comme texte.",
        "ComboBox.ItemsSource" => "Liaison vers la liste des éléments à afficher, à la place des éléments Option.",
        "ComboBox.OnSelectedValueChanged" => "Se produit quand l'option sélectionnée change.",
        "ComboBox.SelectedValue" => "Valeur de l'option sélectionnée. Vide quand rien n'est sélectionné.",
        "ComboBox.ValueMember" => "Champ de chaque élément lié utilisé comme valeur.",
        "DataTable" => "Tableau de données avec colonnes triables et pagination. Déclarez les colonnes comme éléments Column enfants.",
        "DataTable.ItemsSource" => "Liaison vers la liste des lignes à afficher. Chaque colonne affiche le champ nommé par sa Binding.",
        "DataTable.OnRowActivated" => "Se produit quand une ligne est double-cliquée.",
        "DataTable.OnSelectionChanged" => "Se produit quand la ligne sélectionnée change.",
        "DataTable.OnSortChanged" => "Se produit quand un en-tête de colonne est cliqué pour trier le tableau.",
        "DataTable.SelectedIndex" => "Index de la ligne sélectionnée, à partir de 0. -1 signifie aucune.",
        "DataTable.ReadOnly" => "Empêche la modification des cellules. Si faux, F2, la frappe ou un double-clic modifie la cellule active ; Entrée ou Tab valide, Échap annule.",
        "DataTable.Culture" => "Culture utilisée pour mettre en forme et relire les valeurs des colonnes qui n'indiquent pas la leur, par exemple fr-FR. Vide utilise celle de l'utilisateur.",
        "DataTable.OnCellBeginEdit" => "Se produit quand une cellule va être modifiée. Mettez Cancel à vrai pour l'en empêcher.",
        "DataTable.OnCellValidating" => "Se produit quand une cellule modifiée va être validée, avec le texte saisi. Mettez Cancel à vrai pour le refuser et continuer la modification.",
        "DataTable.OnCellValueChanged" => "Se produit quand la valeur d'une cellule a été changée par une modification.",
        "DataTable.OnCellEndEdit" => "Se produit quand la modification d'une cellule se termine, validée ou annulée.",
        "DataTable.OnCellClick" => "Se produit quand une cellule est cliquée : sa ligne et sa colonne.",
        "DataTable.PageSize" => "Nombre de lignes par page. 0 affiche toutes les lignes sans pagination.",
        "DataTable.PageIndex" => "Page affichée, à partir de 0. Une liaison bidirectionnelle suit la pagination.",
        "DataTable.TotalRows" => "Nombre total de lignes quand vous chargez une page à la fois : ItemsSource ne contient alors que la page affichée. -1 pagine les lignes lui-même.",
        "DataTable.Density" => "Hauteur des lignes.",
        "DataTable.Loading" => "Affiche des lignes d'attente pendant le chargement des données.",
        "DataTable.EmptyTitle" => "Titre affiché quand il n'y a aucune ligne. Vide utilise le texte par défaut.",
        "DataTable.EmptyText" => "Description affichée quand il n'y a aucune ligne. Vide utilise le texte par défaut.",
        "DataTable.ErrorText" => "Si non vide, le tableau affiche une erreur avec cette description au lieu de ses lignes.",
        "DataTable.SortColumn" => "Champ de la colonne selon laquelle les lignes sont triées.",
        "DataTable.SortOrder" => "Sens du tri.",
        "DataTable.OnPageChanged" => "Se produit quand l'utilisateur passe à une autre page. La valeur est la nouvelle page, à partir de 0.",
        "DatePicker" => "Champ de date avec un calendrier déroulant.",
        "DockArea" => "Zone de travail entourée de panneaux que l'utilisateur peut ancrer à gauche ou à droite, regrouper en onglets, empiler, détacher en fenêtres flottantes, redimensionner, fermer et rouvrir. Ajoutez les panneaux comme éléments DockPanel enfants ; un autre élément enfant est le contenu de la zone centrale.",
        "DockArea.StorageKey" => "Clé sous laquelle la disposition choisie par l'utilisateur est enregistrée et restaurée ; vide pour ne rien conserver d'une exécution à l'autre.",
        "DockArea.Layout" => "Disposition actuelle, en JSON ; la modifier restaure une disposition, la vider restaure la disposition par défaut.",
        "DockArea.ActivePanel" => "Nom du panneau affiché au premier plan ; le modifier ouvre et affiche ce panneau.",
        "DockArea.Theme" => "Couleurs des panneaux : celles de l'application, ou celles des éditeurs sombres ou clairs.",
        "DockArea.ViewportColor" => "Couleur de fond de la zone centrale (#RRVVBB) ; vide pour le fond de l'application.",
        "DockArea.PanelsHidden" => "Masque les panneaux et affiche la zone centrale seule, en pleine taille.",
        "DockArea.OnPanelActivated" => "Se produit quand l'utilisateur met un panneau au premier plan.",
        "DockArea.OnPanelClosed" => "Se produit quand l'utilisateur ferme un panneau.",
        "DockArea.OnLayoutChanged" => "Se produit quand les panneaux sont déplacés, redimensionnés, fermés ou rouverts.",
        "DockPanel" => "Panneau d'une DockArea : un onglet que l'utilisateur peut déplacer, ancrer, détacher ou fermer, et un élément enfant comme contenu.",
        "DockPanel.Title" => "Texte de l'onglet du panneau.",
        "DockPanel.Icon" => "Icône affichée avant le titre : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "DockPanel.Side" => "Côté où le panneau est ancré par défaut.",
        "DockPanel.Group" => "Les panneaux d'un même côté ayant le même groupe partagent un groupe d'onglets ; vide pour un groupe à lui seul.",
        "DockPanel.Active" => "Affiche ce panneau en premier dans son groupe d'onglets.",
        "DockPanel.Closable" => "Indique si l'utilisateur peut fermer le panneau.",
        "DatePicker.Date" => "Date sélectionnée, au format AAAA-MM-JJ.",
        "DatePicker.Format" => "Affichage de la date : date longue, date courte ou heure.",
        "DatePicker.Invalid" => "Affiche le champ dans la couleur d'erreur.",
        "DatePicker.OnValueChanged" => "Se produit quand la date change.",
        "DatePicker.Today" => "Date considérée comme aujourd'hui, au format AAAA-MM-JJ. Laisser vide pour utiliser la date du jour.",
        "Dropdown" => "Liste déroulante pour choisir une option. Ajoutez les options comme éléments Option enfants.",
        "Dropdown.DisplayMember" => "Champ de chaque élément lié affiché comme texte.",
        "Dropdown.ItemsSource" => "Liaison vers la liste des éléments à afficher, à la place des éléments Option.",
        "Dropdown.OnSelectedValueChanged" => "Se produit quand l'option sélectionnée change.",
        "Dropdown.Placeholder" => "Texte affiché quand rien n'est sélectionné.",
        "Dropdown.SelectedValue" => "Valeur de l'option sélectionnée. Vide quand rien n'est sélectionné.",
        "Dropdown.ValueMember" => "Champ de chaque élément lié utilisé comme valeur.",
        "Dropdown.Variant" => "Aspect de la liste : avec bordure, ou sans bordure pour une barre d'outils.",
        "EmptyState" => "Écran affiché quand une zone n'a rien à montrer.",
        "EmptyState.ActionLabel" => "Texte du bouton d'action principal. Laisser vide pour aucun bouton.",
        "EmptyState.Compact" => "Occupe moins de hauteur, pour une petite zone.",
        "EmptyState.Description" => "Texte secondaire affiché sous le titre.",
        "EmptyState.Icon" => "Icône affichée en haut : un nom du jeu d'icônes Kubuno, ou un fichier image relatif à la vue.",
        "EmptyState.OnAction" => "Se produit quand le bouton d'action principal est cliqué.",
        "EmptyState.OnSecondaryAction" => "Se produit quand le bouton d'action secondaire est cliqué.",
        "EmptyState.SecondaryActionLabel" => "Texte du bouton d'action secondaire. Laisser vide pour aucun bouton.",
        "EmptyState.Title" => "Titre du message.",
        "EmptyState.Variant" => "Raison pour laquelle la zone est vide : première utilisation, aucun résultat, erreur ou indisponible.",
        "FloatingWindow" => "Fenêtre dessinée dans la vue, avec la barre de titre Kubuno et un bouton Fermer ; modale, elle voile le reste de la fenêtre.",
        "FloatingWindow.Title" => "Texte de la barre de titre de la fenêtre.",
        "FloatingWindow.Icon" => "Icône affichée avant le titre : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "FloatingWindow.IsOpen" => "Indique si la fenêtre est affichée. Liez-la pour ouvrir et fermer la fenêtre depuis le code ; le bouton Fermer la passe à false.",
        "FloatingWindow.Modal" => "Voile le reste de la fenêtre tant qu'elle est ouverte, comme un dialogue.",
        "FloatingWindow.ShowClose" => "Affiche le bouton Fermer de la barre de titre.",
        "FloatingWindow.CornerRadius" => "Rayon des coins de la fenêtre, en pixels (8 par défaut, comme une fenêtre du bureau ; 0 pour des coins droits).",
        "FloatingWindow.OnClose" => "Se produit quand on clique sur le bouton Fermer de la fenêtre.",
        "GroupBox" => "Cadre avec un titre autour d'un élément enfant.",
        "GroupBox.Padding" => "Espace autour de l'élément enfant, sur les quatre côtés, en pixels.",
        "GroupBox.Title" => "Titre affiché en haut du cadre.",
        "Icon" => "Icône.",
        "Icon.Name" => "L'icône : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "Icon.Size" => "Taille de l'icône, en pixels.",
        "Icon.Disc" => "Dessine l'icône sur un disque coloré, comme les icônes des boîtes de message et des confirmations de Kubuno.",
        "IconButton" => "Bouton rond qui n'affiche qu'une icône.",
        "IconButton.Diameter" => "Diamètre du bouton, en pixels.",
        "IconButton.Filled" => "Donne au bouton un fond teinté.",
        "IconButton.Glyph" => "Taille de l'icône dans le bouton, en pixels.",
        "IconButton.Icon" => "L'icône : un nom du jeu d'icônes Kubuno (Check, X, Trash2, Search, Plus, MoreVertical…), ou un fichier image relatif à la vue.",
        "IconButton.OnClick" => "Se produit quand le bouton est cliqué ou activé avec Espace ou Entrée.",
        "Item" => "Élément d'une ListBox, CheckedListBox, ListView ou TreeView.",
        "Item.Text" => "Texte de l'élément.",
        "Label" => "Étiquette de texte.",
        "Label.TextAlign" => "Position du texte dans l'étiquette.",
        "Label.Overflow" => "Traitement du texte trop long : points de suspension, coupé, ou renvoyé à la ligne.",
        "Label.Role" => "Style du texte : petit, légende, corps, intertitre, titre, titre de page ou titre de page d’administration.",
        "Label.Text" => "Texte affiché.",
        "LinkLabel" => "Lien cliquable.",
        "LinkLabel.OnClick" => "Se produit quand le lien est cliqué.",
        "LinkLabel.Role" => "Style du texte : petit, légende, corps, intertitre, titre, titre de page ou titre de page d’administration.",
        "LinkLabel.Text" => "Texte du lien.",
        "LinkLabel.Visited" => "Affiche le lien comme déjà visité.",
        "ListBox" => "Liste d'éléments. Ajoutez les éléments comme enfants Item ou liez ItemsSource.",
        "ListBox.ItemsSource" => "Liaison vers la liste des éléments à afficher, à la place des éléments Item.",
        "ListBox.ItemHeight" => "Hauteur d'une ligne, en DIP (avec DrawMode OwnerDrawFixed : la hauteur dans laquelle dessine le gestionnaire DrawItem) ; 0 pour la hauteur standard.",
        "ListBox.OnSelectionChanged" => "Se produit quand la sélection change.",
        "ListBox.SelectedIndex" => "Index de l'élément sélectionné, à partir de 0. -1 signifie aucun.",
        "ListBox.SelectionMode" => "Nombre d'éléments sélectionnables, et effet de Ctrl et Maj avec un clic.",
        "ListView" => "Liste d'éléments en colonnes. Déclarez les colonnes comme éléments Column enfants.",
        "ListView.ItemsSource" => "Liaison vers la liste des lignes à afficher. Chaque colonne affiche le champ nommé par sa Binding.",
        "ListView.MultiSelect" => "Permet de sélectionner plusieurs éléments.",
        "ListView.OnItemActivate" => "Se produit quand un élément est double-cliqué.",
        "ListView.OnSelectionChanged" => "Se produit quand la sélection change.",
        "ListView.SelectedIndex" => "Index de l'élément sélectionné, à partir de 0. -1 signifie aucun.",
        "MaskedField" => "Zone de texte qui suit un masque de saisie, par exemple 00/00/0000.",
        "MaskedField.Invalid" => "Affiche le champ dans la couleur d'erreur.",
        "MaskedField.Mask" => "Masque de saisie, par exemple 00/00/0000 pour une date.",
        "MaskedField.OnTextChanged" => "Se produit quand le texte change.",
        "MaskedField.Text" => "Texte contenu dans le champ.",
        "MonthCalendar" => "Calendrier affichant un mois.",
        "MonthCalendar.OnDateSelected" => "Se produit quand un jour est cliqué.",
        "MonthCalendar.SelectedDate" => "Date sélectionnée, au format AAAA-MM-JJ. Vide signifie aucune.",
        "MonthCalendar.Today" => "Date considérée comme aujourd'hui, au format AAAA-MM-JJ. Laisser vide pour utiliser la date du jour.",
        "NumericField" => "Champ numérique avec des boutons haut et bas.",
        "NumericField.DecimalPlaces" => "Nombre de décimales affichées.",
        "NumericField.Invalid" => "Affiche le champ dans la couleur d'erreur.",
        "NumericField.Maximum" => "Valeur maximale.",
        "NumericField.Minimum" => "Valeur minimale.",
        "NumericField.OnValueChanged" => "Se produit quand la valeur change.",
        "NumericField.Increment" => "Valeur ajoutée ou retirée par les boutons haut et bas.",
        "NumericField.ThousandsSeparator" => "Affiche un séparateur entre les groupes de milliers.",
        "NumericField.Value" => "Valeur actuelle, entre Minimum et Maximum.",
        "Option" => "Élément de la liste d'un Dropdown ou d'une ComboBox.",
        "Option.Label" => "Texte affiché pour l'élément. Par défaut, Value.",
        "Option.Value" => "Valeur de l'élément.",
        "Panel" => "Conteneur qui place ses éléments enfants par ancrage ou amarrage.",
        "Panel.Padding" => "Espace autour des éléments enfants, sur les quatre côtés, en pixels.",
        "Panel.Surface" => "Fond peint derrière les éléments enfants.",
        "Timer" => "Composant qui déclenche un événement à intervalles réguliers.",
        "Timer.Enabled" => "Indique si la minuterie est en marche.",
        "Timer.Interval" => "Temps entre deux déclenchements, en millisecondes.",
        "Timer.OnTick" => "Se produit quand l'intervalle est écoulé alors que la minuterie est en marche.",
        "ToolTip" => "Composant qui règle l'apparition des info-bulles de la vue. Le texte de l'info-bulle de chaque contrôle est sa propriété ToolTip.",
        "ToolTip.InitialDelay" => "Temps pendant lequel la souris doit rester sur un contrôle avant que son info-bulle apparaisse, en millisecondes.",
        "ToolTip.AutoPopDelay" => "Durée d'affichage d'une info-bulle tant que la souris reste sur son contrôle, en millisecondes.",
        "ToolTip.ReshowDelay" => "Délai avant l'apparition de l'info-bulle suivante quand la souris passe d'un contrôle à un autre, en millisecondes.",
        "ToolTip.ShowAlways" => "Affiche les info-bulles même quand la fenêtre n'est pas active.",
        "ToolTip.Active" => "Indique si les info-bulles sont affichées.",
        "ContextMenu" => "Menu affiché quand on clique avec le bouton droit sur un contrôle qui le nomme dans sa propriété ContextMenu, quand on clique sur un bouton qui le nomme dans sa propriété DropDownMenu, ou depuis le code (show). Ajoutez ses commandes comme éléments MenuItem enfants ; des MenuItem enfants d'un MenuItem forment un sous-menu.",
        "ContextMenu.OnOpening" => "Se produit quand le menu va s'ouvrir.",
        "ContextMenu.ItemsSource" => "Commandes ajoutées depuis une liste à l'ouverture du menu (champs Text, Key, Icon, ShortcutKeys, Checked, Enabled, Danger, et Kind = Separator ou Header) ; en choisir une déclenche OnItemClicked avec sa clé.",
        "ContextMenu.OnItemClicked" => "Se produit quand une commande issue d'ItemsSource est choisie : sa clé est le nouveau texte.",
        "MenuItem" => "Commande d'un menu. Des MenuItem enfants en font un sous-menu ; un texte fait d'un seul tiret (ou Kind Separator) crée une ligne de séparation.",
        "MenuItem.Text" => "Texte de la commande. Une esperluette devant une lettre en fait le raccourci clavier dans le menu.",
        "MenuItem.Icon" => "Icône affichée avant le texte : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "MenuItem.Kind" => "Une commande, une ligne de séparation ou un titre de section.",
        "MenuItem.Danger" => "Commande destructrice, affichée dans la couleur de danger.",
        "MenuItem.Enabled" => "Indique si la commande peut être choisie.",
        "MenuItem.Visible" => "Indique si la commande est affichée.",
        "MenuItem.Checked" => "Affiche une coche devant la commande.",
        "MenuItem.CheckOnClick" => "Choisir la commande inverse sa coche.",
        "MenuItem.RadioGroup" => "Les commandes d'un même groupe s'excluent : en choisir une la coche et décoche les autres.",
        "MenuItem.ShortcutKeys" => "Raccourci clavier affiché à côté de la commande, par exemple Ctrl+C.",
        "MenuItem.ItemsSource" => "Commandes du sous-menu ajoutées depuis une liste à son ouverture (voir l'ItemsSource du ContextMenu).",
        "MenuItem.OnClick" => "Se produit quand la commande est choisie.",
        "MenuItem.OnCheckedChanged" => "Se produit quand choisir la commande a changé sa coche (CheckOnClick, RadioGroup).",
        "MenuItem.OnDropDownOpening" => "Se produit quand son sous-menu va s'ouvrir : remplissez-le maintenant (son ItemsSource est lu ensuite).",
        "Button.DropDownMenu" => "ContextMenu de la vue qu'un clic ouvre sous le bouton (bouton déroulant).",
        "IconButton.DropDownMenu" => "ContextMenu de la vue qu'un clic ouvre sous le bouton (bouton de menu).",
        "Stack.WrapContents" => "Renvoie les enfants sur plusieurs lignes (ou colonnes) quand ils ne tiennent pas, comme un FlowLayoutPanel.",
        "Stack.CrossAlign" => "Place les enfants en travers du flux : étirés sur la ligne (ou la colonne), ou à leur propre taille au début, au centre ou à la fin.",
        "Repeater" => "Liste dont les éléments sont des vues : chaque ligne d'ItemsSource est affichée par le contrôle utilisateur ItemTemplate, ou par l'élément écrit dans le Repeater. Seuls les éléments visibles sont construits.",
        "Repeater.ItemsSource" => "Lignes affichées, un élément chacune : une liaison vers une liste.",
        "Repeater.ItemTemplate" => "Contrôle utilisateur qui affiche un élément ; vide pour utiliser l'élément écrit dans le Repeater.",
        "Repeater.ItemKey" => "Champ de la ligne qui identifie un élément quand la liste change (un identifiant) ; vide pour la position.",
        "Repeater.Orientation" => "Indique si les éléments se suivent vers le bas ou vers la droite.",
        "Repeater.Wrap" => "Renvoie les éléments sur plusieurs lignes (une grille de cartes) au lieu d'une seule colonne ou ligne.",
        "Repeater.Spacing" => "Espace entre deux éléments, en DIP.",
        "Repeater.ItemWidth" => "Largeur d'un élément, en DIP ; 0 pour toute la largeur (une colonne) ou la largeur de conception du modèle (renvoi à la ligne).",
        "Repeater.ItemHeight" => "Hauteur d'un élément, en DIP ; 0 pour mesurer chaque élément.",
        "Repeater.ItemHeightField" => "Champ de la ligne qui donne la hauteur de chaque élément, en DIP, pour des éléments de hauteurs différentes ; vide pour mesurer chaque élément.",
        "Repeater.SelectionMode" => "Indique si un clic sur un élément le sélectionne (et l'affiche sélectionné).",
        "Repeater.SelectedIndex" => "Index de l'élément sélectionné, -1 pour aucun.",
        "Repeater.EmptyText" => "Texte affiché quand la liste n'a aucun élément.",
        "Repeater.DesignItemCount" => "Nombre d'éléments d'exemple que le concepteur affiche quand la liste n'a pas de lignes à la conception.",
        "Repeater.OnItemClick" => "Se produit quand on clique sur un élément.",
        "Repeater.OnSelectionChanged" => "Se produit quand l'élément sélectionné change.",
        "Sidebar" => "Volet de navigation : lignes avec une icône et un libellé, en-têtes de section et groupes dépliables. La ligne active est SelectedItem.",
        "Sidebar.SelectedItem" => "Clé (Key) de la ligne active (son x:Name, ou son texte si elle n'a pas de Key).",
        "Sidebar.DisplayMode" => "Expanded affiche les libellés ; Compact affiche un rail d'icônes.",
        "Sidebar.ItemsSource" => "Lignes issues d'une liste (champs Text, Icon, Key, Level, et Kind=\"Section\" pour un en-tête), à la place des lignes écrites dedans.",
        "Sidebar.OnItemInvoked" => "Se produit quand une ligne est choisie (clic ou Entrée) : sa clé est le nouveau texte.",
        "Sidebar.OnSelectionChanged" => "Se produit quand la ligne active change.",
        "SidebarItem" => "Ligne d'une Sidebar : une icône et un libellé. Des SidebarItem enfants en font un groupe que l'utilisateur peut déplier ou replier.",
        "SidebarItem.Text" => "Libellé de la ligne.",
        "SidebarItem.Icon" => "Icône affichée avant le libellé : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "SidebarItem.Key" => "Valeur de SelectedItem quand la ligne est active ; vide pour le x:Name, sinon le texte.",
        "SidebarItem.Indent" => "Où commence son icône, en pixels depuis la gauche de la ligne ; -1 pour un pas par niveau de l'arbre (plus la colonne du chevron pour un groupe). Une ligne simple réglée sur le retrait d'un groupe s'aligne sur les groupes.",
        "SidebarItem.Expanded" => "Pour une ligne qui a des enfants : indique s'ils sont affichés au départ.",
        "SidebarItem.Enabled" => "Indique si la ligne peut être choisie.",
        "SidebarItem.Visible" => "Indique si la ligne est affichée.",
        "SidebarItem.OnClick" => "Se produit quand la ligne est choisie.",
        "SidebarSection" => "En-tête de section d'une Sidebar : petit texte en majuscules au-dessus des lignes qui le suivent.",
        "SidebarSection.Text" => "Texte de l'en-tête.",
        "SidebarSection.Visible" => "Indique si l'en-tête est affiché.",
        "StatusBar" => "Barre d'état : une rangée de cellules StatusLabel le long du bas d'une fenêtre.",
        "StatusBar.OnItemClicked" => "Se produit quand on clique sur une cellule cliquable (son index est dans l'événement).",
        "StatusLabel" => "Cellule d'une StatusBar : un texte, une icône facultative. Spring lui fait partager la largeur restante ; un texte fait d'un seul tiret crée un séparateur ; Clickable en fait un bouton.",
        "StatusLabel.Text" => "Texte de la cellule. Un seul tiret crée un séparateur.",
        "StatusLabel.Icon" => "Icône affichée avant le texte (cellule cliquable) : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "StatusLabel.Spring" => "La cellule prend la largeur que les autres cellules laissent.",
        "StatusLabel.ForeColor" => "Couleur du texte de la cellule (une couleur du thème comme Caution, ou #RRGGBB) ; vide : la couleur du texte secondaire de la barre.",
        "StatusLabel.Clickable" => "La cellule est un bouton : elle s'éclaire sous la souris et déclenche OnClick.",
        "StatusLabel.Enabled" => "Indique si une cellule cliquable peut être cliquée.",
        "StatusLabel.Visible" => "Indique si la cellule est affichée.",
        "StatusLabel.OnClick" => "Se produit quand on clique sur une cellule cliquable.",
        "Avatar" => "Photo d'une personne dans un cercle, ou ses initiales sur une couleur quand il n'y a pas de photo, avec une pastille de présence facultative.",
        "Avatar.DisplayName" => "Nom de la personne : ses initiales sont affichées quand il n'y a pas de photo, et il choisit la couleur.",
        "Avatar.Initials" => "Lettres affichées à la place des initiales du nom.",
        "Avatar.Image" => "Photo : le chemin d'un fichier image, relatif à la vue.",
        "Avatar.ImageData" => "Photo sous forme d'octets d'un fichier image (une liaison vers un Shared<Vec<u8>>), pour une photo téléchargée par l'application.",
        "Avatar.Tint" => "Auto : une couleur choisie d'après le nom, initiales en blanc. Accent : la couleur d'accent pâle, initiales dans la couleur d'accent. Primary : la couleur d'accent, initiales en blanc (l'utilisateur connecté dans un en-tête).",
        "Avatar.Shape" => "Un cercle, ou un carré aux coins arrondis.",
        "Avatar.Presence" => "Pastille affichée en bas à droite : la disponibilité de la personne.",
        "Avatar.AvatarSize" => "Diamètre de l'avatar, en DIP (la boîte de l'élément est remplie si elle est plus petite).",
        "PictureBox" => "Image, issue d'un fichier ou de la mémoire, ajustée au contrôle selon SizeMode.",
        "PictureBox.Image" => "Image : le chemin d'un fichier image, relatif à la vue.",
        "PictureBox.ImageData" => "Image sous forme d'octets d'un fichier image (une liaison vers un Shared<Vec<u8>>).",
        "PictureBox.SizeMode" => "Normal : à sa taille, en haut à gauche. Stretch : à la taille du contrôle. Zoom : aussi grande que possible en gardant ses proportions. Center : à sa taille, centrée. Cover : remplit le contrôle en gardant ses proportions (rognée).",
        "PictureBox.CornerRadius" => "Arrondit les coins de l'image, en DIP.",
        "PictureBox.BorderStyle" => "Ligne dessinée autour du contrôle.",
        "SplashArtwork" => "Illustration d'un écran de démarrage : l'illustration procédurale et la marque du module, le nom du produit, la version, la ligne d'état, la barre de progression et les mentions légales.",
        "SplashArtwork.Artwork" => "Illustration de quelle application : Kubuno (le shell), Drive, Chat ou Documents.",
        "SplashArtwork.Product" => "Nom du produit, « Kubuno Drive » (vide : celui de l'illustration).",
        "SplashArtwork.Version" => "Ligne de version, « Version 0.1.0 ».",
        "SplashArtwork.Tagline" => "Ligne sous le nom du produit (vide : celle de l'illustration).",
        "SplashArtwork.Status" => "Ligne d'état : l'étape du démarrage en cours.",
        "SplashArtwork.Progress" => "Avancement du démarrage, de 0 à 1 ; en dessous de 0, un reflet qui parcourt la barre.",
        "SplashArtwork.License" => "Licence nommée sur la ligne des mentions légales.",
        "SplashArtwork.Credits" => "Ligne de remerciements (vide : celle par défaut).",
        "Popover" => "Panneau flottant affiché à côté d'un contrôle (sa cible) tant qu'IsOpen vaut true ; un clic à l'extérieur ou Échap le ferme. Il se dessine au-dessus du reste de la vue, où qu'il soit déclaré.",
        "Popover.Target" => "x:Name du contrôle à côté duquel il s'ouvre.",
        "Popover.IsOpen" => "Indique s'il est affiché. Liez-le dans les deux sens pour savoir quand l'utilisateur le ferme.",
        "Popover.Placement" => "Côté de la cible où il s'ouvre, quand il y a la place.",
        "Popover.Alignment" => "Bords du panneau et de la cible qui s'alignent.",
        "Popover.PopupWidth" => "Largeur du panneau, en DIP ; 0 pour celle de son contenu.",
        "Popover.PopupHeight" => "Hauteur du panneau, en DIP ; 0 pour celle de son contenu.",
        "Popover.LightDismiss" => "Le ferme sur un clic à l'extérieur ou Échap.",
        "Popover.OnOpened" => "Se produit quand le panneau s'ouvre.",
        "Popover.OnClosed" => "Se produit quand le panneau se ferme.",
        "TableLayoutPanel" => "Grille : ses enfants sont placés en lignes et en colonnes dimensionnées en pixels, en parts de la place restante, ou d'après leur contenu.",
        "TableLayoutPanel.ColumnCount" => "Nombre de colonnes.",
        "TableLayoutPanel.RowCount" => "Nombre de lignes (d'autres sont ajoutées quand les enfants en ont besoin, avec GrowStyle AddRows).",
        "TableLayoutPanel.ColumnStyles" => "Dimensionnement de chaque colonne, séparé par des points-virgules : Absolute 120, Percent 50 ou AutoSize. Une colonne sans style reçoit Percent 1 (une part égale).",
        "TableLayoutPanel.RowStyles" => "Dimensionnement de chaque ligne, séparé par des points-virgules : Absolute 40, Percent 50 ou AutoSize. Une ligne sans style est AutoSize.",
        "TableLayoutPanel.GrowStyle" => "Ce qui se passe quand les enfants ne tiennent pas dans la grille déclarée.",
        "TableLayoutPanel.CellBorderStyle" => "Lignes dessinées autour des cellules et entre elles.",
        "TableLayoutPanel.CellSpacing" => "Espace entre deux cellules, en DIP.",
        "UserControl" => "Racine d'un contrôle utilisateur : un contrôle réutilisable conçu comme une vue à part entière, dont les éléments enfants sont placés par ancrage ou amarrage.",
        "UserControl.Padding" => "Espace autour des éléments enfants, sur les quatre côtés, en pixels.",
        "UserControl.Surface" => "Fond peint derrière les éléments enfants.",
        "ProgressBar" => "Barre de progression.",
        "ProgressBar.Indeterminate" => "Affiche une animation au lieu d'une valeur, quand la progression est inconnue.",
        "ProgressBar.Label" => "Texte affiché au-dessus de la barre. Laisser vide pour aucun texte.",
        "ProgressBar.Maximum" => "Valeur pour laquelle la barre est pleine.",
        "ProgressBar.Minimum" => "Valeur pour laquelle la barre est vide.",
        "ProgressBar.ShowValue" => "Affiche le pourcentage au-dessus de la barre.",
        "ProgressBar.Size" => "Épaisseur de la barre.",
        "ProgressBar.Value" => "Progression actuelle, entre Min et Max.",
        "ProgressBar.Variant" => "Couleur de la barre. Auto passe à l'orange puis au rouge à mesure qu'elle se remplit.",
        "RadioButton" => "Bouton d'option : une seule option d'un groupe peut être sélectionnée.",
        "RadioButton.AutoCheck" => "Sélectionne l'option quand on clique dessus.",
        "RadioButton.Description" => "Texte secondaire affiché sous le libellé.",
        "RadioButton.Group" => "Nom du groupe auquel appartient cette option.",
        "RadioButton.OnCheckedChanged" => "Se produit quand cette option est sélectionnée.",
        "RadioButton.SelectedValue" => "Valeur de l'option sélectionnée du groupe, généralement liée dans les deux sens. L'option est sélectionnée quand elle est égale à Value.",
        "RadioButton.Text" => "Texte affiché à côté de l'option.",
        "RadioButton.Value" => "Valeur que représente cette option.",
        "ScrollArea" => "Zone défilante autour d'un élément enfant.",
        "ScrollArea.Corner" => "Rayon des coins arrondis, en pixels. 0 pour des coins carrés.",
        "SearchField" => "Zone de recherche avec un bouton d'effacement.",
        "SearchField.OnTextChanged" => "Se produit quand le texte recherché change.",
        "SearchField.Placeholder" => "Indication affichée tant que le champ est vide.",
        "SearchField.Text" => "Texte recherché.",
        "Separator" => "Fine ligne de séparation.",
        "Separator.Orientation" => "Indique si la ligne est horizontale ou verticale.",
        "Slider" => "Curseur pour choisir une valeur dans une plage.",
        "Slider.LargeChange" => "Pas de variation avec Page précédente ou Page suivante.",
        "Slider.Maximum" => "Valeur maximale.",
        "Slider.Minimum" => "Valeur minimale.",
        "Slider.OnValueChanged" => "Se produit quand la valeur change.",
        "Slider.SmallChange" => "Pas de variation avec une touche fléchée.",
        "Slider.Value" => "Valeur actuelle, entre Minimum et Maximum.",
        "Spinner" => "Indicateur de chargement animé.",
        "Spinner.Size" => "Taille de l'indicateur.",
        "Splitter" => "Deux volets séparés par une barre déplaçable.",
        "Splitter.Distance" => "Taille du premier volet, en pixels. Mise à jour quand la barre est déplacée.",
        "Splitter.OnDistanceChanged" => "Se produit quand la barre est déplacée.",
        "Splitter.Orientation" => "Vertical : volets côte à côte. Horizontal : volets l'un au-dessus de l'autre.",
        "Stack" => "Aligne ses éléments enfants les uns après les autres, en ligne ou en colonne.",
        "Stack.Direction" => "Sens dans lequel les éléments enfants sont placés.",
        "Stack.Gap" => "Espace entre deux éléments enfants, en pixels.",
        "Stack.Padding" => "Espace autour des éléments enfants, sur les quatre côtés, en pixels.",
        "Stack.Surface" => "Fond peint derrière les éléments enfants.",
        "Step" => "Étape d'un Stepper.",
        "Step.Description" => "Texte secondaire affiché sous le libellé.",
        "Step.Label" => "Texte de l'étape.",
        "Step.Optional" => "Marque l'étape comme facultative.",
        "Step.Status" => "État de l'étape. Laisser vide pour le déduire de l'étape en cours.",
        "Stepper" => "Progression d'un processus en plusieurs étapes. Ajoutez les étapes comme éléments Step enfants.",
        "Stepper.AllowForward" => "Permet de cliquer sur une étape située après l'étape en cours.",
        "Stepper.CurrentIndex" => "Index de l'étape en cours, à partir de 0.",
        "Stepper.OnStepSelected" => "Se produit quand l'utilisateur clique sur une étape.",
        "Stepper.Orientation" => "Indique si les étapes sont disposées horizontalement ou verticalement.",
        "Switch" => "Interrupteur marche/arrêt.",
        "Switch.Description" => "Texte secondaire affiché sous le libellé.",
        "Switch.Label" => "Texte affiché à côté de l'interrupteur.",
        "Switch.On" => "Indique si l'interrupteur est activé.",
        "Switch.OnCheckedChanged" => "Se produit quand l'interrupteur est activé ou désactivé.",
        "Switch.Size" => "Taille de l'interrupteur.",
        "Switch.CheckAlign" => "Où se place l'interrupteur par rapport à son libellé : MiddleLeft avant lui, MiddleRight à l'extrémité droite du contrôle, après lui (une ligne de réglages).",
        "TabItem" => "Page d'un contrôle Tabs.",
        "TabItem.Header" => "Texte de l'onglet.",
        "Tabs" => "Ensemble de pages affichées une à la fois, avec des onglets. Ajoutez les pages comme éléments TabItem enfants.",
        "Tabs.OnSelectionChanged" => "Se produit quand un autre onglet est sélectionné.",
        "Tabs.SelectedIndex" => "Index de l'onglet sélectionné, à partir de 0.",
        "TextArea" => "Zone de texte multiligne.",
        "TextArea.AcceptsReturn" => "Passe à la ligne quand on appuie sur Entrée. Sinon, Entrée clique sur le bouton de validation de la vue.",
        "TextArea.Invalid" => "Affiche le champ dans la couleur d'erreur.",
        "TextArea.OnTextChanged" => "Se produit quand le texte change.",
        "TextArea.Placeholder" => "Indication affichée tant que le champ est vide.",
        "TextArea.Text" => "Texte contenu dans le champ.",
        "TextArea.WordWrap" => "Renvoie les longues lignes à la ligne au bord du champ.",
        "TextArea.MinLines" => "Grandit avec son texte à partir de ce nombre de lignes (dans une disposition qui le dimensionne, une Stack ou AutoSize) ; 0 pour la hauteur standard.",
        "TextArea.MaxLines" => "Grandit avec son texte jusqu'à ce nombre de lignes, puis défile ; 0 pour aucune limite.",
        "TextField" => "Zone de texte sur une ligne.",
        "TextField.Invalid" => "Affiche le champ dans la couleur d'erreur.",
        "TextField.OnTextChanged" => "Se produit quand le texte change.",
        "TextField.Placeholder" => "Indication affichée tant que le champ est vide.",
        "TextField.Text" => "Texte contenu dans le champ.",
        "Toolbar" => "Barre d'outils. Ajoutez les commandes comme éléments ToolbarItem enfants.",
        "Toolbar.Band" => "Peint une bande de fond derrière les commandes.",
        "ToolbarItem" => "Commande d'une barre d'outils.",
        "ToolbarItem.Icon" => "Icône affichée avant le texte : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "ToolbarItem.OnClick" => "Se produit quand la commande est cliquée.",
        "ToolbarItem.Text" => "Texte de la commande. Laisser vide pour une commande avec icône seule.",
        "TreeView" => "Arborescence d'éléments dépliables. Ajoutez les éléments comme éléments Item imbriqués.",
        "WorkspaceShell" => "Cadre d'un éditeur : une barre supérieure avec le titre, le nom de l'éditeur et les détails du document, une barre d'état facultative, et un élément enfant comme corps (en général une DockArea).",
        "WorkspaceShell.Title" => "Titre affiché dans la barre supérieure (le nom du document).",
        "WorkspaceShell.Icon" => "Icône affichée avant le titre : un nom du jeu d'icônes Kubuno, ou un fichier image (SVG, PNG…) relatif à la vue.",
        "WorkspaceShell.Subtitle" => "Nom de l'éditeur, affiché après le titre dans la couleur d'accent.",
        "WorkspaceShell.DocInfo" => "Détails du document affichés après le sous-titre (dimensions, nombre de pages…).",
        "WorkspaceShell.StatusText" => "Textes de la barre d'état, séparés par « | » ; vide pour ne pas afficher de barre d'état.",
        "WorkspaceShell.Theme" => "Couleurs du cadre.",
        "WorkspaceShell.ShowBack" => "Affiche la flèche de retour.",
        "WorkspaceShell.ShowSearch" => "Affiche le bouton de recherche.",
        "WorkspaceShell.ShowDelete" => "Affiche le bouton de suppression.",
        "WorkspaceShell.OnBack" => "Se produit quand on clique sur la flèche de retour.",
        "WorkspaceShell.OnSearch" => "Se produit quand on clique sur le bouton de recherche.",
        "WorkspaceShell.OnDelete" => "Se produit quand on clique sur le bouton de suppression.",
        "TreeView.ItemsSource" => "Liaison vers une liste simple d'éléments à afficher, à la place des éléments Item.",
        "TreeView.ItemHeight" => "Hauteur d'une ligne, en DIP ; 0 pour la hauteur standard.",
        "TreeView.MultiSelect" => "Permet de sélectionner plusieurs éléments.",
        "TreeView.OnItemActivate" => "Se produit quand un élément est double-cliqué.",
        "TreeView.OnSelectionChanged" => "Se produit quand l'élément sélectionné change.",
        "TreeView.SelectedPath" => "Élément sélectionné, sous forme d'index séparés par des points, par exemple 0.2.1. Vide signifie aucun.",
        // Owner-draw (EVT-8).
        "ListBox.DrawMode" | "ComboBox.DrawMode" | "Dropdown.DrawMode" => "Qui dessine les éléments : le contrôle (Normal), ou votre gestionnaire DrawItem avec une même hauteur pour tous (OwnerDrawFixed) ou une hauteur par élément donnée par votre gestionnaire MeasureItem (OwnerDrawVariable).",
        "Tabs.DrawMode" => "Qui dessine les onglets : le contrôle (Normal) ou votre gestionnaire DrawItem (OwnerDrawFixed).",
        "TreeView.DrawMode" => "Qui dessine les éléments : le contrôle (Normal), ou votre gestionnaire DrawItem, pour le texte seul (OwnerDrawText) ou la ligne entière (OwnerDrawAll).",
        "ListView.OwnerDraw" | "ContextMenu.OwnerDraw" => "Dessine les éléments avec votre gestionnaire DrawItem au lieu de l'apparence du contrôle.",
        "DataTable.OwnerDraw" => "Dessine les cellules avec votre gestionnaire DrawItem (e.sub_index est la colonne) au lieu du texte du tableau.",
        "ListBox.OnDrawItem" | "ComboBox.OnDrawItem" | "Dropdown.OnDrawItem" | "ListView.OnDrawItem" | "TreeView.OnDrawItem" | "DataTable.OnDrawItem" | "Tabs.OnDrawItem" | "ContextMenu.OnDrawItem" => "Se produit quand un élément dessiné par le propriétaire doit être dessiné : dessinez-le avec e.graphics() dans e.bounds.",
        "ListBox.OnMeasureItem" | "ComboBox.OnMeasureItem" | "Dropdown.OnMeasureItem" => "Se produit quand la hauteur d'un élément d'une liste OwnerDrawVariable est demandée : définissez e.item_height.",
        "PaintBox" => "Surface de dessin : votre gestionnaire Paint y dessine avec e.graphics() (lignes, formes, dégradés, texte, images).",
        "PaintBox.OnPaint" => "Se produit quand la surface est dessinée : dessinez avec e.graphics() dans e.clip_rectangle.",
        // The events every control raises (super::COMMON_EVENTS), keyed *.<event>.
        "*.OnClick" => "Se produit quand l'utilisateur clique sur le contrôle.",
        "*.OnDoubleClick" => "Se produit quand l'utilisateur double-clique sur le contrôle.",
        "*.OnMouseClick" => "Se produit quand l'utilisateur clique sur le contrôle avec la souris.",
        "*.OnMouseDoubleClick" => "Se produit quand l'utilisateur double-clique sur le contrôle avec la souris.",
        "*.OnMouseDown" => "Se produit quand un bouton de la souris est enfoncé au-dessus du contrôle.",
        "*.OnMouseUp" => "Se produit quand un bouton de la souris enfoncé au-dessus du contrôle est relâché.",
        "*.OnMouseMove" => "Se produit quand le pointeur de la souris se déplace sur le contrôle.",
        "*.OnMouseEnter" => "Se produit quand le pointeur de la souris entre dans le contrôle.",
        "*.OnMouseLeave" => "Se produit quand le pointeur de la souris quitte le contrôle.",
        "*.OnMouseHover" => "Se produit quand le pointeur de la souris s'immobilise sur le contrôle.",
        "*.OnMouseWheel" => "Se produit quand la molette de la souris tourne alors que le pointeur est sur le contrôle.",
        "*.OnKeyDown" => "Se produit quand une touche est enfoncée alors que le contrôle a le focus.",
        "*.OnKeyPress" => "Se produit quand une touche de caractère est enfoncée alors que le contrôle a le focus.",
        "*.OnKeyUp" => "Se produit quand une touche est relâchée alors que le contrôle a le focus.",
        "*.OnEnter" => "Se produit quand le contrôle, ou un contrôle qu'il contient, reçoit le focus.",
        "*.OnGotFocus" => "Se produit quand le contrôle reçoit le focus.",
        "*.OnLeave" => "Se produit quand le focus quitte le contrôle et tous les contrôles qu'il contient.",
        "*.OnLostFocus" => "Se produit quand le contrôle perd le focus.",
        "*.OnValidating" => "Se produit pendant la validation du contrôle, avant que le focus le quitte. Annulez-le pour garder le focus.",
        "*.OnValidated" => "Se produit quand la validation du contrôle est terminée.",
        "*.OnResize" => "Se produit quand le contrôle est redimensionné.",
        "*.OnMove" => "Se produit quand le contrôle est déplacé.",
        "*.OnSizeChanged" => "Se produit quand la taille du contrôle change.",
        "*.OnLocationChanged" => "Se produit quand la position du contrôle change.",
        "*.OnDragDrop" => "Se produit quand des données (fichiers, texte…) sont déposées sur le contrôle. Sa propriété AllowDrop doit valoir true, et DragEnter ou DragOver doit les avoir acceptées (e.effect).",
        "*.OnDragEnter" => "Se produit quand des données sont glissées sur le contrôle. Définissez e.effect pour accepter le dépôt. Sa propriété AllowDrop doit valoir true.",
        "*.OnDragOver" => "Se produit pendant que des données sont glissées sur le contrôle. Définissez e.effect pour accepter le dépôt à cet endroit.",
        "*.OnDragLeave" => "Se produit quand des données glissées sur le contrôle le quittent ou que le glissement est annulé.",
        "*.OnPaint" => "Se produit quand le contrôle est dessiné : dessinez avec e.graphics(). Déclenché par les contrôles personnalisés, les éléments PaintBox et les boutons.",
        // The view's own events (`super::VIEW_EVENTS`, root element only).
        "View.OnLoad" => "Se produit avant le premier affichage de la vue.",
        "View.OnShown" => "Se produit la première fois que la vue est affichée.",
        "View.OnActivated" => "Se produit quand la fenêtre de la vue devient active.",
        "View.OnDeactivate" => "Se produit quand la fenêtre de la vue cesse d'être active.",
        "View.OnFormClosing" => "Se produit avant la fermeture de la fenêtre de la vue. Annulez-le pour la garder ouverte (modifications non enregistrées).",
        "View.OnFormClosed" => "Se produit après la fermeture de la fenêtre de la vue, juste avant sa destruction.",
        "View.OnResizeBegin" => "Se produit quand l'utilisateur commence à déplacer ou redimensionner la fenêtre.",
        "View.OnResizeEnd" => "Se produit quand l'utilisateur a fini de déplacer ou redimensionner la fenêtre.",
        "View.OnTitleBarDoubleClick" => "Se produit quand on double-clique sur la barre de titre (la fenêtre s'agrandit ou se restaure ensuite).",
        "View.OnDpiChanged" => "Se produit quand la fenêtre passe sur un écran d'une autre mise à l'échelle.",
        "View.OnHelpButtonClicked" => "Se produit quand on clique sur le bouton d'aide de la barre de titre.",
        "View.OnCaptionButtonClick" => "Se produit quand on clique sur l'un de vos boutons de la barre de titre (CaptionButtons) : e.id dit lequel.",
        "View.OnMdiChildActivate" => "Se produit quand un document MDI devient actif dans la fenêtre, ou qu'il se ferme.",
        "View.OnSearchClicked" => "Se produit quand on clique sur le bouton de recherche de la barre de titre (ShowSearch).",
        "View.OnNotificationsClicked" => "Se produit quand on clique sur la cloche des notifications de la barre de titre (ShowNotifications).",
        "View.OnSettingsClicked" => "Se produit quand on clique sur le bouton des paramètres de la barre de titre (ShowSettings).",
        "View.OnHelpClicked" => "Se produit quand on clique sur le bouton d'aide de l'en-tête dans la barre de titre (ShowHelp).",
        _ => return None,
    })
}

/// The French documentation of `component`'s event `event`: the component's own entry,
/// else the common one (`*.<event>`), else the view event's (`View.<event>`).
pub fn event_french(component: &str, event: &str) -> Option<&'static str> {
    french(&key(component, Some(event))).or_else(|| french(&key("*", Some(event)))).or_else(|| french(&key("View", Some(event))))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every registered component, property and event has its French documentation, and every English
    /// `doc` reads as user text (no code or implementation vocabulary - those go in code comments).
    #[test]
    fn every_registry_member_is_documented_for_users_in_both_languages() {
        for meta in crate::registry::builtins() {
            let mut members: Vec<(Option<&str>, &str)> = vec![(None, meta.doc)];
            members.extend(meta.properties.iter().map(|p| (Some(p.name), p.doc)));
            members.extend(meta.events.iter().map(|e| (Some(e.name), e.doc)));
            for (member, doc) in members {
                let k = key(meta.name, member);
                assert!(french(&k).is_some(), "no French doc for {k}");
                for word in ["`", "replica", "::", "crate", "module doc"] {
                    assert!(
                        !doc.contains(word),
                        "{k}'s doc is not user text ({word:?}): {doc}"
                    );
                }
            }
        }
    }

    /// The properties every control inherits (and the view's) are documented in both languages, in user
    /// words, whatever element inherits them.
    #[test]
    fn inherited_and_view_properties_are_documented_for_users_in_both_languages() {
        for meta in crate::registry::builtins() {
            for (level, p) in meta.all_properties() {
                assert!(property_french(meta.name, p.name, level).is_some(), "no French doc for {}.{} ({level:?})", meta.name, p.name);
            }
        }
        let levels = crate::registry::LEVELS.iter().flat_map(|l| l.properties.iter().map(move |p| (l.name, p)));
        for (level, p) in levels {
            assert!(french(&key(level, Some(p.name))).is_some(), "no French doc for {level}.{}", p.name);
            for word in ["`", "replica", "::", "crate", "module doc"] {
                assert!(!p.doc.contains(word), "{level}.{}'s doc is not user text ({word:?}): {}", p.name, p.doc);
            }
        }
    }

    #[test]
    fn common_and_view_events_are_documented_in_french() {
        for e in super::super::COMMON_EVENTS {
            assert!(french(&key("*", Some(e.name))).is_some(), "no French doc for *.{}", e.name);
        }
        for e in super::super::VIEW_EVENTS {
            assert!(french(&key("View", Some(e.name))).is_some(), "no French doc for View.{}", e.name);
        }
        for meta in crate::registry::builtins() {
            for e in meta.all_events() {
                assert!(event_french(meta.name, e.name).is_some(), "{}.{}", meta.name, e.name);
            }
        }
    }
}
